### ISSUE TITLE
[BUG] Your e-mail is not working

### ISSUE THREAD

**Issue by lennert1986** [Attendize/Attendize#1005]
**Describe the bug**
I cant send you an email. Support and hello emails...

Your message couldn't be delivered to catchall@attendize.com because the remote server is misconfigured. See technical details below for more information.

The response was:
A delivery loop was detected which causes this email to be undeliverable.

I send it from a @gmail.com

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment the bug happens in (Desktop, Mobile, CLI) (please complete the following information):**

**Version of Attendize you are using**

**Where you are running Attendize**

**What version or Operating System are you using on the above server**

**What version of PHP you are using on the above server**

**What web server are you using Attendize with**

**Additional context**

**Comment by johannac** [comment]
This is fixed.
