### ISSUE TITLE
Error when executing "make setup"

### ISSUE THREAD

**Issue by ShadowGamb** [Attendize/Attendize#1006]
Does anyone have a clue how to solve this? Getting this everytime when i want to execute "make setup"

standard_init_linux.go:228: exec user process caused: exec format error
The command '/bin/sh -c apt-get update && apt-get install -y wait-for-it libxrender1' returned a non-zero code: 1
make: *** [Makefile:5: build] Fehler 1

**Comment by quentincaffeino** [comment]
Please do `make setup SHELL=sh\ -x &> log` and post `log` file here

**Comment by ShadowGamb** [comment]
[log.txt](https://github.com/Attendize/Attendize/files/7572458/log.txt)

**Comment by quentincaffeino** [comment]
The problem is that you are running ARMv7 (is that raspberry or some kind of surface tablet?) and parent image `wyveo/nginx-php-fpm` isn't built for that architecture.

What you can try is to:

1. clone https://github.com/wyveo/nginx-php-fpm
2. checkout to branch `php74`
3. Execute `docker build -t wyveo/nginx-php-fpm:php74`

This would create an image for your architecture.

Then you can get back to make setup.

Note: if it still says that image is for amd64 try clearing build cache by running `docker system prune`

If you get an error on any apt command that means it probably could not be built for your architecture because target package for your arch is missing. But that shouldn't really happen

**Comment by ShadowGamb** [comment]
Can follow your instructions till 3. After I execute the docker build command, i get the following error:


root@raspberrypi:/home/pi/nginx-php-fpm# docker build -t wyveo/nginx-php-fpm:php74
"docker build" requires exactly 1 argument.
See 'docker build --help'.

Usage:  docker build [OPTIONS] PATH | URL | -

Build an image from a Dockerfile

**Comment by quentincaffeino** [comment]
Yeah, sorry I forgot dot at the end, use this:

`docker build -t wyveo/nginx-php-fpm:php74 .`

**Comment by ShadowGamb** [comment]
Thank you, but i think there is a general problem about running it on a raspberry.

E: Version '1.19.10-1~buster' for 'nginx' was not found
The command '/bin/sh -c buildDeps='curl gcc make autoconf libc-dev zlib1g-dev pkg-config'     && set -x     && apt-get update     && apt-get install --no-install-recommends $buildDeps --no-install-suggests -q -y gnupg2 dirmngr wget apt-transport-https lsb-release ca-certificates     &&     NGINX_GPGKEY=573BFD6B3D8FBC641079A6ABABF5BD827BD9BF62;      found='';       for server in                   ha.pool.sks-keyservers.net              hkp://keyserver.ubuntu.com:80                   hkp://p80.pool.sks-keyservers.net:80                 pgp.mit.edu     ; do            echo "Fetching GPG key $NGINX_GPGKEY from $server";             apt-key adv --batch --keyserver "$server" --keyserver-options timeout=10 --recv-keys "$NGINX_GPGKEY" && found=yes && break;          done;     test -z "$found" && echo >&2 "error: failed to fetch GPG key $NGINX_GPGKEY" && exit 1;     echo "deb http://nginx.org/packages/mainline/debian/ buster nginx" >> /etc/apt/sources.list     && wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg     && echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/php.list     && apt-get update     && apt-get install --no-install-recommends --no-install-suggests -q -y             apt-utils             nano             zip             unzip             python-pip             python-setuptools             git             libmemcached-dev             libmemcached11             libmagickwand-dev             nginx=${NGINX_VERSION}             php7.4-fpm             php7.4-cli             php7.4-bcmath             php7.4-dev             php7.4-common             php7.4-json             php7.4-opcache             php7.4-readline             php7.4-mbstring             php7.4-curl             php7.4-gd             php7.4-imagick             php7.4-mysql             php7.4-zip             php7.4-pgsql             php7.4-intl             php7.4-xml             php-pear     && pecl -d php_suffix=7.4 install -o -f redis memcached     && mkdir -p /run/php     && pip install wheel     && pip install supervisor supervisor-stdout     && echo "#!/bin/sh\nexit 0" > /usr/sbin/policy-rc.d     && rm -rf /etc/nginx/conf.d/default.conf     && sed -i -e "s/;cgi.fix_pathinfo=1/cgi.fix_pathinfo=0/g" ${php_conf}     && sed -i -e "s/memory_limit\s*=\s*.*/memory_limit = 256M/g" ${php_conf}     && sed -i -e "s/upload_max_filesize\s*=\s*2M/upload_max_filesize = 100M/g" ${php_conf}     && sed -i -e "s/post_max_size\s*=\s*8M/post_max_size = 100M/g" ${php_conf}     && sed -i -e "s/variables_order = \"GPCS\"/variables_order = \"EGPCS\"/g" ${php_conf}     && sed -i -e "s/;daemonize\s*=\s*yes/daemonize = no/g" /etc/php/7.4/fpm/php-fpm.conf     && sed -i -e "s/;catch_workers_output\s*=\s*yes/catch_workers_output = yes/g" ${fpm_conf}     && sed -i -e "s/pm.max_children = 5/pm.max_children = 4/g" ${fpm_conf}     && sed -i -e "s/pm.start_servers = 2/pm.start_servers = 3/g" ${fpm_conf}     && sed -i -e "s/pm.min_spare_servers = 1/pm.min_spare_servers = 2/g" ${fpm_conf}     && sed -i -e "s/pm.max_spare_servers = 3/pm.max_spare_servers = 4/g" ${fpm_conf}     && sed -i -e "s/pm.max_requests = 500/pm.max_requests = 200/g" ${fpm_conf}     && sed -i -e "s/www-data/nginx/g" ${fpm_conf}     && sed -i -e "s/^;clear_env = no$/clear_env = no/" ${fpm_conf}     && echo "extension=redis.so" > /etc/php/7.4/mods-available/redis.ini     && echo "extension=memcached.so" > /etc/php/7.4/mods-available/memcached.ini     && ln -sf /etc/php/7.4/mods-available/redis.ini /etc/php/7.4/fpm/conf.d/20-redis.ini     && ln -sf /etc/php/7.4/mods-available/redis.ini /etc/php/7.4/cli/conf.d/20-redis.ini     && ln -sf /etc/php/7.4/mods-available/memcached.ini /etc/php/7.4/fpm/conf.d/20-memcached.ini     && ln -sf /etc/php/7.4/mods-available/memcached.ini /etc/php/7.4/cli/conf.d/20-memcached.ini     && curl -o /tmp/composer-setup.php https://getcomposer.org/installer     && curl -o /tmp/composer-setup.sig https://composer.github.io/installer.sig     && php -r "if (hash('SHA384', file_get_contents('/tmp/composer-setup.php')) !== trim(file_get_contents('/tmp/composer-setup.sig'))) { unlink('/tmp/composer-setup.php'); echo 'Invalid installer' . PHP_EOL; exit(1); }"     && php /tmp/composer-setup.php --no-ansi --install-dir=/usr/local/bin --filename=composer --version=${COMPOSER_VERSION}     && rm -rf /tmp/composer-setup.php     && rm -rf /tmp/pear     && apt-get purge -y --auto-remove $buildDeps     && apt-get clean     && apt-get autoremove     && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100

**Comment by ShadowGamb** [comment]
Here's the complete log for analysis

[log.txt](https://github.com/Attendize/Attendize/files/7574577/log.txt)

**Comment by quentincaffeino** [comment]
As you can see it tries to apt install nginx=1.19.10-1~buster, this version is pretty old so no wonder it's no longer in repos. I would just remove the specific version part (`=1.19.10-1~buster`) from Dockerfile.

However to be honest I don't think it would be very performant on raspberry. I tried default setup on cheapest 1cpu 1gb ram digitalocean instance and for 75% requests I got 500. I got it to around 5% (if I recall correctly) error rate by splitting node and php services where node serves all static resources. And I added swoole to php. Also applied different optimizations where it possible. With node I enabled gzip and brotli, and php I enabled all optimizations flags in composer and artisan.

**Comment by ShadowGamb** [comment]
I removed "ENV NGINX_VERSION 1.19.10-1~buster" from the Dockerfile, then i got the error E: Version '' for 'nginx' was not found

**Comment by quentincaffeino** [comment]
You can revert your change. You need to remove it on line 45 so it will look something like this:

`nginx \`

Note you also need to remove equals sign

**Comment by ShadowGamb** [comment]
Seems fine now, but i got some problems with phpize, but it is installed. Is there an additional step for that?
[log.txt](https://github.com/Attendize/Attendize/files/7583374/log.txt)

**Comment by quentincaffeino** [comment]
No idea)

**Comment by ShadowGamb** [comment]
Ok, but anyways thanks for your help :)
