### ISSUE TITLE
Integraton to Wordpress

### ISSUE THREAD

**Issue by JoopStringer** [Attendize/Attendize#1007]
Is there any integration to MemberPress Wordpress plugin ?

**Comment by storca** [comment]
Hey
Have a look at the "Widgets" pane in Attendize, there is html that you can embed in your wordpress pages.

**Comment by clawfire** [comment]
> Is there any integration to MemberPress Wordpress plugin ?

Memberpress looks like doing kinda the same but for managing membership. Why not asking memberpress developers to know if they want to work on some kind of integration ?
