### ISSUE TITLE
After installation, Attendize is not working (digitalocean LAMP Ubuntu 20.04)

### ISSUE THREAD

**Issue by goma786** [Attendize/Attendize#1010]

**Comment by jigzstar** [comment]
1. You're missing some php extensions:
mbstring, dom, and simplexml. 

2. Since you on PHP 8, it might be causing issues, with the package versions in the composer, so can either drop down to php 7.4, or fork the repo and update the composer json.

**Comment by paws13** [comment]
@agennx I have just gone though the setup process on a VM and after a lot of messing about, I have gotten it to work. I encountered the same errors as you I think at the start. Check out the last post in the L1T forum [here](https://forum.level1techs.com/t/attendize-ticketing-system-server-build/186066/10) for a line by line instruction on how to install and get running (server side anyway).
