### ISSUE TITLE
[BUG] Demo website broken

### ISSUE THREAD

**Issue by majerus1223** [Attendize/Attendize#1013]
**Describe the bug**
Demo site goes to a broken domain

**To Reproduce**
1. Navigate to https://github.com/Attendize/Attendize#attendize
2. Click on Demove Event Page, Demo Back-end Demo links
3. Taken to landing page without a demo

**Expected behavior**
Launch a demo of the product 
![Links off of readme](https://user-images.githubusercontent.com/7389171/149961057-df3c703b-37cf-4504-811f-bca9e09c8a58.png)

![Broken Demo Site](https://user-images.githubusercontent.com/7389171/149961098-4cbcb75b-1736-4410-acea-a45b50f3fd9d.png)

**Comment by clawfire** [comment]
Yep well, a lot of links on the official website & Github documentation are broken :(

**Comment by johannac** [comment]
Thanks for letting me know about the broken links! I've fixed them in the README now. The demo site is no longer available, it was mostly being used for spam and some people trying to actually run events on it ☹️  I may bring it back in the future if people think it's really needed, but it will need some better devops set up to prevent it from getting used incorrectly.
