### ISSUE TITLE
Questions about the attendize license

### ISSUE THREAD

**Issue by martinhyper** [Attendize/Attendize#1014]
Hi everyone, I'm new to attendize. Is there any contact point for asking questions about the support license please? I've tried the email addresses on attendize.com but these only returned errors. Thankyou in advance for any help!  Martin

**Comment by ugintl** [comment]
I also have the similar question about the license. What if I want to remove attribution?

**Comment by johannac** [comment]
Email is working again, please feel free to send us any questions. Any of the 3 licenses allow you to remove the 'powered By Attendize' attribution, but redistribution is still restricted.
