### ISSUE TITLE
What is the Super Administrator login?

### ISSUE THREAD

**Issue by dzulhelmi** [Attendize/Attendize#102]
Once installed, go to /signup, so the account created there is the Administrator account? How can I login as the Administrator/Super Admin account? Not just or Account Owner/Organiser

**Comment by ylecuyer** [comment]
AFAIK there is no super admin role in attendize

**Comment by daveearley** [comment]
There is no super admin yet, however, you can [alter the base model slightly](https://github.com/Attendize/Attendize/blob/46c25776066fd4aef68373dfff5545c7cdb894f5/app/Models/MyBaseModel.php#L143) to allow you do browse events etc. from all accounts.
