### ISSUE TITLE
[BUG] Due to stripe adding Strong Customer Authentication (SCA) I am getting more than 50% of transactions failing.

### ISSUE THREAD

**Issue by TMDesigns** [Attendize/Attendize#1020]
Due to stripe adding [Strong Customer Authentication (SCA)](https://59.email.stripe.com/CL0/https:%2F%2Fstripe.com%2Fsca/1/0101017f6af5631c-b35b48bf-f02b-4392-b613-9f5bb2cbd590-000000/uA94U9FnXb6RKxZuQw4vmzO36JIkftQMV7Q4m-4pMOc=240) I am getting more than 50% of transactions failing.

The stripe integration need looking at.

**Comment by MacBadger** [comment]
This is handled by stripe. If you go into your Stripe account you can see why items are being declined and alter the conditions for denial. Of course you are at greater risk of chargebacks if payments go through more easily.

**Comment by TMDesigns** [comment]
The issue in stripe says:

The bank required 3D Secure authentication for this payment. [Update your integration](https://stripe.com/docs/payments/3d-secure) to set up 3D Secure authentication.

I presume the stripe integration needs updating in attendize

**Comment by storca** [comment]
You have to change the option in the payment gateway configuration ui, choose 'Stripe SCA' and not 'Stripe'.
