### ISSUE TITLE
The website is down! Installation guide?

### ISSUE THREAD

**Issue by giorgiogiudice** [Attendize/Attendize#1022]
Hello beautiful people. 
attendize.com is down :(. Anyone happens to have the guideline for attendize manual installation?

Thank you all.

Peace

**Comment by storca** [comment]
Head here to get the instructions

https://web.archive.org/web/20201029080016/https://www.attendize.com/getting_started.html

**Comment by giorgiogiudice** [comment]
Thank you!!!

**Comment by johannac** [comment]
Thanks all! Currently in the process of changing ownership of this project, it's no longer owned by Vitis Events, it's owned by myself individually. So am moving around accounts, DNS etc. The web site is now back up. Working on email next.

**Comment by btsteve** [comment]
@johannac Does that mean we will be seeing updates. We looked at using the project and were going to purchase a license a few years ago but never got a response from anyone.

**Comment by johannac** [comment]
Yes there will be updates coming! I have a lot to organize still, with all the open issues and PRs here but I'm hoping to get things rolling again soon.
