### ISSUE TITLE
Problem while generating a PDF ticket

### ISSUE THREAD

**Issue by EpikCloudFR** [Attendize/Attendize#1045]
Hi everybody !
I have some problems with the PDF generator on Attendize. When I try to generate a ticket for download, an error appear.

`System error <pre>Unable to load library icui18n "Cannot load library icui18n: (icui18n: cannot open shared object file: No such file or directory)"`

Do you know how can I resolve it ?
I am running Attendize v2.5.0 on Debian Bullseye with Apache2 (php 7.4)

**Comment by HenryDelgadoLoza** [comment]
Text me +51@9@4@1@9@06@5@8@9
