### ISSUE TITLE
Attendee reference

### ISSUE THREAD

**Issue by ylecuyer** [Attendize/Attendize#106]
Unless attendees are created through an order the reference is wrong.

As the reference number for an attendee is the reference of the order followed by the attendee id it should not be denormalized in the attendee table. There there reference column of the attendees table should be removed and a function to retrieve the attendee reference should be added to the Attendee model

**Comment by JapSeyz** [comment]
I can not recreate this.

I've added an attendee through "Add Attendee" on the event page, but everything works flawlessly. Could you give me the exact steps to recreate the issue?

Along with expected and actual outcomes of the action?

**Comment by ylecuyer** [comment]
If the attendee reference is the order reference folowed by the attendee index in that order then this line is wrong https://github.com/Attendize/Attendize/blob/master/app/Commands/SendAttendeeTicketCommand.php#L68

**Comment by JapSeyz** [comment]
I am afraid I don't follow. That line shows the exact thing you just said - it shows the order reference followed by the attendee index.

**Comment by daveearley** [comment]
As it stands now an order is always created alongside an attendee, so the attendee reference should be right. There is a bug [here](https://github.com/Attendize/Attendize/blob/master/app/Commands/SendAttendeeTicketCommand.php#L68  ) however, it only affects the name of the PDF though. I'll fix that now.

Also, It definitely is redundant to have the order ID stored with every attendee, so I'll add changing that to the to-do list!
