### ISSUE TITLE
Security Header Not Valid

### ISSUE THREAD

**Issue by Aditya790** [Attendize/Attendize#114]
HI 
i am building a festival based event management website
I have installed your application on my server.
I have followed the instructions and created and event and ticket for that event. When testing out there was an error at the checkout page. (Please see the image)
I have used the Paypal API signature correctly but still error prevails.
Please help me on this matter.(I am a non tech guy and new to web development)
Thanks
![error](https://cloud.githubusercontent.com/assets/16581144/15541950/f95f5dba-228e-11e6-82f4-c01eb89e12ea.PNG)

**Comment by daveearley** [comment]
That error usually means either the API endpoint or your PayPal API credentials are incorrect. Double check your PayPal setting in the 'My Account' page and try again.

**Comment by Aditya790** [comment]
i recheked my paypal api credentials...but still error persists.

**Comment by Aditya790** [comment]
Hi
I am new to this whole thing of APIs...could you please tell me where to put my paypal credentials..i have rechecked my paypal credentials.

**Comment by daveearley** [comment]
If you click into the menu on the top right, then select **Account Settings** , then click the **Payment** tab. You enter your details there. 

If your PayPal information is definitely correct, try contacting PayPal support and see if they can assist you.

**Comment by Aditya790** [comment]
Thanks for the reply...my paypal credentials are right...one thing i noticed that once you put payment information in attendize only the API signature box is active...the other fields(paypal username and password) are inactive. Is it the problem from attendize?
Doesnt paypal need username and password other than API signature from attendize.

**Comment by Aditya790** [comment]
As i see the demo sample page at your site works also in the same fashion...same error pops up...."SECURITY HEADER NOT VALID"
http://attendize.website/e/1/checkout/create?is_embedded=0#order_form
Any help on this issue...shall i reinstall attendize again?...Can u install for me?...thanks in advance
![error_test](https://cloud.githubusercontent.com/assets/16581144/15632704/ddb2e852-259a-11e6-88c6-8d3b6e16a475.PNG)

**Comment by JapSeyz** [comment]
I doubt he can install it for you, does your server run in HTTPS.

My best guess would be that Paypal does not allow requests from non SSL domains.

**Comment by Aditya790** [comment]
I have installed the v0.5 system on my server...i removed and installed with v0.8..now the system works finally. Thanks for the support...I dont have HTTPS on my domain but i am able to check out and paypal is working

**Comment by aethatsme** [comment]
I'm getting this issue too.  Might by ominipay.

**Comment by daveearley** [comment]
I just tested this locally and it seems to be working. If you're using an older version try installing manually from GitHub if possible.
