### ISSUE TITLE
Email Settings Error

### ISSUE THREAD

**Issue by weezqyd** [Attendize/Attendize#116]
When i fill in Email settings on .env a blank page is displayed for any url/request, but when i comment out the email settings it works fine except on ticket checkout.

**Comment by daveearley** [comment]
It could be because you have a space in some settings in your .env, try wrapping any setting with spaces in quotes.

**Comment by bretto36** [comment]
I had the same issue, i had

MAIL_FROM_NAME=brett b
had to change to 
MAIL_FROM_NAME="brett b"
