### ISSUE TITLE
No /install on the extracted dir for attendize (as I think the manual instructions mention)

### ISSUE THREAD

**Issue by kdamianakis** [Attendize/Attendize#119]
Have been trying to install it via the manual method - have extracted the files but there is no install or install.php. Any advise?

**Comment by daveearley** [comment]
You should be be able to navigate to **yoursite.com/install** and see the installation page. If that doesn't work try **yoursite.com/public/install**.

**Comment by kstefanou52** [comment]
Same luck. The only thing I see in both pages is a completely blank page.

**Comment by kstefanou52** [comment]
Please see by yourself : 52.40.170.223/b2b/public
Thank you in advance

**Comment by kdamianakis** [comment]
Yes - I have tried both the /install and the /public/install and am getting

"The requested URL /public/install was not found on this server."

accessing it via the local subnet.

Also, there does not appear to be any files named '*install*'

**Comment by daveearley** [comment]
The '/install' part of the URL is virtual so no install file exists. Did you download the zip file from the Attendize.com website or install from GitHub? Also, does navigating to yoursite.com/index.php/install work?

**Comment by kdamianakis** [comment]
Hi, 

Thank you for this - it comes back from

The requested URL /index.php/install was not found on this server.

I extarcted the zip file but earlier on I created a VM and cloned the git with similar problems. Am using LAMP and have installed it under /var/www/html/*

Regards,
Konstantinos

**Comment by daveearley** [comment]
Are the folders **storage**, **public** and **bootstrap** all writable?

**Comment by kdamianakis** [comment]
Yes they are.. 777 (just to be safe).. perhaps there there is a step I am missing? Its ubuntu 16.10 with lamp^ installed..

**Comment by daveearley** [comment]
Does running **composer update** have any effect?

**Comment by kdamianakis** [comment]
Thanks again. This is what I get once I run it. Am a java dev and do not know much about the PHP side so cannot explain the message without googling..

Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - dompdf/dompdf dev-master requires ext-gd * -> the requested PHP extension gd is missing from your system.
    - dompdf/dompdf dev-master requires ext-gd * -> the requested PHP extension gd is missing from your system.
    - Installation request for dompdf/dompdf dev-master -> satisfiable by dompdf/dompdf[dev-master].

  To enable extensions, verify that they are enabled in those .ini files:
    - /etc/php/7.0/cli/php.ini
    - /etc/php/7.0/cli/conf.d/10-mysqlnd.ini
    - /etc/php/7.0/cli/conf.d/10-opcache.ini
    - /etc/php/7.0/cli/conf.d/10-pdo.ini
    - /etc/php/7.0/cli/conf.d/20-calendar.ini
    - /etc/php/7.0/cli/conf.d/20-ctype.ini
    - /etc/php/7.0/cli/conf.d/20-exif.ini
    - /etc/php/7.0/cli/conf.d/20-fileinfo.ini
    - /etc/php/7.0/cli/conf.d/20-ftp.ini
    - /etc/php/7.0/cli/conf.d/20-gettext.ini
    - /etc/php/7.0/cli/conf.d/20-iconv.ini
    - /etc/php/7.0/cli/conf.d/20-json.ini
    - /etc/php/7.0/cli/conf.d/20-mysqli.ini
    - /etc/php/7.0/cli/conf.d/20-pdo_mysql.ini
    - /etc/php/7.0/cli/conf.d/20-phar.ini
    - /etc/php/7.0/cli/conf.d/20-posix.ini
    - /etc/php/7.0/cli/conf.d/20-readline.ini
    - /etc/php/7.0/cli/conf.d/20-shmop.ini
    - /etc/php/7.0/cli/conf.d/20-sockets.ini
    - /etc/php/7.0/cli/conf.d/20-sysvmsg.ini
    - /etc/php/7.0/cli/conf.d/20-sysvsem.ini
    - /etc/php/7.0/cli/conf.d/20-sysvshm.ini
    - /etc/php/7.0/cli/conf.d/20-tokenizer.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

**Comment by daveearley** [comment]
The problem could be that you don't have the dependencies installed. have a [look here](https://attendize.com/documentation.php#requirements) and see if everything is installed.

**Comment by kstefanou52** [comment]
All the dependencies has been installed and I still have the same problem. 
Any help ?

**Comment by kstefanou52** [comment]
I opened the /public from chrome browser (I use safari) and I get this error : my-site is currently unable to handle this request. HTTP ERROR 500 

Thank you in advance,
KS
