### ISSUE TITLE
Problem after installation on ubuntu server

### ISSUE THREAD

**Issue by kstefanou52** [Attendize/Attendize#120]
Greetings,

I have spent the last 2 days in installing attendize but still no luck.
I tried manual install and I didn't have any error but when I go to the my-site.com/attendize/public I see a white blank page telling me "Whoops, looks like something went wrong." as you can see on the image that I attached.
I checked my postgreDB and attendize has gain access and has create tables and etc.

I managed to get the Apache errors log. -->
[ApacheErrorsLog.txt](https://github.com/Attendize/Attendize/files/293557/ApacheErrorsLog.txt)

Thank you in advance,
KS

![error3052](https://cloud.githubusercontent.com/assets/19667647/15693186/03433e34-279c-11e6-9039-87fc1a53062c.png)

**Comment by daveearley** [comment]
Hi @kstefanou52, it looks like it may be an issue with the Cypher setting in Laravel. Have a[ look here](http://stackoverflow.com/questions/31512970/laravel-no-supported-encrypter-found-the-cipher-and-or-key-length-are-invalid) and see if any of the answers solve your issue. Cheers.
