### ISSUE TITLE
sales_volume increment doesnt work

### ISSUE THREAD

**Issue by kiuka** [Attendize/Attendize#121]
Hello,

You have changed (https://github.com/Attendize/Attendize/commit/17cf0b4a1cc4308804a0a83cd5a79470ce70c1d3) the type of columns such as sales_volume, organiser_fees_volume, etc to nullable, but Laravel's increment method does not update this columns when contain NULL as a value.

**Comment by daveearley** [comment]
Cheers @kiuka , I'll fix this shortly.

**Comment by clawfire** [comment]
Is it possible to create a new release integrating this patch ?

**Comment by daveearley** [comment]
There will be a new release published later this evening which will contain all bug fixes/features which have been added over the past few months.

**Comment by daveearley** [comment]
The latest version has been uploaded on the the [website](https://attendize.com/documentation.php#download) now.
