### ISSUE TITLE
Error when trying to install/config 

### ISSUE THREAD

**Issue by eidercarlos** [Attendize/Attendize#122]
I get this following log after trying to install/config to use Attendize:

[2016-06-07 14:15:13] development.ERROR: exception 'Illuminate\Session\TokenMismatchException' in /Applications/AMPPS/www/Attendize/bootstrap/cache/compiled.php:2929
Stack trace:
#0 /Applications/AMPPS/www/Attendize/app/Http/Middleware/VerifyCsrfToken.php(24): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#1 [internal function]: App\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#2 /Applications/AMPPS/www/Attendize/bootstrap/cache/compiled.php(9547): call_user_func_array(Array, Array)
#3 /Applications/AMPPS/www/Attendize/bootstrap/cache/compiled.php(12875): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#4 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#5 /Applications/AMPPS/www/Attendize/bootstrap/cache/compiled.php(9547): call_user_func_array(Array, Array)
#6 /Applications/AMPPS/www/Attendize/bootstrap/cache/compiled.php(11498): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#7 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#8 /Applications/AMPPS/www/Attendize/bootstrap/cache/compiled.php(9547): call_user_func_array(Array, Array)
#9 /Applications/AMPPS/www/Attendize/bootstrap/cache/compiled.php(12616): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#10 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#11 /Applications/AMPPS/www/Attendize/bootstrap/cache/compiled.php(9547): call_user_func_array(Array, Array)
#12 /Applications/AMPPS/www/Attendize/bootstrap/cache/compiled.php(12555): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#13 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#14 /Applications/AMPPS/www/Attendize/bootstrap/cache/compiled.php(9547): call_user_func_array(Array, Array)
#15 /Applications/AMPPS/www/Attendize/bootstrap/cache/compiled.php(2977): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#16 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#17 /Applications/AMPPS/www/Attendize/bootstrap/cache/compiled.php(9547): call_user_func_array(Array, Array)
#18 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#19 /Applications/AMPPS/www/Attendize/bootstrap/cache/compiled.php(9537): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#20 /Applications/AMPPS/www/Attendize/bootstrap/cache/compiled.php(2250): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#21 /Applications/AMPPS/www/Attendize/bootstrap/cache/compiled.php(2233): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#22 /Applications/AMPPS/www/Attendize/public/index.php(52): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#23 {main}  

Ps.: I have already replaced the new EventOrdersController file you provided...

**Comment by JapSeyz** [comment]
When exactly do you get the error?
It's a CSRF token that's missing from the form.
