### ISSUE TITLE
Customize 'Attendee' Questions

### ISSUE THREAD

**Issue by VigWatch** [Attendize/Attendize#13]
Some events need fields for asking questions, like 'T-Shirt Size' or 'Badge Name', to be asked to attendees during the registration process. Should be defined per ticket type.

**Comment by Attendize** [comment]
This is a definitely a necessity. Added this to the v1.0.0 milestone.

I started work on this previously but never finished it, so the DB is already set up for it.

**Comment by G0dLik3** [comment]
@Attendize How do you want to implement this? Maybe I can help...

**Comment by daveearley** [comment]
I'm not entirely sure yet. I was thinking maybe do something similar to [how Eventbrite does it](https://www.eventbrite.ie/support/articles/en_US/How_To/how-to-create-custom-questions-for-attendees?lg=en_IE), where you can assign question to each attendee or only the buyer.

For the the UI I think an extra 'Questions' tab on the event customize page, where you can assign questions to tickets.

I got a start on the [migrations a while back](https://github.com/Attendize/Attendize/blob/master/database/migrations/2014_03_26_180116_create_users_table.php#L329) but never got around to fully implementing it.

Any suggestions welcome!

**Comment by G0dLik3** [comment]
I see. But I'm having trouble with accessing the event customization page... I get a "The connection was reset." error. Tracked it down to the compileComments method from within the BladeCompiler class...

**Comment by daveearley** [comment]
Hmm not too sure what's causing that. Are there any errors in the log file Storage/logs?

**Comment by G0dLik3** [comment]
It occurs when compileComments tries to compile the multi-line comments from  resources/views/ManageEvent/Customize.blade.php ... Not sure why.

**Comment by daveearley** [comment]
I can't replicate it locally, but I've removed the multi-line comments. Hopefully that sorts it.

**Comment by G0dLik3** [comment]
I have a question: in the migration, why do you have $t->text('options'); for the 'questions' table and also create a separate 'question_options' table?

**Comment by daveearley** [comment]
As far as I remember the **$t->text('options');** is redundant in favor of storing the options in their own table. Having said that I'm not pushed on sticking with what I already had in favor of better ideas etc.

The **questions.instructions** would be an optional prompt for the user, giving them additional information related to a questions.

e.g:

Question title: **What is your phone number?**
Question instructions: _Please enter in the format +000-000-0000_
