### ISSUE TITLE
Payment error message disappears too quickly

### ISSUE THREAD

**Issue by kasbah** [Attendize/Attendize#130]
Testing out my Stripe setup the error message that comes in at the top disappears too quickly. Had to quickly copy and paste it in order to read it.

**Comment by bretto36** [comment]
I think it's set at 2.5 seconds, should we up this to 5 or 10 seconds?

**Comment by daveearley** [comment]
I don't see any reason why it shouldn't be upped. The notifications are powered by [humane.js](http://wavded.github.io/humane-js/) so there's a few different options you can add to make them more user friendly.

**Comment by bretto36** [comment]
I'm adding the following parameters 


        timeout: 60000,
        timeoutAfterMove: 2500,
        waitForMove: true

so that means by default if you don't move the mouse the message last 60 seconds, after you move it closes in 2.5 seconds

**Comment by bretto36** [comment]
Couldn't add the timeout as a back up, can only have one or the other. #136

**Comment by bretto36** [comment]
@kasbah Can you give this a test and close it if the messages remain long enough. Cheers

**Comment by kasbah** [comment]
Looks good to me now.
