### ISSUE TITLE
responsive-embeds missing

### ISSUE THREAD

**Issue by JapSeyz** [Attendize/Attendize#131]
If we look at [bootstrap.less](https://github.com/Attendize/Attendize/blob/master/public/vendor/bootstrap/less/bootstrap.less#L38)
it includes a non-existant file called responsive-embed. (There's also a few other things that's missing) I am unable to run `grunt less` and properly submit my UI updates.

**Comment by daveearley** [comment]
Not sure why this is happening,  but it can be fixed by deleting the vendor/bootstrap folder and then running **bower update bootstrap**. I'm not at a computer so can't do it atm.

**Comment by bretto36** [comment]
I was getting the same issue, but deleting the folder sorted it out. The folder is in public/vendor/bootstrap for anyone else who didn't know what Dave meant.
