### ISSUE TITLE
Changing name or email in "My Profile" does not work

### ISSUE THREAD

**Issue by kasbah** [Attendize/Attendize#134]
From the organizer dashboard menu, under "My profile". 

- If I try and change my name in the user profile and hit save it doesn't get saved upon closing and re-opening
- If I try and change the email it says "This E-mail has is already in use."

**Comment by bretto36** [comment]
This will be fixed by tomorrow. Have changed the code just waiting for merging

**Comment by bretto36** [comment]
This has been merged. Can you update your code and close if this is fixed

**Comment by kasbah** [comment]
Works great now, thanks!
