### ISSUE TITLE
I'd like to have /o/1 as root and only /login on explicit login

### ISSUE THREAD

**Issue by kasbah** [Attendize/Attendize#137]
Is it possible with the env or hacking the source, or not yet? Could do a work-around with Nginx config but thought I would ask.

**Comment by kasbah** [comment]
This is my current work-around in the Nginx config. 

```nginx        
location = / {
	rewrite ^ /o/1 redirect;
}

#still keep this from the standard config
location / {
	try_files $uri $uri/ /index.php$is_args$args;
}

```

**Comment by daveearley** [comment]
You'll be able to choose an event, organiser or login as the root page soon. I began working on the feature a few weeks ago but put it too the side.

**Comment by bagage** [comment]
@daveearley any news about that feature?

**Comment by etiennemarais** [comment]
Closing this due to age

**Comment by bagage** [comment]
Was it solved @etiennemarais? Looking forward to it!

**Comment by etiennemarais** [comment]
@bagage no sorry. We are cleaning out old issues with no progress on them. Please log a new issue if this is still a burning problem or submit a pull request with the changes but it's not something we are able to pick up in the short term.
