### ISSUE TITLE
Add the ability to re-send tickets to an attendee

### ISSUE THREAD

**Issue by Attendize** [Attendize/Attendize#14]

**Comment by bretto36** [comment]
Hi, i'm not sure of the name of the person who is heading up development. I've just added a pull request for this change. I'm new to laravel, so please make any comments as to whether my code is crap. I'm mostly coming from a symfony style framework and still trying to find my way around laravel. 

I'll be doing bits and pieces so feel free to assign me stuff that is within my knowledge level

**Comment by daveearley** [comment]
Nice work on this @bretto36 ! It all looks fine. Feel free work away on anything in the issues, or suggest anything else you think would be a good addition. I'll post under any issue I'm actively working so you'll know if there's any crossover.

Appreciate the help!
