### ISSUE TITLE
Unable to load the app - empty output

### ISSUE THREAD

**Issue by hubiktomas** [Attendize/Attendize#141]
When trying to load homepage, I am getting this error:
`PHP Fatal error:  Can't inherit abstract function Illuminate\\Support\\Manager::getDefaultDriver() (previously declared abstract in Illuminate\\Session\\SessionManager) in /var/www/xyz/bootstrap/cache/compiled.php on line 12369
`
The installation from git finished without problems.

Using PHP 7.0.7-4

Thanks for any help.

Tomas

**Comment by daveearley** [comment]
Try running **php artisan clear-compiled** followed by **php artisan optimize** and see if that fixes the issue.

**Comment by hubiktomas** [comment]
Thanks for the tip. The execution went without any problems. However the issue remains.

**Comment by daveearley** [comment]
Any updates on this? does the suggestion mentioned here help at all: https://www.reddit.com/r/PHP/comments/4qc3ck/laravel_performance_tuning/d4s004j

**Comment by hubiktomas** [comment]
Thank you very much Removing bootstrap/cache/compiled.php helped - I can see the signup page now, but is it really a solution? I am afraid of some performance issues...

**Comment by daveearley** [comment]
If you run  **php artisan optimize --force** does everything still work?

**Comment by hubiktomas** [comment]
No, it does not and new compiled.php file gets generated.

**Comment by daveearley** [comment]
What are the details of the environment you're running in? I'll see if I can replicate the issue on my side and find a solution.

**Comment by hubiktomas** [comment]
I have sent the info to your mail mentioned in license file. I do not want to expose so detailed info here in public. We can then post the relevant part here if we find the cause. Thank you very much.

**Comment by jeremyquinton** [comment]
As this issue is over 2 years old I am closing it off.
