### ISSUE TITLE
Add users to organizer

### ISSUE THREAD

**Issue by kasbah** [Attendize/Attendize#145]
I was hoping I could add registered users to my organizer but this doesn't seem to be the case. Is this planned or is it supposed to work some other way?

**Comment by bretto36** [comment]
So does the invite section only allow you to add non registered users?

**Comment by kasbah** [comment]
I haven't found an invite section to add people to an organizer. Are you thinking of an event or have I just missed it somewhere?

**Comment by kasbah** [comment]
Basically, I am trying to set this up for my Hackspace which is a community organization. I would like to give other users the ability to schedule Hackspace events. 

https://events.bristolhack.space

**Comment by bretto36** [comment]
If you click up the top right -> Account Settings -> there is a Users tab where you can invite people in

**Comment by kasbah** [comment]
Aha! I had done that before but didn't realise this would add to the organization. It would make more sense on the left somewhere or with the organization settings no?

I tested it out and the behaviour when you add existing users doesn't make much sense yet, but I guess that's expected for now.

I guess the workflow has to be that users not sign up themselves but only in response to invites for now?

**Comment by daveearley** [comment]
The user management will be beefed up soon. As it stands all users are equal. There's definitely needs to be a way to allocate permissions etc.
