### ISSUE TITLE
Add feature to have maximum tickets for an event

### ISSUE THREAD

**Issue by OmegaSyrus** [Attendize/Attendize#146]
Use case: optional payment events, where buying a ticket can be free or paid, but attendance is capped

I.e. Capacity for 300 people, but both tickets are available

**Comment by bretto36** [comment]
So there could be 300 paid people attend, or 300 free, or 150 free and 150 paid?

Seems like a fairly niche solution. Couldn't you just keep adjusting the number of tickets. assign 250 to free tickets and 50 to paid, and when the paid sell out or get close you could adjust the levels again

**Comment by daveearley** [comment]
I'd agree with @bretto36 here, adjusting the number of tickets on a per ticket basis seems to be the option suited to the majority currently.

**Comment by jimsug** [comment]
I would want this type of control - for example for performances where discounted tickets are available for children/students, etc. It this can be revisited, it would be appreciated.
