### ISSUE TITLE
Grace period for payments.

### ISSUE THREAD

**Issue by aethatsme** [Attendize/Attendize#151]
Is there a way to hold the funds before releasing them? maybe schedule when it will be released.

Event brite has something similar to where funds don't get released until requested. I believe this is is due to credit card chargebacks. 

I also like the idea of having a full admin where we can set a fee per transaction sitewide. This way the organizer can see the total amount sold before and after the fee when funds are released. This would be in addition to the organizer having the option to set their own fee.

**Comment by daveearley** [comment]
There's no way to hold funds currently. Unless it's added via a plug-in down the road It's unlikely this will every become an option as the instant availability of funds is the reason why many people choose Attendize in the first place. 

There will be defaults and site-wide settings added in the future, so you will be able to add site-wide transaction fees.

**Comment by aethatsme** [comment]
Would it be possible to have a more enterprise solution for the shopping cart? such as registering the user/customer at the checkout? https://github.com/hassansin/dbcart

Omnipay is great for quick express checkout but having a full shopping cart could possibly take care of the sitewide transaction fees and holding funds.
