### ISSUE TITLE
wkhtmltopdf didn't return any data

### ISSUE THREAD

**Issue by cmarfil** [Attendize/Attendize#154]
Hello,

First, thanks for package :)

I get error "wkhtmltopdf didn't return any data" in OrderCompletedListener.
I tried to set 777 to all project with same result..

Any idea?
Thanks!

**Comment by cmarfil** [comment]
I found the solution, you need to set the correct **os driver** for wkhtml2pdf in **config/wkhtml2pdf.php**.

The info about the drivers are here:
https://github.com/NitMedia/wkhtml2pdf

I suggest that in future this will be added in the documentation of the installation process.

Thanks and regards.

**Comment by daveearley** [comment]
Thanks @cmarfil , I'll update the config so it grabs the os driver value from the Attendize config in the future. Cheers!
