### ISSUE TITLE
Wkhtml2pdf 64 vs 32 bit

### ISSUE THREAD

**Issue by ketchuphed** [Attendize/Attendize#156]
I was having an error on Ubuntu 14.04 32 bit and the error involved wkhtmltopdf-amd64. I had to change config/Wkhtml2pdf.php binfile to wkhtmltopdf-i386 for the software to work correctly. are there any flaws i may expect from this point? or is there a more preferred way to set this variable?

**Comment by daveearley** [comment]
If you're able to generate tickets using the i386 bin file currently then you should be fine. There shouldn't be any noticeable flaws or decrease in performance.
