### ISSUE TITLE
Mixed 12/24 hrs time format in event page

### ISSUE THREAD

**Issue by KlausGPaul** [Attendize/Attendize#158]
On an event page, an event that is scheduled for 17:00-18:00 is shown as 5:00 PM-17:00 PM.

Very unfortunately, this bug affects somewhat both timestamps.

Klaus

**Comment by daveearley** [comment]
Thanks for flagging this. I'm very surprised it wasn't noticed before. I'll push a fix shortly.

Cheers!

**Comment by KlausGPaul** [comment]
Thanks for fixing this, but it now reads Thu 25 Aug 17:03 PM - 17:05 PM.

**Comment by daveearley** [comment]
Hi @KlausGPaul , is that for an event with the end date also on the 25th of Aug?

**Comment by KlausGPaul** [comment]
Yes, indeed, it was on the very same day. I am using a dockerized version, so if there were any time zone specific settings in the environment I assume it would not be any host timezone settings.
Note also, this installation uses the "old" database, I´ll double check with a fresh installation.

![snip_20160822054203](https://cloud.githubusercontent.com/assets/20340525/17843177/42f0476e-682b-11e6-8c0d-611947f199ed.png)
![snip_20160822054105](https://cloud.githubusercontent.com/assets/20340525/17843170/377215c0-682b-11e6-9897-ceca7c4a40e9.png)
![snip_20160822054131](https://cloud.githubusercontent.com/assets/20340525/17843173/3bb83844-682b-11e6-8bfc-b3d2fb0b2bc1.png)
