### ISSUE TITLE
Surveys cannot be edited as non-required

### ISSUE THREAD

**Issue by KlausGPaul** [Attendize/Attendize#159]
I had set up an event, and a survey. To make the survey applicable to the event, I was selecting "Require this question for ticket(s)..." . 

It was not obvious to me at the time that this would result in me mandatorily requiring all answers to be fille in, I had been assuming this was more of a "also show this survey question on that event". When I tried to edit/disable that setting I got an error response. It does not seem to be possible to change that setting via edit at the moment.

**Comment by daveearley** [comment]
The Survey functionality is very much in its infancy so there's a lot of bugs that need to be ironed out. Are there any messages related to the error in the log file in **Storage/logs**?

Cheers

**Comment by KlausGPaul** [comment]
No, the exported storage/logs is empty, so are the attendize_php and attendize_php-worker container´s storage/logs. Any other area I could check?

Didi I mention that you are doing a great job?

**Comment by daveearley** [comment]
What does the error say? also does the error appear when you are attempting to edit other questions?

Cheers

**Comment by johannac** [comment]
Fixed in #906
