### ISSUE TITLE
The use statement with non-compound name 'DB' has no effect

### ISSUE THREAD

**Issue by userj** [Attendize/Attendize#160]
I am getting this error:
The use statement with non-compound name 'DB' has no effect

every time I run 

php artisan attendize:install

seems to only have started recently

**Comment by ivansalomon** [comment]
Mix manual install and the via web. 
Clone attendize
Composer install 
Create a database in mysql or other DB
Php artisan serve
Go to site http://localhost:8000/install
Done! 
Good luck!

**Comment by daveearley** [comment]
This should be fixed now, an unnecessary use statement was causing it to fail.

**Comment by userj** [comment]
Thanks for the suggestions and fixes :)
