### ISSUE TITLE
French localisation

### ISSUE THREAD

**Issue by guidtz** [Attendize/Attendize#161]
Hello,

   how can we translate attendize interface in french language ?

Regards

**Comment by daveearley** [comment]
Unfortunately Attendize isn't internationalized yet, so the only way to add the French language would be to manually change the views. I18n is high on the list of priorities however, so it will be added in the coming months.

**Comment by ylecuyer** [comment]
There is branch which contains a base for i18n it could be used to translate attendize to French

**Comment by guidtz** [comment]
Hello,  thanks for you're response. How can we help you to localize in French in i18n branch ?

**Comment by ylecuyer** [comment]
You have to go for all pages and replace the fixed text with the trans helper and the translation in the given file

**Comment by givre** [comment]
Can you provide en example ? so we can contribute please ?

**Comment by daveearley** [comment]
Attendize is built on Laravel so the documentation [found here](https://laravel.com/docs/5.2/localization#basic-usage) is applicable to Attendize too. Cheers.

**Comment by bzg** [comment]
Hi, I'm willing to help translate Attendize in french. Should I simply create `resources/lang/fr` and translate files from there?

**Comment by ylecuyer** [comment]
Yes basically you can just copy paste `resources/lang/en` to `resources/lang/fr` and start from here.
You will have to modify `config/laravellocalization.php` to enable `fr`
Some of the views in `resources/views` too (copy `resources/views/en` to `resources/views/fr`)

I'm may be missing some (js for example) but that will be a good start

**Comment by bzg** [comment]
Okay, thanks, I will start from here.

**Comment by johanricher** [comment]
@bzg Ready to help if you want. 😉

**Comment by bzg** [comment]
@jeremyquinton I didn't know about this event, I just signed up. Let's see!

**Comment by khosrowk** [comment]
My apology for unrelated issue. I have unsubscribed from this thread and yet I still get all the messages in my Gmail. Any feedback to deal with it would be appreciated. Thank you

**Comment by bzg** [comment]
I created [this PR](https://github.com/Attendize/Attendize/pull/486) with the french translation.

**Comment by jeremyquinton** [comment]
@bzg have merged your PR so closing this off. Thanks very much. Attendize is now in 🇫🇷 👍

**Comment by bzg** [comment]
Thanks to you for guiding me on this one!
