### ISSUE TITLE
Printed Ticket Customization [feature]

### ISSUE THREAD

**Issue by tahongawaka** [Attendize/Attendize#163]
I would like to be able to upload an image that would be placed on the PDF ticket sheet below the ticket. Ideally, the image should be defined in the organizer's account as a default ticket page image. Each event would choose to use the default organizer's image, upload a specific image, or leave the space blank.

This image could be used for information, maps, coupons, a sponsor's advertisements, or anything else.

**Comment by daveearley** [comment]
While I'm not completely opposed to the idea, I feel this would be quite a niche requirement. As it stands now it's easy to customize the ticket page by editing the [view](https://github.com/Attendize/Attendize/blob/master/resources/views/Public/ViewEvent/Partials/PDFTicket.blade.php).

**Comment by tahongawaka** [comment]
Thanks for that link. I'm not too familiar with this framework, so I didn't
know what's to start looking. For my purposes, changing that view twice a
year wouldn't be too much trouble.
