### ISSUE TITLE
Web installer error

### ISSUE THREAD

**Issue by mandla07** [Attendize/Attendize#165]
When i use the web istall i get errr in log file:[2016-07-15 15:40:26] production.ERROR: exception 'RuntimeException' with message 'Changing columns for table "messages" requires Doctrine DBAL; install "doctrine/dbal".' in /xxx/xxxx/public_html/tickets/vendor/laravel/framework/src/Illuminate/Database/Schema/Grammars/Grammar.php:284
Stack trace:

**Comment by daveearley** [comment]
Looks like you're missing a dependency. Try running:

composer require doctrine/dbal

**Comment by mandla07** [comment]
Thank you how do i do this?
