### ISSUE TITLE
[Payment] Allow custom payment gateway text instruction 

### ISSUE THREAD

**Issue by givre** [Attendize/Attendize#166]
Hi, 
It would be nice to have a "custom" payment gateway where the organiser can setup a description page about how to make the payment with an auto generated code displayed as a reference 

Let's say you wanna allow payment by check .  When somebody select payment by check, the information are displayed with the auto generated value for payment tracking : Please make your payment of xx$  to  "information value company"  and put the tracking number "xxxxx" on the back. 

Also , in my personal case, I would like to tell my friends to send the money to a specific email address with a tracking number so I know who payed 
I wanted to use this platforme as a "friend event management/booking" but as it require to use a payment platform, look like I can't 
Or maybe I can at least allow the checkout without payment gateway and display a simple page with the payment instruction ?

Thanks for all the work you have done so far. Nice laravel app.

**Comment by daveearley** [comment]
Hi @givre, an offline payment option was added a few days ago. It allows you to give instructions to your attendees on how to pay offline. You can ask them to reference their order number in the payment and then mark them as paid in the attendee management area.

<img width="431" alt="capture" src="https://cloud.githubusercontent.com/assets/166798/16949593/9584ba10-4db3-11e6-9f73-e32f0dbe91f6.PNG">

Cheers!

**Comment by givre** [comment]
Hi ! That's a really good thing ! 
I wish this can happen more, think about a new feature, sleep, wake-up and it's there ;)
Keep the good work 
Cheers !

**Comment by givre** [comment]
Is there any "easy-way" to update an existing installation to get that new feature ?
I'm not too familiar with laravel,  maybe there is specific commands to update it ?
Thanks

**Comment by daveearley** [comment]
You should be able to just copy all the files GitHub and then run:

```
composer dump-autoload --optimize
php artisan optimize --force
php artisan migrate
```
Make sure to backup your existing installation just in case though.

**Comment by givre** [comment]
Thanks !
