### ISSUE TITLE
Event title : missing date of the end of the event

### ISSUE THREAD

**Issue by givre** [Attendize/Attendize#167]
On the event page , a the top there is the information : 

Event Title 
EVENT START DATE  EVENT START TIME - EVENT END TIME @ location of the event 

As you can see, the EVENT END DATE is not mentioned, only the time is shown

**Comment by daveearley** [comment]
This should be fixed now. The end date will now be shown if the event is longer than 1 day.

**Comment by givre** [comment]
Thanks for the quick fix. 
I'm not able to see the change on the event. 
I can see the new php code in the modified file, but nothing online. 

I did clear the cache view and the cache . 
> php artisan view:clear
> php artisan cache:clear

I manually deleted : 
storage/framework/views/*.php 

Am I missing something ?

**Comment by daveearley** [comment]
It should just work. I've updated it again so now the end date is shown if the event is over 12 hours long.

**Comment by givre** [comment]
Working good now. Thanks!
