### ISSUE TITLE
Editor :  Line break without space between lines

### ISSUE THREAD

**Issue by givre** [Attendize/Attendize#168]
I'm using chrome (windows) and chromium (Ubuntu)
Using the editor, I'm not able to add a break line without a space between 
Sometimes it can work with SHIFT+ENTER  but most of the time, this does not work. 

Is there a way to force a break line (<br>)  with this editor?

**Comment by daveearley** [comment]
Adding two spaces at the end of a line should do the trick. You can read more about line breaks in Markdown [here](https://daringfireball.net/projects/markdown/syntax#block).

**Comment by givre** [comment]
It's working as you said. Thanks
Looks like they support it well since version 1.10.1
