### ISSUE TITLE
Guest cannot checkout on ticket sale

### ISSUE THREAD

**Issue by givre** [Attendize/Attendize#170]
Hi, 
I am able to do the checkout for a ticket in sale only when I am logged in
If I am not logged in, I have this error message : 

> Whoops!, it looks like something went wrong on our servers. Please try again, or contact support if the problem persists.

I can't see anything in storage/logs 
Even with APP_DEBUG=true

**Comment by givre** [comment]
Is this related to the new feature "Pay using offline method" ?
Because I had this error message before even logged in when I did not have any payment gateway configured .

**Comment by givre** [comment]
If the ticket is free, it's working.

**Comment by daveearley** [comment]
I can't seem to replicate this on my end.  If you open the network tab of your browser dev tools when trying to make the payment is there any error in the server response?

**Comment by givre** [comment]
Request URL:http://*****/e/1/checkout/create
Request Method:POST
Status Code:500 Internal Server Error
Remote Address:10.16.25.72:8080

**Comment by daveearley** [comment]
It looks like you haven't fully updated your install. Try running `php artisan migrate`.

**Comment by givre** [comment]
**************************************
*     Application In Production!     *
**************************************

 Do you really wish to run this command? (yes/no) [no]:
 > yes

Nothing to migrate.

**Comment by givre** [comment]
I did a laravel refresh , and I get another error now : 

`in EventCheckoutController.php line 486
at HandleExceptions->handleError('8', 'Trying to get property of non-object', `

And maybe something relevant about it : 

` 'event' => object(Event), 'attendee_increment' => '1', 'ticket_questions' => array())) `

**Comment by daveearley** [comment]
I think I can see whats's causing this, I'll push a fix shortly.

**Comment by daveearley** [comment]
Does the latest push fix the issue?

**Comment by givre** [comment]
This is what I'm doing do update everything as you told me :+1: 

```
git pull 
composer dump-autoload --optimize
php artisan optimize --force
php artisan migrate
```

Now I'm back at the same error : 

```
QueryException in Connection.php line 713:
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'order_status_id' cannot be null 
```

Everything is up-to-date and database migration too. 

How can I help to debug this better ?

**Comment by daveearley** [comment]
From that error it appears this line is causing the problem:

` $order->order_status_id = isset($request_data['pay_offline']) ? config('attendize.order_awaiting_payment') : config('attendize.order_complete');`

Which means `config('attendize.order_awaiting_payment')` is not set for some reason. Can you see the these settings in the **config/attendize.php** file:

```
    /* Order statuses */
    'order_complete'                => 1,
    'order_refunded'                => 2,
    'order_partially_refunded'      => 3,
    'order_cancelled'               => 4,
    'order_awaiting_payment'        => 5,
```

If those lines are there try running `php artisan config:clear  `

Cheers

**Comment by givre** [comment]
This one is missing : 
` 'order_awaiting_payment'        => 5,`
I don't understand why it did not came last time I update the git files


```
git fetch --all
Fetching origin
git reset --hard origin/master
HEAD is now at 2de8496 Fix bug where offline payment would fail if no payment gateway was configured (issue #170)
```
Now I have the last file update and it's working ! :) 

Thanks for you support
