### ISSUE TITLE
Checkout Issues 

### ISSUE THREAD

**Issue by steveayo27** [Attendize/Attendize#174]
I just installed this apps and everything seems to be working well, but the only challenge that I have is the Payment aspect. When a customer try to buy tickets it will bring out the checkout ( Im using Stripe) when entering the cc info, and you click submit. It will bring out this error "Whoops!, it looks like something went wrong on our servers. Please try again, or contact support if the problem persists" But the funniest part of it, is that , it will charge the money on my credit card,  but no ticket will be issued and no email confirmation , The total number of tickets will still remain the same 

Please i need a solution to this

**Comment by jeremymcminn** [comment]
I would recommend looking at your logs, this'll tell you why - most likely you don't have an email server setup correctly so it fails when trying to send the emails related to a ticket purchase.

This is actually a workflow issue that possibly needs attention anyway.

**Comment by aethatsme** [comment]
Same is happening to me after the upgrade.
