### ISSUE TITLE
Unable to buy tickets

### ISSUE THREAD

**Issue by ojas121** [Attendize/Attendize#176]
When I try to buy free tickets, I get an error saying "Whoops!, it looks like something went wrong on our servers. Please try again, or contact support if the problem persists."

The logs are empty, and I can't figure out what the problem is.

Also, when I add another user, it says that an email has been sent although I do not receive one. I don't know if that has anything to do with this issue

**Comment by daveearley** [comment]
Are you using the downloaded zip version from the website or did you clone from Github?

**Comment by ojas121** [comment]
I'm using the downloaded zip version

**Comment by daveearley** [comment]
I've uploaded the a newer version on the website [here](https://attendize.com/documentation.php#download). Try the new version and let me know if the problem persists.

**Comment by ojas121** [comment]
Unfortunately, the problem persists. I don't know how to change that :disappointed:.

**Comment by daveearley** [comment]
Can your check if you're email settings are definitely correct in the .env file. Also make sure the driver files in **vendor\nitmedia\wkhtml2pdf\src\Nitmedia\Wkhtml2pdf\lib** are executable.
