### ISSUE TITLE
Currency [Decimal Place]

### ISSUE THREAD

**Issue by asilvapino** [Attendize/Attendize#177]
Hey, in my country (Chile) we don´t have decimal place. Its just i.e. $10.000 CLP (dot for thousands), how can i hide or erase the decimal value in order_form/ticket view.
Its a little confusing showing decimal for us.
I already tried to add a new Currency on database table, and modify "decimal_place" of U.S. Dollar on the currencies table, but not working.
Best regards!

**Comment by daveearley** [comment]
Hi there, you can edit the money helper function found here:  https://github.com/Attendize/Attendize/blob/master/app/Helpers/helpers.php#L13

Cheers

**Comment by asilvapino** [comment]
Cool, works like a charm.
Thanks for your fast response.

**Comment by daveearley** [comment]
I just pushed a commit which added better support for additional currencies so it's easy to add currencies in the future.

**Comment by asilvapino** [comment]
i make the git pull, but no config available to currency.. 
i missing something?

**Comment by daveearley** [comment]
sorry forgot to mention you'll have to run `php artisan db:seed --class=CurrencySeeder` to bring the new currencies.

**Comment by asilvapino** [comment]
>  ReflectionException: Class CurrencySeeder does not exist in /var/www/attendize/bootstrap/cache/compiled.php:1355

sorry but im new to Laravel and this artisian CLI so idk if i gotta do something before seeding the db.
and... CurrencySeeder its the only change i gotta seed or compile?

thanks in advance

**Comment by daveearley** [comment]
No problem, try running:
`php artisan clear-compiled`
then 
`php artisan optimize --force`
then
`php artisan db:seed --class=CurrencySeeder`

**Comment by asilvapino** [comment]
Working great.
btw the CurrencySeeder should be:
```
            [
                'id' => 28,
                'title' => 'Chilean peso',
                'symbol_left' => '$',
                'symbol_right' => '',
                'code' => 'CLP',
                **'decimal_place' => 0,**
                'value' => 0.00,
                **'decimal_point' => ',',**
                **'thousand_point' => '.',**
                'status' => 1,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
```
For Chile at least! 
Thanks again ;)
