### ISSUE TITLE
PDF Ticket half page width

### ISSUE THREAD

**Issue by asilvapino** [Attendize/Attendize#178]
Hey, how can i set the ticket width to only fill half of the page in pdf ticket?
or just costumize the size in % or px...

Thanks in advance

**Comment by daveearley** [comment]
You can edit the design of the ticket by editing this file: https://github.com/Attendize/Attendize/blob/master/public/assets/stylesheet/ticket.css

**Comment by asilvapino** [comment]
Right! thanks, im gonna try and i let you know if its all ok to close this.
Cheers!

**Comment by asilvapino** [comment]
daveearley man i hope ur fine! 
Im putting half of the size in every px and % but in the QR code image i cant get it half size... what do im doing wrong?

**Comment by asilvapino** [comment]
ok, finnaly i got it..
i have to edit this file
resources/views/Public/ViewEvent/Partials/PDFTicket.blade.php
in:
`<div class="barcode">
    {!! DNS2D::getBarcodeSVG($attendee->private_reference_number, "QRCODE", 3, 3) !!}
</div>`
the original was "QRCODE", 6, 6 so i just put 3, 3 now its ok!
