### ISSUE TITLE
Add the ability to customize the design / bar-code type of tickets

### ISSUE THREAD

**Issue by kaptk2** [Attendize/Attendize#18]
By using a 1 dimensional bar code instead of a QR code on the tickets more / cheaper scanners could be used rather than requiring the use of a smart scanner (phone) to take a ticket/

**Comment by Attendize** [comment]
Very good  point. I'll add the option to choose 1D or QR in the event options for v1.0.0

**Comment by mandla07** [comment]
I get Error after i uploaded the files you changed. [2016-07-07 21:23:25] production.ERROR: exception 'ErrorException' with message 'Undefined variable: image_path' in /xxx/xxxx/xxxx/xxx/storage/framework/views/ecf32de08add39071139ae10f58a2e36:19

**Comment by daveearley** [comment]
On what page are you receiving the error?

**Comment by mandla07** [comment]
When i go to event customize page i get something was or went wrong error. I got this error in the log.

**Comment by mandla07** [comment]
It happens when upload the TicketDesignPreview.blade.php
