### ISSUE TITLE
PaaS?

### ISSUE THREAD

**Issue by ojas121** [Attendize/Attendize#180]
Does attendize work with any PaaS?
Can it work with ephemeral storage?

**Comment by daveearley** [comment]
Yes the system should work with PaaS and ephemeral storage.

**Comment by ojas121** [comment]
Okay, thanks. Do you recommend any particular hosting platform?

**Comment by daveearley** [comment]
There are a number of services suited to Laravel applications listed [here](http://www.laravelbestpractices.com/#php_paas_providers).

**Comment by ojas121** [comment]
Great, thanks :)
