### ISSUE TITLE
Add user importable calendar to ticket

### ISSUE THREAD

**Issue by KlausGPaul** [Attendize/Attendize#182]
This would be a really cool new feature .... If there was a way for customers to add the event ticket to their calendar(s), probably needs support for various formats (simple attachments may not work).

**Comment by daveearley** [comment]
This has been mentioned before and it's definitely a good idea so I'll tag it as a future feature. 

It wouldn't be that difficult to allow attendees download a .ics file, or even attach it to the email along with their tickets. As far as I'm aware .ics files are well supported too.

**Comment by jmowatt** [comment]
Hi,

https://github.com/Attendize/Attendize/pull/199

Will allow you to download an ICS file, instead of attaching it users are able to click a link in the email to receive an ICS file.

**Comment by KlausGPaul** [comment]
Nicely done, works well, thanks for that!

**Comment by KlausGPaul** [comment]
Residual issue reported via https://github.com/Attendize/Attendize/issues/292.
