### ISSUE TITLE
Assign roles to users

### ISSUE THREAD

**Issue by aethatsme** [Attendize/Attendize#183]
I noticed that the site owner can add as many organizers and organizers can add also. Might be a good idea to assign roles to organizers. Maybe create 2 or 3 roles; ex: Organizer, Staff, Customer

**Comment by daveearley** [comment]
I'll add a feature tag to this as we will be adding in better user/permission management over the next few months.

**Comment by ashleyyounguk** [comment]
I would like the ability to setup an organiser with an account that will only allow them to access their own events. I assume this would be covered under this feature?

**Comment by etiennemarais** [comment]
Closing this due to age
