### ISSUE TITLE
Support for additional widgets 

### ISSUE THREAD

**Issue by ashleyyounguk** [Attendize/Attendize#187]
This application is awesome, you've done a remarkable job.

A good feature to have is the ability to display a list of all events on a website, from all organisers.

**Comment by daveearley** [comment]
Thanks @ashleyyounguk, we'll be adding additional widgets and customization options in later versions.

**Comment by Bellusterra** [comment]
Just checking to see if this has been implemented, I can't seem to find out how to do this?
