### ISSUE TITLE
Unable to Send Email -> Unable to Checkout

### ISSUE THREAD

**Issue by schmidna** [Attendize/Attendize#189]
Having tried for hours now to debug checkout I'm pretty sure the issue is in email/swift mailer but cannot figure out how to fix it.. I will admit my own lack of ability likely is impacting the situation.

Although Attendize itself produces no logs (probably because I've missed something), I'm able to pull up Apache's logs at the time I try to check out and it continually lists this exception (apologies for the length):
`production.ERROR: exception 'Swift_TransportException' with message 'Connection could not be established with host email-smtp.us-east-1.amazonaws.com [Connection timed out #110]' in /var/www/html/attendize/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php:269\nStack trace:\n#0 /var/www/html/attendize/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php(62): Swift_Transport_StreamBuffer->_establishSocketConnection()\n#1 /var/www/html/attendize/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(113): Swift_Transport_StreamBuffer->initialize(Array)\n#2 /var/www/html/attendize/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(79): Swift_Transport_AbstractSmtpTransport->start()\n#3 /var/www/html/attendize/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(385): Swift_Mailer->send(Object(Swift_Message), Array)\n#4 /var/www/html/attendize/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(171): Illuminate\\Mail\\Mailer->sendSwiftMessage(Object(Swift_Message))\n#5 /var/www/html/attendize/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221): Illuminate\\Mail\\Mailer->send('Mailers.TicketM...', Array, Object(Closure))\n#6 /var/www/html/attendize/app/Mailers/OrderMailer.php(40): Illuminate\\Support\\Facades\\Facade::__callStatic('send', Array)\n#7 /var/www/html/attendize/app/Mailers/OrderMailer.php(40): Illuminate\\Support\\Facades\\Mail::send('Mailers.TicketM...', Array, Object(Closure))\n#8 /var/www/html/attendize/app/Jobs/SendOrderTickets.php(37): App\\Mailers\\OrderMailer->sendOrderTickets(Object(App\\Models\\Order))\n#9 [internal function]: App\\Jobs\\SendOrderTickets->handle(Object(App\\Mailers\\OrderMailer))\n#10 /var/www/html/attendize/vendor/laravel/framework/src/Illuminate/Container/Container.php(507): call_user_func_array(Array, Array)\n#11 /var/www/html/attendize/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(81): Illuminate\\Container\\Container->call(Array)\n#12 [internal function]: Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}(Object(App\\Jobs\\SendOrderTickets))\n#13 /var/www/html/attendize/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(150): call_user_func(Object(Closure), Object(App\\Jobs\\SendOrderTickets))\n#14 [internal function]: Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(App\\Jobs\\SendOrderTickets))\n#15 /var/www/html/attendize/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(App\\Jobs\\SendOrderTickets))\n#16 /var/www/html/attendize/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(82): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))\n#17 /var/www/html/attendize/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(41): Illuminate\\Bus\\Dispatcher->dispatchNow(Object(App\\Jobs\\SendOrderTickets))\n#18 /var/www/html/attendize/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(130): Illuminate\\Queue\\CallQueuedHandler->call(Object(Illuminate\\Queue\\Jobs\\SyncJob), Array)\n#19 /var/www/html/attendize/vendor/laravel/framework/src/Illuminate/Queue/Jobs/SyncJob.php(44): Illuminate\\Queue\\Jobs\\Job->resolveAndFire(Array)\n#20 /var/www/html/attendize/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(30): Illuminate\\Queue\\Jobs\\SyncJob->fire()\n#21 /var/www/html/attendize/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(142): Illuminate\\Queue\\SyncQueue->push(Object(App\\Jobs\\SendOrderTickets))\n#22 /var/www/html/attendize/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(117): Illuminate\\Bus\\Dispatcher->pushCommandToQueue(Object(Illuminate\\Queue\\SyncQueue), Object(App\\Jobs\\SendOrderTickets))\n#23 /var/www/html/attendize/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(66): Illuminate\\Bus\\Dispatcher->dispatchToQueue(Object(App\\Jobs\\SendOrderTickets))\n#24 /var/www/html/attendize/vendor/laravel/framework/src/Illuminate/Foundation/Bus/DispatchesJobs.php(17): Illuminate\\Bus\\Dispatcher->dispatch(Object(App\\Jobs\\SendOrderTickets))\n#25 /var/www/html/attendize/app/Listeners/OrderCompletedListener.php(42): App\\Listeners\\OrderCompletedListener->dispatch(Object(App\\Jobs\\SendOrderTickets))\n#26 [internal function]: App\\Listeners\\OrderCompletedListener->handle(Object(App\\Events\\OrderCompletedEvent))\n#27 /var/www/html/attendize/vendor/laravel/framework/src/Illuminate/Events/CallQueuedHandler.php(43): call_user_func_array(Array, Array)\n#28 /var/www/html/attendize/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(130): Illuminate\\Events\\CallQueuedHandler->call(Object(Illuminate\\Queue\\Jobs\\SyncJob), Array)\n#29 /var/www/html/attendize/vendor/laravel/framework/src/Illuminate/Queue/Jobs/SyncJob.php(44): Illuminate\\Queue\\Jobs\\Job->resolveAndFire(Array)\n#30 /var/www/html/attendize/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(30): Illuminate\\Queue\\Jobs\\SyncJob->fire()\n#31 [internal function]: Illuminate\\Queue\\SyncQueue->push('Illuminate\\Even...', Array)\n#32 /var/www/html/attendize/vendor/laravel/framework/src/Illuminate/Queue/QueueManager.php(267): call_user_func_array(Array, Array)\n#33 /var/www/html/attendize/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(417): Illuminate\\Queue\\QueueManager->__call('push', Array)\n#34 /var/www/html/attendize/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(417): Illuminate\\Queue\\QueueManager->push('Illuminate\\Even...', Array)\n#35 [internal function]: Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}(Object(App\\Events\\OrderCompletedEvent))\n#36 /var/www/html/attendize/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(348): call_user_func_array(Object(Closure), Array)\n#37 [internal function]: Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}(Object(App\\Events\\OrderCompletedEvent))\n#38 /var/www/html/attendize/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(221): call_user_func_array(Object(Closure), Array)\n#39 /var/www/html/attendize/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(419): Illuminate\\Events\\Dispatcher->fire(Object(App\\Events\\OrderCompletedEvent), Array, false)\n#40 /var/www/html/attendize/app/Http/Controllers/EventCheckoutController.php(630): event(Object(App\\Events\\OrderCompletedEvent))\n#41 /var/www/html/attendize/app/Http/Controllers/EventCheckoutController.php(416): App\\Http\\Controllers\\EventCheckoutController->completeOrder('1')\n#42 [internal function]: App\\Http\\Controllers\\EventCheckoutController->postCreateOrder(Object(Illuminate\\Http\\Request), '1')\n#43 /var/www/html/attendize/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(80): call_user_func_array(Array, Array)\n#44 /var/www/html/attendize/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(146): Illuminate\\Routing\\Controller->callAction('postCreateOrder', Array)\n#45 /var/www/html/attendize/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(94): Illuminate\\Routing\\ControllerDispatcher->call(Object(App\\Http\\Controllers\\EventCheckoutController), Object(Illuminate\\Routing\\Route), 'postCreateOrder')\n#46 [internal function]: Illuminate\\Routing\\ControllerDispatcher->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))\n#47 /var/www/html/attendize/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\\Http\\Request))\n#48 [internal function]: Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))\n#49 /var/www/html/attendize/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\\Http\\Request))\n#50 /var/www/html/attendize/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(96): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))\n#51 /var/www/html/attendize/vendor/laravel`

For awhile I've assumed the actual error was caused simply by invalid credentials, or the firewall blocking access on port 587. This I gather from `with message 'Connection could not be established with host email-smtp.us-east-1.amazonaws.com [Connection timed out #110]'`. 

However AWS SES was not my first service tried, as initially I had it setup with Sendgrid, which produced the identical error, and I've confirmed port 587 is open. So I'm fairly sure now that my actual credentials aren't the problem.

**Comment by daveearley** [comment]
Hi @schmidna, if AWS and SendGrid both block connections I would guess it's an issue with the port. Other than double checking the port is open I'm not sure what the problem could be.

**Comment by schmidna** [comment]
@daveearley thanks for your reply. SendGrid now works after changing ports. Doing so resolved all issues.
