### ISSUE TITLE
Ticket-checkmark for visible or not

### ISSUE THREAD

**Issue by Elektrostephan** [Attendize/Attendize#195]
i would like to have e.g. a checkmark at the tickets to make it not visible at the Ticketshop e.g. for free VIP- or Press-tickets. 
it would be good too, if i can send an invitiation to buy a ticket for a special price. 

by the way
had a meeting, we had some problems with the mobile Phones while scanning and had to export html-attendees-list to check it, but all in all it was a great help

**Comment by aethatsme** [comment]
I'm having the same problem with mobile check-in also. It's not triggering the camera on both android and apple. Also tested on different mobile browsers as well. Same issue.

**Comment by ashleyyounguk** [comment]
Yep same here. Even tried the demo version too. I'm on a iPhone 6 using chrome. It's not triggering the camera.

**Comment by daveearley** [comment]
I'll look into this now. I do know some browsers don't allow access to the camera if the page is not HTTPS, so that may be causing an issue.

**Comment by aethatsme** [comment]
I have it running under HTTPS. Same issue. Only the blue screen will pop up with the outlined square but camera function not on.

**Comment by aethatsme** [comment]
Doesn't work on the demo either. Here's a screen shot on an iphone 6 safari.
![img_4099](https://cloud.githubusercontent.com/assets/7725507/18712437/10480fd4-7fd4-11e6-9e74-2f14241e1fde.PNG)

**Comment by aethatsme** [comment]
Same issue on the demo. Here's a screen shot on my iphone 6 safari browser.

![img_4099](https://cloud.githubusercontent.com/assets/7725507/18712494/4ac05e64-7fd4-11e6-8cc2-95fb650ccc30.PNG)

**Comment by aethatsme** [comment]
Maybe using phonegap.com could resolve the issue.

**Comment by cosmorogers** [comment]
getUserMedia isn't supported on iOS devices, and only newer androids;
http://caniuse.com/#feat=stream

**Comment by daveearley** [comment]
There was on string comparison issue on some versions of PHP which was causing all the attendees to appear checked in. The last commit should fix it .

The missing checkmark was fixed too.

The camera not appearing is likely an issue with Chrome not allowing the camera to be opened when using HTTP.
