### ISSUE TITLE
Paypal SEPA Problem

### ISSUE THREAD

**Issue by m10g4** [Attendize/Attendize#204]
Hi there!

We noticed problems with the direct debit authorization through PayPal: Someone used it an the payment never succeeded – but the payment-state directly changes to "completed" instead of "awaiting payment".

Thanks for finding some fixes!

**Comment by daveearley** [comment]
Cheers @mgens , I'll look into this.

**Comment by johannac** [comment]
I'm going to close this due to the length of time it's been open, this may not be an issue anymore. If it still is, please reopen a new ticket using the bug submission template.
