### ISSUE TITLE
Google Analytics Code

### ISSUE THREAD

**Issue by bretto36** [Attendize/Attendize#205]
I see we just added the Google Analytics code into the organiser page. It seems to be placed at the very bottom after everything. But GA recommends inside the head tags

"Paste your tracking code snippet into its own include file, then include it in your page header, so that the snippet appears before the closing `</head>` tag on every web page on your site you wish to track."

https://support.google.com/analytics/answer/1008080?hl=en

**Comment by daveearley** [comment]
Cheers @bretto36! , I'll make a change now
