### ISSUE TITLE
Payment details sent to server

### ISSUE THREAD

**Issue by cosmorogers** [Attendize/Attendize#207]
When using Stripe at least, you are not suppose to send payment details to your server, otherwise you have the fun of PCI compliance. 

> Do not give names to the payment details form elements! This prevents that data from touching your server, which means you no longer need to worry about redacting logs, encrypting cardholder details, or other burdens of PCI compliance.

See https://stripe.com/docs/custom-form

Offending lines;
https://github.com/Attendize/Attendize/blob/master/resources/views/Public/ViewEvent/Partials/EventCreateOrderSection.blade.php#L169
https://github.com/Attendize/Attendize/blob/master/resources/views/Public/ViewEvent/Partials/EventCreateOrderSection.blade.php#L196

Arguably the expiry date doesn't need a name either.

**Comment by daveearley** [comment]
Hi @cosmorogers, 

Thanks for the heads up!  We do our best [here](https://github.com/Attendize/Attendize/blob/master/app/Http/Controllers/EventCheckoutController.php#L303) to strip out any CC data. To the best of my knowledge it's still PCI compliant if you're not saving data in logs etc. 

The CC number is there as we need to support gateways which need the CC info passed in. However, I will look at removing it for installs only using PayPal and Stripe.

Cheers
