### ISSUE TITLE
use artisan commands

### ISSUE THREAD

**Issue by macwinnie** [Attendize/Attendize#209]
Executing `php artisan down`  within the command line tools causes an not so pretty looking error "Whoops, looks like something went wrong." instead of something like "Sorry, the site is in maintenance – please try again later".

What is the correct way to push the site to maintenance mode? If there is none, please make the app usable with the default laravel way – and possibly with customizable error messages.

**Comment by daveearley** [comment]
Not sure what would cause that as Laravel's maintenance was never altered. I'll have a look.

**Comment by ylecuyer** [comment]
This seems to be the right behavior. The solution maybe to add a custom 503 error page with a custom message for maintenance.

https://github.com/laravel/framework/blob/5.1/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php
