### ISSUE TITLE
Sorting tickets

### ISSUE THREAD

**Issue by macwinnie** [Attendize/Attendize#214]
Sorting the tickets within the backend doesn't do anything in the frontend ... please check over.

**Comment by ylecuyer** [comment]
That's normal, there is no options for ordering tickets on the frontend.

**Comment by macwinnie** [comment]
HI @ylecuyer,
you're right, there is no option within the tickets overview. But within the data layer, the `tickets`-table provides an attribute `sort_order`, that (in my understanding) should do this. But changing these values doesn't do anything =(
Cheers,
Martin
