### ISSUE TITLE
How do i prevent unpaid tickets to check in?

### ISSUE THREAD

**Issue by asilvapino** [Attendize/Attendize#216]
If the attende doesnt pay, how do i prevent him to check in... 😢 
my event is only Offline Payments
but anyone can figure out how to put an informative alert when i check in a non paid attende? i know maybe its a feature to add in the future, but if anyone can just give me a guideline to add this alert in code, i'll be very thankful.
![image](https://cloud.githubusercontent.com/assets/17709940/19214430/52555af6-8d5a-11e6-900b-bfbeb61b8d18.png)

**Comment by daveearley** [comment]
Hi @asilvapino 

I'm not sure I follow you when you say "anyone can figure out how to put an informative alert when i check in a non paid attende". 

Do you want an alert to popup warning you that the attendee hasn't paid?

**Comment by asilvapino** [comment]
yeah that's exactly what i need

**Comment by asilvapino** [comment]
i was think to modify attendize/public/assets/javascript/check_in.js to add something like this:
![info](https://cloud.githubusercontent.com/assets/17709940/19254204/b89c96a2-8f27-11e6-9726-7b73e1b9060b.png)
but i really no that skilled in laravel.
can u give me a hand @daveearley ?

**Comment by asilvapino** [comment]
Never mind i got it!
we need to change:
app/Http/Controllers/EventCheckInController.php
line 137 add another join 
->join('orders', 'orders.id', '=', 'attendees.order_id')
and new select:
'orders.is_payment_received as payment',

then line 187 to add the text and show $attendee->payment

to show correctly i add a if statement:
```
 if ($attendee->payment==0) {
            $paidOrder='NO';
        }else{
            $paidOrder='YES';
        }
```
then just print $paidOrder var

Cheers!

**Comment by jharris70** [comment]
Also, the unpaid ticket should be generated with huge letters reading "UNPAID TICKET" or some wording. When the payment is received, the system can generate a new email with new tickets without the UNPAID mark. They should still be checked at the door, in case the patron didn't print the new tickets.

**Comment by asilvapino** [comment]
Possible a good feature, but mi request was solved so im closing this
Thanks guys!
