### ISSUE TITLE
ics calendar entries are not updated time-wise after the event time has been edited

### ISSUE THREAD

**Issue by KlausGPaul** [Attendize/Attendize#217]
We created an event that was originally scheduled for 17-18, and was moved to 15-16. Unfortunately, the ics calendar link was not updated and the attendees become an outdated calendar entry which points to 17-18 still.

Possible fix: re-generate the .ics upon updating the event.

**Comment by ylecuyer** [comment]
Couldn't replicate. The ics is generated every time someone try to download it

**Comment by KlausGPaul** [comment]
Will double check, this could also be a time zone issue?

**Comment by KlausGPaul** [comment]
New issue raised #292 that describes the current problem and supercedes 217
