### ISSUE TITLE
Duplicate data for accounts, users and organisers

### ISSUE THREAD

**Issue by markwalet** [Attendize/Attendize#22]
I'm exploring the workflow of Attendize and I have found some minor issues in the data structure of the application.
For example: The email adress is stored in the accounts, users AND organisers table. I this way I am able to create an account which contains the same user credentials for multiple accounts. 
This data structure has to be cleaned up. Especially for the authenticated user data.

Maybe you could store all data in one table with an extra column `role`. Or maybe you could store all the extra data per row in a seperate table. But storing two mail adresses in two different tables for one user is never a good practice.

**Comment by Attendize** [comment]
Hi Mark,

I laid the structure to accommodate for the possibility of a hosted version in future. So each account would have multiple users, and a user wouldn't necessarily have the same email as the account holder. The same goes for the organizers; my thinking based on looking at existing events and seeing organizers had organizer@gmail.com emails etc. so there wouldn't be much duplication.

Feel free to optimize away though!

Cheers
