### ISSUE TITLE
missing API_PREFIX=* within the .env.example / docs

### ISSUE THREAD

**Issue by macwinnie** [Attendize/Attendize#224]
I couldn't find the information, which `API_PREFIX` I should put within my `.env`-file – so after updating the application, it crashed by

```
production.ERROR: RuntimeException: Unable to boot ApiServiceProvider, configure an API domain or prefix.
```

Google helped me out to figure out the Attribute within the `.env`-file, but the correct value for Attendize, it could not tell ;)
My temp(?) value now is `api`.

**Comment by daveearley** [comment]
This was related to an incomplete feature which has been removed. It should be fixed now.
