### ISSUE TITLE
correct redirection from embedded iframe

### ISSUE THREAD

**Issue by macwinnie** [Attendize/Attendize#227]
Hi =)

The Check-Out-Sessions are expiring, so if an attendee remains for a longer time on the checkout page, which is embedded via iframe to another site, he is notified by a popup and the page will be reloaded.
But the newly loaded page is no more the embed-page but the full event page, what causes duplicate content and messy look and feel ...

Could you please check and fix that?
Thanks!

**Comment by daveearley** [comment]
Fixed in e1956b2da927dbcbd4e1cfb4a6d05b03ea3f396f
