### ISSUE TITLE
improve usability – possibility to renew session instead to expire

### ISSUE THREAD

**Issue by macwinnie** [Attendize/Attendize#228]
Hi,
I have another ticket on the expiring checkout session – but rather an enhancement than an issue.

The Check-Out-Sessions are expiring, so if an attendee remains for a longer time on the checkout page, which is embedded via iframe to another site, he is notified by a popup and the page will be reloaded.

Is there any possibility to renew the session and prevent all entered data to be vanished after reloading the checkout-page? Some of our attendees asked us for such an feature, because we asked them for detailed answers within the surveys and some of them needed more time ...

Thank you,
cheers!
Martin

**Comment by daveearley** [comment]
If you require a lot of information from attendees you can increase the allowed checkout time in the config file [found here](https://github.com/Attendize/Attendize/blob/master/config/attendize.php#L33).
