### ISSUE TITLE
Support for multiple languages

### ISSUE THREAD

**Issue by markwalet** [Attendize/Attendize#23]
Laravel provides an excellent way to add translations to your web application.
At this point. Almost none of these features are used.
If all the sentences and words are stored in the translation files, I probably would add all dutch translations as well.

**Comment by JapSeyz** [comment]
This is mostly just grind work, you could easily do it via a pull-request yourself.

**Comment by markwalet** [comment]
Absolutely! Was planning to do this maybe this week or the next.
Could you make sure that you store new strings by default in an translation file? That will prevent inconsistencies.
Do you prefer a syntax or something like that for storing the translations?

**Comment by JapSeyz** [comment]
@markwalet Awesome. If I can find any sparetime from studying for exams and working, I'll check in and add some danish lines as well.

**Comment by markwalet** [comment]
Nice work!

**Comment by Attendize** [comment]
This is definitely a big necessity. I'll start chipping away at this too when I've time over the next while.

**Comment by JapSeyz** [comment]
@Attendize You should setup some guidelines for it. That way people can help you out, and keep it uniform.

**Comment by phillipnunes** [comment]
When you guys release this upgrade, i'll translate to Portuguese BR.

[]'s

**Comment by ylecuyer** [comment]
I'm working on this, it would be nice to have some help https://github.com/ylecuyer/Attendize/tree/i18n

**Comment by daveearley** [comment]
I've a good few hours available this Monday, so I can get a fair amount of work on i18n done then.

**Comment by pelim** [comment]
I have positive experience with gettext translation in combination with this translation scanner https://github.com/dzuelke/grammatista and found this laravel package with another scanner included https://github.com/xinax/laravel-gettext

**Comment by daveearley** [comment]
Those options definitely look very useful. I like the idea of using a scanner to find translatable text.

**Comment by Sebi55** [comment]
The latest changes in Laravel 5.4 would be maybe interesting for implementing a multilanguage feature:
https://laravel-news.com/2016/11/json-based-translations/

**Comment by jeremyquinton** [comment]
Attendize now has multiple language support.
