### ISSUE TITLE
sell tickets for events on the day

### ISSUE THREAD

**Issue by macwinnie** [Attendize/Attendize#230]
It would be a nice feature to add the ability to buy tickets on the day for an event. Now, I didn't find any option to prevent the "This event has already started."-message on the purchase page.

**Comment by daveearley** [comment]
This would be a handy feature alright. I'll try to include it in the next version.

**Comment by jeremyquinton** [comment]
Attendize by Default now allows tickets to be bought on the day of the event and up until the event has ended. https://github.com/Attendize/Attendize/commit/b1ffb7e6fdd8390700e1801fb10f4c822c35d5b1
