### ISSUE TITLE
Trying to setup

### ISSUE THREAD

**Issue by kirkins** [Attendize/Attendize#231]
I'm following the instructions setup and I'm on the 3rd last step:

```
docker-compose run php php artisan attendize:install
```

After I do that I get the following:

![screenshot from 2016-10-28 16-04-22](https://cloud.githubusercontent.com/assets/9503662/19820659/58fba88c-9d28-11e6-9b36-49fa4836135d.png)

It just hangs, I try opening another terminal while that's running to use:

```
chmod a+w -R storage
chmod a+w -R public/user_content
```

I get "No such file or directory" so I guess that's a command I should be running inside the container. Anyone know what went wrong here?

**Comment by KlausGPaul** [comment]
@kirkins  You can do these steps before (i.e. last, 2nd last, 3rd last), and/or from a second terminal window. docker-compose launches a non-daemon version of attendize in the foreground, so you actually watch the attendize console output. Klaus

**Comment by jeremyquinton** [comment]
@kirkins @KlausGPaul the new docker environment is working correctly and there is a troubleshooting guide which can be found here. https://www.attendize.com/troubleshooting.html

Closing off this issue as its over 18 months old
