### ISSUE TITLE
Hidden Attendee-Attributes 

### ISSUE THREAD

**Issue by macwinnie** [Attendize/Attendize#232]
For some festival type events, often a ticket is coming with a special sleeping location. I.e. the cheep tickets only qualify for sleeping in the gym, while there is another ticket category for the ones who may sleep in a hostel.

For automatically processing with exporter lists, it could be helpful to define some survey questions that are answered with a default value through the ticket type.
These "tickettype attributes" should not be editable with attendees, but only with tickettype.

**Comment by daveearley** [comment]
For now I'll leave this as it may over complicate the survey section.

Cheers!
