### ISSUE TITLE
Partial filled out ticket saying "sold out" 

### ISSUE THREAD

**Issue by Jarrettob** [Attendize/Attendize#236]
Although I did not complete the full checkout process on a ticket, it then showed up as saying sold out, although the order did not process and could not be found in the orders tab.

**Comment by jeremyquinton** [comment]
potentially related to #472 #473

**Comment by johannac** [comment]
I believe this was addressed in the tickets that Jeremy linked above. Please reopen a new ticket using the bug submission template if this is still and issue.
