### ISSUE TITLE
Issues with editing Event flyer images

### ISSUE THREAD

**Issue by Jarrettob** [Attendize/Attendize#237]
I have had a few glitches changing the flyer image. The last time I edited it showed up with a bunch of errors on all fields (see attached). Also, not sure if there is an upload limit but that could be the problem.

Also more of an idea, but we work with a lot of nonprofits that make banner images that are much larger for Facebook, Meetup, and other platforms. Might be helpful to look into having the ability to click and enlarge or match typical standards. I know background images are coming so this may help.

<img width="1203" alt="screen shot 2016-11-01 at 11 30 54 am" src="https://cloud.githubusercontent.com/assets/16140200/19902795/5cce5da2-a029-11e6-8832-45dce79782c9.png">

**Comment by daveearley** [comment]
Is this still happening? I can't seem to replicate it

**Comment by Jarrettob** [comment]
I haven't been able to replicate either and tried a few times with larger images.

**Comment by daveearley** [comment]
I'll close this for now and re-open if the issue reoccurs 👍
