### ISSUE TITLE
I can not install it. Can anyone help?

### ISSUE THREAD

**Issue by feliphed** [Attendize/Attendize#241]
I can not install it Attendize. Can anyone help?

**Comment by daveearley** [comment]
What have you tried? are there any errors showing? Are there any errors in your logs? Have you looked at the [troubleshooting](https://attendize.com/documentation.php#troubleshooting) tips?

**Comment by feliphed** [comment]
Good evening. Soon when I install, I put the db data, appears this message:

RuntimeException in process.php line 144: The Process class Relies on proc_open, Which is not available on your PHP installation.

then when I can fix by changing something in the code, appear other errors relacinados the RuntimeException.
My hosting is One.com, I do not have access to php.ini

**Comment by daveearley** [comment]
Are you trying to install using the CLI installer or the web browser installer?

**Comment by feliphed** [comment]
the web browser installer, I have access to ssh but did not get there.

**Comment by feliphed** [comment]
My hotel does not have the composer. Is there a problem with that?

**Comment by daveearley** [comment]
It looks like Attendize may not be compatible with your hosting provider. You could ask your host to enable proc_open, or try a VPS provider like Digital Ocean or Linode.
