### ISSUE TITLE
Buying - what about selling?

### ISSUE THREAD

**Issue by HighFlyerPL185** [Attendize/Attendize#242]
Great module you've got here! From what I gather, this is mainly for purchasing tickets, but does it support also sale of tickets? For example, a user would like to sell me a ticket and I'd buy it off them and resell. Is that possible? If not, where could I start?

**Comment by daveearley** [comment]
Thanks @HighFlyerPL185. Thanks for the suggestion. That's not possible unfortunately, and we plan to keep mostly to buying and selling setup we have now. 

It would be a big job to implement so you'd probably be better looking at a different platform.
