### ISSUE TITLE
Ticket download not available from URL

### ISSUE THREAD

**Issue by jharris70** [Attendize/Attendize#244]
Transaction email from Attendize states "Your tickets are attached to this email. You can also view your order details and download your tickets at: {$URL}/order/{$order->order_reference}."

The linked url is missing a download link or an embedded PDF of the tickets.

**Comment by daveearley** [comment]
There is actually a link contained in the sentence "Your **tickets** and a confirmation email have been sent to you.", but admittedly it isn't very clear. 

I'll change it so it's more clear now.

 Cheers!
