### ISSUE TITLE
Have problem with checkout Order Details

### ISSUE THREAD

**Issue by OverVlad** [Attendize/Attendize#248]
When i try to checkout my ticket i receive an error 'production.ERROR: exception 'ErrorException' with message 'Trying to get property of non-object' in /Attendize/app/Http/Controllers/EventCheckoutController.php:320'

$gateway = Omnipay::create($ticket_order['payment_gateway']->name)

**Comment by daveearley** [comment]
This will happen if you have paid tickets but didn't add a payment gateway. Adding a payment gateway should sort the problem out.

**Comment by OverVlad** [comment]
@daveearley thx
