### ISSUE TITLE
Issue running install script on local server

### ISSUE THREAD

**Issue by bretto36** [Attendize/Attendize#25]
Hi there, i'm looking for a project to contribute to so i can learn laravel a bit more. I've already put a pull request up with a bunch of formatting changes. I'm trying to install on my local development server and i'm getting an issue where it reaches max nesting whilst running the installer. I'm getting a bunch of tables in the database, then i get this - 
**
production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Maximum function nesting level of '100' reached, aborting!' in D:\Users\brett\workspace\Attendize\vendor\nikic\php-parser\lib\PhpParser\PrettyPrinterAbstract.php:174**
Stack trace:
#0 D:\Users\brett\workspace\Attendize\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(133): Symfony\Component\Debug\Exception\FatalErrorException->__construct()
#1 D:\Users\brett\workspace\Attendize\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(118): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError()
#2 D:\Users\brett\workspace\Attendize\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(0): Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#3 D:\Users\brett\workspace\Attendize\vendor\nikic\php-parser\lib\PhpParser\PrettyPrinter\Standard.php(447): PhpParser\PrettyPrinter\Standard->pVarOrNewExpr()
#4 D:\Users\brett\workspace\Attendize\vendor\nikic\php-parser\lib\PhpParser\PrettyPrinterAbstract.php(175): PhpParser\PrettyPrinter\Standard->pExpr_PropertyFetch()
#5 D:\Users\brett\workspace\Attendize\vendor\nikic\php-parser\lib\PhpParser\PrettyPrinter\Standard.php(781): PhpParser\PrettyPrinterAbstract->p()
#6 D:\Users\brett\workspace\Attendize\vendor\nikic\php-parser\lib\PhpParser\PrettyPrinter\Standard.php(363): PhpParser\PrettyPrinter\Standard->pVarOrNewExpr()
#7 D:\Users\brett\workspace\Attendize\vendor\nikic\php-parser\lib\PhpParser\PrettyPrinterAbstract.php(219): PhpParser\PrettyPrinter\Standard->pExpr_MethodCall()
#8 D:\Users\brett\workspace\Attendize\vendor\nikic\php-parser\lib\PhpParser\PrettyPrinterAbstract.php(183): PhpParser\PrettyPrinterAbstract->pPrec()
#9 D:\Users\brett\workspace\Attendize\vendor\nikic\php-parser\lib\PhpParser\PrettyPrinter\Standard.php(111): PhpParser\PrettyPrinterAbstract->pInfixOp()
#10 D:\Users\brett\workspace\Attendize\vendor\nikic\php-parser\lib\PhpParser\PrettyPrinterAbstract.php(175): PhpParser\PrettyPrinter\Standard->pExpr_Assign()
#11 D:\Users\brett\workspace\Attendize\vendor\nikic\php-parser\lib\PhpParser\PrettyPrinter\Standard.php(29): PhpParser\PrettyPrinterAbstract->p()
#12 D:\Users\brett\workspace\Attendize\vendor\nikic\php-parser\lib\PhpParser\PrettyPrinterAbstract.php(175): PhpParser\PrettyPrinter\Standard->pArg()
#13 D:\Users\brett\workspace\Attendize\vendor\nikic\php-parser\lib\PhpParser\PrettyPrinterAbstract.php(233): PhpParser\PrettyPrinterAbstract->p()
#14 D:\Users\brett\workspace\Attendize\vendor\nikic\php-parser\lib\PhpParser\PrettyPrinterAbstract.php(247): PhpParser\PrettyPrinterAbstract->pImplode()
#15 D:\Users\brett\workspace\Attendize\vendor\nikic\php-parser\lib\PhpParser\PrettyPrinter\Standard.php(359): PhpParser\PrettyPrinterAbstract->pCommaSeparated()
#16 D:\Users\brett\workspace\Attendize\vendor\nikic\php-parser\lib\PhpParser\PrettyPrinterAbstract.php(219): PhpParser\PrettyPrinter\Standard->pExpr_FuncCall()
#17 D:\Users\brett\workspace\Attendize\vendor\nikic\php-parser\lib\PhpParser\PrettyPrinterAbstract.php(188): PhpParser\PrettyPrinterAbstract->pPrec()
#18 D:\Users\brett\workspace\Attendize\vendor\nikic\php-parser\lib\PhpParser\PrettyPrinter\Standard.php(283): PhpParser\PrettyPrinterAbstract->pPrefixOp()
#19 D:\Users\brett\workspace\Attendize\vendor\nikic\php-parser\lib\PhpParser\PrettyPrinterAbstract.php(219): PhpParser\PrettyPrinter\Standard->pExpr_BooleanNot()
#20 D:\Users\brett\workspace\Attendize\vendor\nikic\php-parser\lib\PhpParser\PrettyPrinterAbstract.php(183): PhpParser\PrettyPrinterAbstract->pPrec()
#21 D:\Users\brett\workspace\Attendize\vendor\nikic\php-parser\lib\PhpParser\PrettyPrinter\Standard.php(111): PhpParser\PrettyPrinterAbstract->pInfixOp()
#22 D:\Users\brett\workspace\Attendize\vendor\nikic\php-parser\lib\PhpParser\PrettyPrinterAbstract.php(175): PhpParser\PrettyPrinter\Standard->pExpr_Assign()
#23 D:\Users\brett\workspace\Attendize\vendor\nikic\php-parser\lib\PhpParser\PrettyPrinterAbstract.php(156): PhpParser\PrettyPrinterAbstract->p()
#24 D:\Users\brett\workspace\Attendize\vendor\nikic\php-parser\lib\PhpParser\PrettyPrinter\Standard.php(612): PhpParser\PrettyPrinterAbstract->pStmts()
#25 D:\Users\brett\workspace\Attendize\vendor\nikic\php-parser\lib\PhpParser\PrettyPrinterAbstract.php(175): PhpParser\PrettyPrinter\Standard->pStmt_If()
#26 D:\Users\brett\workspace\Attendize\vendor\nikic\php-parser\lib\PhpParser\PrettyPrinterAbstract.php(156): PhpParser\PrettyPrinterAbstract->p()
#27 D:\Users\brett\workspace\Attendize\vendor\nikic\php-parser\lib\PhpParser\PrettyPrinter\Standard.php(580): PhpParser\PrettyPrinterAbstract->pStmts()
#28 D:\Users\brett\workspace\Attendize\vendor\nikic\php-parser\lib\PhpParser\PrettyPrinterAbstract.php(175): PhpParser\PrettyPrinter\Standard->pStmt_ClassMethod()
#29 D:\Users\brett\workspace\Attendize\vendor\nikic\php-parser\lib\PhpParser\PrettyPrinterAbstract.php(156): PhpParser\PrettyPrinterAbstract->p()
#30 D:\Users\brett\workspace\Attendize\vendor\nikic\php-parser\lib\PhpParser\PrettyPrinter\Standard.php(740): PhpParser\PrettyPrinterAbstract->pStmts()
#31 D:\Users\brett\workspace\Attendize\vendor\nikic\php-parser\lib\PhpParser\PrettyPrinter\Standard.php(537): PhpParser\PrettyPrinter\Standard->pClassCommon()
#32 D:\Users\brett\workspace\Attendize\vendor\nikic\php-parser\lib\PhpParser\PrettyPrinterAbstract.php(175): PhpParser\PrettyPrinter\Standard->pStmt_Class()
#33 D:\Users\brett\workspace\Attendize\vendor\nikic\php-parser\lib\PhpParser\PrettyPrinterAbstract.php(156): PhpParser\PrettyPrinterAbstract->p()
#34 D:\Users\brett\workspace\Attendize\vendor\nikic\php-parser\lib\PhpParser\PrettyPrinter\Standard.php(511): PhpParser\PrettyPrinterAbstract->pStmts()
#35 D:\Users\brett\workspace\Attendize\vendor\nikic\php-parser\lib\PhpParser\PrettyPrinterAbstract.php(175): PhpParser\PrettyPrinter\Standard->pStmt_Namespace()
#36 D:\Users\brett\workspace\Attendize\vendor\nikic\php-parser\lib\PhpParser\PrettyPrinterAbstract.php(156): PhpParser\PrettyPrinterAbstract->p()
#37 D:\Users\brett\workspace\Attendize\vendor\nikic\php-parser\lib\PhpParser\PrettyPrinterAbstract.php(94): PhpParser\PrettyPrinterAbstract->pStmts()
#38 D:\Users\brett\workspace\Attendize\vendor\classpreloader\classpreloader\src\ClassPreloader.php(120): PhpParser\PrettyPrinterAbstract->prettyPrint()
#39 D:\Users\brett\workspace\Attendize\vendor\laravel\framework\src\Illuminate\Foundation\Console\OptimizeCommand.php(89): ClassPreloader\ClassPreloader->getCode()
#40 D:\Users\brett\workspace\Attendize\vendor\laravel\framework\src\Illuminate\Foundation\Console\OptimizeCommand.php(70): Illuminate\Foundation\Console\OptimizeCommand->compileClasses()
#41 D:\Users\brett\workspace\Attendize\vendor\laravel\framework\src\Illuminate\Container\Container.php(503): Illuminate\Foundation\Console\OptimizeCommand->fire()
#42 D:\Users\brett\workspace\Attendize\vendor\laravel\framework\src\Illuminate\Container\Container.php(503): call_user_func_array:{D:\Users\brett\workspace\Attendize\vendor\laravel\framework\src\Illuminate\Container\Container.php:503}()
#43 D:\Users\brett\workspace\Attendize\vendor\laravel\framework\src\Illuminate\Console\Command.php(150): Illuminate\Container\Container->call()
#44 D:\Users\brett\workspace\Attendize\vendor\symfony\console\Command\Command.php(256): Illuminate\Console\Command->execute()
#45 D:\Users\brett\workspace\Attendize\vendor\laravel\framework\src\Illuminate\Console\Command.php(136): Symfony\Component\Console\Command\Command->run()
#46 D:\Users\brett\workspace\Attendize\vendor\laravel\framework\src\Illuminate\Console\Application.php(62): Illuminate\Console\Command->run()
#47 D:\Users\brett\workspace\Attendize\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(159): Illuminate\Console\Application->call()
#48 D:\Users\brett\workspace\Attendize\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(213): Illuminate\Foundation\Console\Kernel->call()
#49 D:\Users\brett\workspace\Attendize\app\Http\Controllers\InstallerController.php(118): Illuminate\Support\Facades\Facade::__callStatic()
#50 D:\Users\brett\workspace\Attendize\app\Http\Controllers\InstallerController.php(118): Illuminate\Support\Facades\Artisan::call()
#51 D:\Users\brett\workspace\Attendize\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(256): App\Http\Controllers\InstallerController->postInstaller()
#52 D:\Users\brett\workspace\Attendize\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(256): call_user_func_array:{D:\Users\brett\workspace\Attendize\vendor\laravel\framework\src\Illuminate\Routing\Controller.php:256}()
#53 D:\Users\brett\workspace\Attendize\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(164): Illuminate\Routing\Controller->callAction()
#54 D:\Users\brett\workspace\Attendize\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(112): Illuminate\Routing\ControllerDispatcher->call()
#55 D:\Users\brett\workspace\Attendize\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(139): Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}()
#56 D:\Users\brett\workspace\Attendize\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(139): call_user_func:{D:\Users\brett\workspace\Attendize\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:139}()
#57 D:\Users\brett\workspace\Attendize\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#58 D:\Users\brett\workspace\Attendize\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): call_user_func:{D:\Users\brett\workspace\Attendize\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:103}()
#59 D:\Users\brett\workspace\Attendize\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(114): Illuminate\Pipeline\Pipeline->then()
#60 D:\Users\brett\workspace\Attendize\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(69): Illuminate\Routing\ControllerDispatcher->callWithinStack()
#61 D:\Users\brett\workspace\Attendize\vendor\laravel\framework\src\Illuminate\Routing\Route.php(203): Illuminate\Routing\ControllerDispatcher->dispatch()
#62 D:\Users\brett\workspace\Attendize\vendor\laravel\framework\src\Illuminate\Routing\Route.php(134): Illuminate\Routing\Route->runWithCustomDispatcher()
#63 D:\Users\brett\workspace\Attendize\vendor\laravel\framework\src\Illuminate\Routing\Router.php(704): Illuminate\Routing\Route->run()
#64 D:\Users\brett\workspace\Attendize\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(139): Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#65 D:\Users\brett\workspace\Attendize\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(139): call_user_func:{D:\Users\brett\workspace\Attendize\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:139}()
#66 D:\Users\brett\workspace\Attendize\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#67 D:\Users\brett\workspace\Attendize\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): call_user_func:{D:\Users\brett\workspace\Attendize\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:103}()
#68 D:\Users\brett\workspace\Attendize\vendor\laravel\framework\src\Illuminate\Routing\Router.php(706): Illuminate\Pipeline\Pipeline->then()
#69 D:\Users\brett\workspace\Attendize\vendor\laravel\framework\src\Illuminate\Routing\Router.php(671): Illuminate\Routing\Router->runRouteWithinStack()
#70 D:\Users\brett\workspace\Attendize\vendor\laravel\framework\src\Illuminate\Routing\Router.php(631): Illuminate\Routing\Router->dispatchToRoute()
#71 D:\Users\brett\workspace\Attendize\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(236): Illuminate\Routing\Router->dispatch()
#72 D:\Users\brett\workspace\Attendize\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(139): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
#73 D:\Users\brett\workspace\Attendize\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(139): call_user_func:{D:\Users\brett\workspace\Attendize\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:139}()
#74 D:\Users\brett\workspace\Attendize\app\Http\Middleware\GeneralChecks.php(25): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#75 D:\Users\brett\workspace\Attendize\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): app\Http\Middleware\GeneralChecks->handle()
#76 D:\Users\brett\workspace\Attendize\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array:{D:\Users\brett\workspace\Attendize\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:124}()
#77 D:\Users\brett\workspace\Attendize\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\VerifyCsrfToken.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#78 D:\Users\brett\workspace\Attendize\app\Http\Middleware\VerifyCsrfToken.php(24): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle()
#79 D:\Users\brett\workspace\Attendize\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): App\Http\Middleware\VerifyCsrfToken->handle()
#80 D:\Users\brett\workspace\Attendize\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array:{D:\Users\brett\workspace\Attendize\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:124}()
#81 D:\Users\brett\workspace\Attendize\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#82 D:\Users\brett\workspace\Attendize\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): Illuminate\View\Middleware\ShareErrorsFromSession->handle()
#83 D:\Users\brett\workspace\Attendize\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array:{D:\Users\brett\workspace\Attendize\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:124}()
#84 D:\Users\brett\workspace\Attendize\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#85 D:\Users\brett\workspace\Attendize\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): Illuminate\Session\Middleware\StartSession->handle()
#86 D:\Users\brett\workspace\Attendize\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array:{D:\Users\brett\workspace\Attendize\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:124}()
#87 D:\Users\brett\workspace\Attendize\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#88 D:\Users\brett\workspace\Attendize\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle()
#89 D:\Users\brett\workspace\Attendize\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array:{D:\Users\brett\workspace\Attendize\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:124}()
#90 D:\Users\brett\workspace\Attendize\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#91 D:\Users\brett\workspace\Attendize\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): Illuminate\Cookie\Middleware\EncryptCookies->handle()
#92 D:\Users\brett\workspace\Attendize\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array:{D:\Users\brett\workspace\Attendize\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:124}()
#93 D:\Users\brett\workspace\Attendize\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php(42): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#94 D:\Users\brett\workspace\Attendize\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle()
#95 D:\Users\brett\workspace\Attendize\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array:{D:\Users\brett\workspace\Attendize\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:124}()
#96 D:\Users\brett\workspace\Attendize\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#97 D:\Users\brett\workspace\Attendize\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): call_user_func:{D:\Users\brett\workspace\Attendize\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:103}()
#98 D:\Users\brett\workspace\Attendize\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(122): Illuminate\Pipeline\Pipeline->then()
#99 D:\Users\brett\workspace\Attendize\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(87): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#100 D:\Users\brett\workspace\Attendize\public\index.php(52): Illuminate\Foundation\Http\Kernel->handle()
#101 D:\Users\brett\workspace\Attendize\public\index.php(0): {main}()
#102 {main}

**Comment by bretto36** [comment]
Figured out the issue. When running xdebug it limits the maxmimum nested function calls - 

Adding 

xdebug.max_nesting_level = 200

to php.ini and restarting apache solves the issue.

**Comment by Attendize** [comment]
This has come up a few times so I'll add it to the troubleshooting section in the docs.
