### ISSUE TITLE
Install error - unable to boot ApiServiceProvider

### ISSUE THREAD

**Issue by lkrempler** [Attendize/Attendize#250]
Today i want to install attendize for the first time. (Version: 1.0.0-alpha)

After open the install url - it throw an error like this:
RuntimeException in DingoServiceProvider.php line 82:
Unable to boot ApiServiceProvider, configure an API domain or prefix.

I could solve the issue when i add to my env file this line:
API_PREFIX=api

I think you should define this as standard in the config of dingo.

**Comment by daveearley** [comment]
Hi @lkrempler 

This issue should be fixed in the latest release 👍
