### ISSUE TITLE
Offline Payment Information disables Card Number field

### ISSUE THREAD

**Issue by jefhar** [Attendize/Attendize#257]
I am using Stripe as the payment gateway and have off-line payment information.

Using Stripe, the Credit card block is displayed (as opposed to PayPal, which sends the user to a paypal window for credit card processing). User clicks "Pay using offline method" and the credit card information disappears and is replaced with the Offline Payment Instructions. So far, so good.

User changes his mind and unchecks "Pay using offline method" and the credit card block is revealed, but Card Number and CVC fields remain disabled.

**Comment by daveearley** [comment]
This was fixed previously but must have reappeared. I'll have a look. Cheers!

**Comment by johannac** [comment]
This appears to have been fixed at some point over the years. Please reopen a new ticket using the bug template if it's still a problem.
