### ISSUE TITLE
Weekly Report to Organizer [feature][wishlist]

### ISSUE THREAD

**Issue by MostafaAttia** [Attendize/Attendize#264]
I would like to send a weekly (or daily) report to event organizer instead of sending an email with each order.

Say there are 1000 tickets for an event, I don't want to send 1000 emails to organizer with each event !

**Comment by daveearley** [comment]
This would be handy but would require crons and would add a lot of complication. I'll close this for now but tag it as a feature and potentially re-open for v2. Cheers!
