### ISSUE TITLE
Error when cancel attendee

### ISSUE THREAD

**Issue by MostafaAttia** [Attendize/Attendize#268]
ErrorException: Undefined variable: error_message in /var/www/html/attendize/app/Http/Controllers/EventAttendeesController.php:778 .

Also the attendee is deleted but the Order is NOT .

**Comment by githubertus** [comment]
Yeah, same Exception here with latest version.
To fix you may add
`$error_message = FALSE;`
right in the beginning of the postCancelAttendee() function.

**Comment by johannac** [comment]
I believe this has been addressed at some point over the years (the code doesn't actually exist anymore so it's been refactored). If this is still a problem please reopen a new ticket using the bug template.
