### ISSUE TITLE
Compiling scripts and stylesheets

### ISSUE THREAD

**Issue by markwalet** [Attendize/Attendize#27]
It's generally a good idea to use some kind of processor for your styling and js files.
Maybe take a look at gulp? Works really good with Laravel.
All those javascripts and styling in the head is not necessary.. For js files I recommend a big file at the bottom of your html for performance.

**Comment by Attendize** [comment]
I'm currently using grunt to compile all the less and combine JS etc. The majority of the JS is combined into the backend.js file. There definitely are a few snippets here and there that should be in there too though.

**Comment by markwalet** [comment]
Ah, did miss that, sorry!
Yeah some snippets could be added haha. Not important right now.
