### ISSUE TITLE
Event Flyer Not Uploading

### ISSUE THREAD

**Issue by opoch123** [Attendize/Attendize#271]
Hello, when I upload the event flyer it is not displaying on my page with the following path:

"/user_content/event_images/event_image-04a0488eb6710620fc8aea9f74668b60.jpg"

![1](https://cloud.githubusercontent.com/assets/24359842/20861821/6b3bd8d6-b967-11e6-94bf-4451e2e2cfe3.jpg)

However, when I change the path to the following it works:

http://localhost/attendize/public/user_content/event_images/event_image-04a0488eb6710620fc8aea9f74668b60.jpg

![2](https://cloud.githubusercontent.com/assets/24359842/20861836/d5418e2e-b967-11e6-8d84-02a6fe5bb72d.JPG)

It does not stay because I made the change in chrome developer. Where can I fix this? 
Also, where does the source HTML code get generated for the site? Where I can I go to modify this directly?

Thanks

**Comment by wannaco** [comment]
This is an issue related to this https://github.com/Attendize/Attendize/issues/363
so you can look at the following  and update it:

file \resources\views\Public\ViewEvent\Partials\EventDescriptionSection.blade.php
line 16

` <img alt="{{$event->title}}" src="{{URL::to(config('attendize.cdn_url_user_assets')).'/'.$event->images->first()['image_path']}}" property="image">`
