### ISSUE TITLE
Multiple prices for the same ticket 

### ISSUE THREAD

**Issue by pvullioud** [Attendize/Attendize#276]
I have 100 tickets available for section A. 
This section have different prices for Adults, Children ... etc

With the actual configuration, I can create multiple tickets. That is great. But If I do it, I'll lost the ability to limit to 100,  the total of tickets per section.

And usually, we can have more than one sector in a place like sector A, sector B.

Did I miss something with the actual system? Could this be useful in a future release ?

**Comment by 8temps** [comment]
i have the same problem.

**Comment by jeremyquinton** [comment]
@pvullioud @8temps I can see why this will be useful. The main idea behind Attendize is to be able to issue tickets at the door for an event and not for particular seating arrangements e.g. a theatre or sporting event which has different prices based on a seats with a specific number of tickets 

I doubt we would consider this
