### ISSUE TITLE
Sorry, the page you are looking for could not be found.

### ISSUE THREAD

**Issue by jpfernandezl** [Attendize/Attendize#281]
I could install Attendize at C:\xampp\htdocs\Attendize
Database is fine
When I go to http://localhost/Attendize/
I see the message **Sorry, the page you are looking for could not be found.**

Help please.

**Comment by daveearley** [comment]
it looks like your web server isn't configured correctly. Try searching for "laravel on apache server", it should  point you in the right direction.
