### ISSUE TITLE
Issue when setting up local docker environment

### ISSUE THREAD

**Issue by tristanguo** [Attendize/Attendize#282]
Hey, I am not able to set to local docker environment, according to the instructions, when I run 
$ docker-compose run php php artisan attendize:install

I get errors:
--------------------
Attempting to install Attendize v1.0.0
--------------------
Generating app key
Migrating database.
[2016-12-28 09:51:42] production.ERROR: PDOException: could not find driver in /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:55
Stack trace: ... 

Anyone set it up successfully?

**Comment by KlausGPaul** [comment]
While I am still struggling myself, this is a missing MySQL driver, see e.g. http://stackoverflow.com/questions/13375061/installing-pdo-driver-on-mysql-linux-server for a fix. While the docker files worked for me, I currently fail dismally on the direct install.

**Comment by tristanguo** [comment]
A pull request has been merged to fix related problem. So this issue can be closed. Thanks.

**Comment by jeremyquinton** [comment]
A new docker environment exists with Attendize now so am closing this issue.
