### ISSUE TITLE
How do i use another omnipay provider (Mollie)

### ISSUE THREAD

**Issue by Greenfielt** [Attendize/Attendize#286]
I've tried everything, but my new provider isn't showing up in any list. 
I've followed this: https://github.com/thephpleague/omnipay-mollie

But without succes... anyone who can help me?

**Comment by jeremyquinton** [comment]
@Greenfielt you can have a look at how I implemented a dummy payment gateway here. 
https://github.com/Attendize/Attendize/pull/398/files

I will put together a guide on how to implement a new payment gateway soon. 

I'm going to close this ticket off as its old and more of a question than an issue.
