### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by bs2000** [Attendize/Attendize#288]
So I uploaded the folder and changed permission for the files listed will 777. Now I keep them in the attendiz folder so it won't take over my website. However when I go to www.mydomain.com/attendiz/install nothing happens.

I have done this for other platforms I use and never had an issue but most of them actually had an install.php file.

**Comment by daveearley** [comment]
Does www.mydomain.com/attendiz/index.php/install work?

**Comment by bs2000** [comment]
Doing that way does turn up a no input file specified screen

**Comment by daveearley** [comment]
Sounds like your server isn't configured correctly. Attendize is built using the Laravel Framework, so Googling "configuring Laravel for [INSERT SERVER NAME HERE]" should point you in the right direction.

**Comment by bs2000** [comment]
I will looked that up it is bluedomino server which I believe is UNIX

**Comment by bs2000** [comment]
I pull up lots of info non for my domain, and I don't own the server

**Comment by daveearley** [comment]
The web server will most likely be Apache or Nginx. When you find out which one you're using Google  "configuring Laravel for [INSERT SERVER NAME HERE]"
