### ISSUE TITLE
  [PDOException] 

### ISSUE THREAD

**Issue by iStorry** [Attendize/Attendize#289]
App key exists -- skipping
Migrating database.
[2017-01-16 12:11:35] production.ERROR: PDOException: could not find driver in /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:55
Stack trace:
#0 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(55): PDO->__construct('mysql:host=loca...', 'root', '14JgZYjEHH5zHgX...', Array)
#1 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php(24): Illuminate\Database\Connectors\Connector->createConnection('mysql:host=loca...', Array, Array)
#2 /usr/share/nginx/html/attendize/bootstrap/cache/compiled.php(11851): Illuminate\Database\Connectors\MySqlConnector->connect(Array)
#3 [internal function]: Illuminate\Database\Connectors\ConnectionFactory->Illuminate\Database\Connectors\{closure}()
#4 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Database/Connection.php(908): call_user_func(Object(Closure))
#5 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Database/Connection.php(776): Illuminate\Database\Connection->getPdo()
#6 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Database/Connection.php(661): Illuminate\Database\Connection->reconnectIfMissingConnection()
#7 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Database/Connection.php(342): Illuminate\Database\Connection->run('select * from i...', Array, Object(Closure))
#8 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Database/Schema/MySqlBuilder.php(21): Illuminate\Database\Connection->select('select * from i...', Array)
#9 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Database/Migrations/DatabaseMigrationRepository.php(141): Illuminate\Database\Schema\MySqlBuilder->hasTable('migrations')
#10 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(404): Illuminate\Database\Migrations\DatabaseMigrationRepository->repositoryExists()
#11 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(103): Illuminate\Database\Migrations\Migrator->repositoryExists()
#12 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(58): Illuminate\Database\Console\Migrations\MigrateCommand->prepareDatabase()
#13 [internal function]: Illuminate\Database\Console\Migrations\MigrateCommand->fire()
#14 /usr/share/nginx/html/attendize/bootstrap/cache/compiled.php(1257): call_user_func_array(Array, Array)
#15 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Console/Command.php(169): Illuminate\Container\Container->call(Array)
#16 /usr/share/nginx/html/attendize/vendor/symfony/console/Command/Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\BufferedOutput))
#17 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Console/Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\BufferedOutput))
#18 /usr/share/nginx/html/attendize/vendor/symfony/console/Application.php(791): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\BufferedOutput))
#19 /usr/share/nginx/html/attendize/vendor/symfony/console/Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Database\Console\Migrations\MigrateCommand), Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\BufferedOutput))
#20 /usr/share/nginx/html/attendize/vendor/symfony/console/Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\BufferedOutput))
#21 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Console/Application.php(64): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\BufferedOutput))
#22 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(170): Illuminate\Console\Application->call('migrate', Object(Illuminate\Support\Collection))
#23 /usr/share/nginx/html/attendize/bootstrap/cache/compiled.php(6356): Illuminate\Foundation\Console\Kernel->call('migrate', Array)
#24 /usr/share/nginx/html/attendize/app/Console/Commands/Install.php(60): Illuminate\Support\Facades\Facade::__callStatic('call', Array)
#25 [internal function]: App\Console\Commands\Install->handle()
#26 /usr/share/nginx/html/attendize/bootstrap/cache/compiled.php(1257): call_user_func_array(Array, Array)
#27 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Console/Command.php(169): Illuminate\Container\Container->call(Array)
#28 /usr/share/nginx/html/attendize/vendor/symfony/console/Command/Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#29 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Console/Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#30 /usr/share/nginx/html/attendize/vendor/symfony/console/Application.php(791): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#31 /usr/share/nginx/html/attendize/vendor/symfony/console/Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(App\Console\Commands\Install), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#32 /usr/share/nginx/html/attendize/vendor/symfony/console/Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#33 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#34 /usr/share/nginx/html/attendize/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#35 {main}  

                         
  [PDOException]         
  could not find driver

**Comment by daveearley** [comment]
You're likely missing the **pdo_mysql** module. You'll find more info by googling the error message " PDOException: could not find driver ".

**Comment by harshmalik** [comment]
I am also getting the same PDOException

Have googled extensively but nothing works so far.

Any help!

I am using Mac high Sierra v10.13.4

**Comment by re1nth** [comment]
Hey, 
Try replacing the 12th line in dockerfile-php (located in Attendize folder) with the below line :
&& docker-php-ext-install -j$(nproc) pdo_pgsql pgsql pdo_mysql mcrypt gd zip.

**Comment by ajita-asthana** [comment]
I did the same @re1nth but still doesn't work.
Did it for you @harshmalik ?

**Comment by D3vStAr** [comment]
@ajita-asthana is your pdo_mysql extension enabled in php.ini?

**Comment by ajita-asthana** [comment]
Yea, I enabled it by removing the ‘;’ from php.ini file.

**Comment by re1nth** [comment]
Hey @ ajita-asthana,
After saving I think you need to re run the commands starting from
'docker-compose build' .
I got pdo_mysql extension enabled after doing this.
