### ISSUE TITLE
How to Integrate Attendize with other systems

### ISSUE THREAD

**Issue by tristanguo** [Attendize/Attendize#290]
Hey I am looking for a way to integrate Attendize with other systems.

For example, I want to have a notification when 'events' like new event created, new registration created occurs in Attendize, How can I hook into these events and ask external system to do custom handling?  Is this ability provided by Attendize already or I have to inject code everywhere those events are triggerd?

**Comment by daveearley** [comment]
Hi @tristanguo,

Currently there is only an event triggered [when an order is created](https://github.com/attendize/attendize/blob/ab2ceff24f496e4226c2ce2ec568950097901dee/app/Listeners/OrderCompletedListener.php#L34-L34), so you'd had to add the hook yourself.

Cheers
