### ISSUE TITLE
Check-in function does not work

### ISSUE THREAD

**Issue by ungelovende** [Attendize/Attendize#291]
Why doesn't the check-in function work?

It looks like this even before I started to issue tickets...
![image](https://cloud.githubusercontent.com/assets/25183077/22041383/f3ba90f4-dd06-11e6-84d4-f263158782c2.png)

After issue one ticket, I cant find it with the search.

And the "scanner" which phones does it work on? I tried it on a Andriod didnt work.

**Comment by KlausGPaul** [comment]
Have you checked https://www.kirupa.com/html5/accessing_your_webcam_in_html5.htm ? Also, the problem title may be more like "camera does not get activated by check-in"....

**Comment by shahiran12395** [comment]
why value 0 or 1 is consider as check in. it suppose to be 1 for check in and 0 is not check in yet

**Comment by jeremyquinton** [comment]
@ungelovende @KlausGPaul @shahiran12395 In the latest version of Attendize checkin is working on the desktop version. 

The QR code scanner works on safari on iPhone and Firefox for Android. 

There are some issues with chrome on iphone these need to be addresses.

**Comment by johannac** [comment]
The check in page works now as described by Jeremy.
