### ISSUE TITLE
Omnipay Integration [feature] [enhancement] [wishlist]

### ISSUE THREAD

**Issue by drjagan** [Attendize/Attendize#297]
Instead of trying to integrate multiple payment gateways, can Attendize have a robust [Omnipay ](https://github.com/thephpleague/omnipay) Integration please? 

That way Attendize can support a [large number of payment gateways](https://github.com/thephpleague/omnipay#payment-gateways) out of the box. 

Thank you for considering this feature request.

**Comment by daveearley** [comment]
Attendize already uses Omnipay to handle payments. V2 will bring much improved integration also
