### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by cpalop** [Attendize/Attendize#299]
I've just followed the steps for manual installation and when i'm trying to install it get this error

Warning: require(/home/u771664184/public_html/attendize/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /home/u771664184/public_html/attendize/bootstrap/autoload.php on line 17
PHP Fatal error:  require(): Failed opening required '/home/u771664184/public_html/attendize/bootstrap/../vendor/autoload.php' (include_path='.:/opt/alt/php56/usr/share/pear:/opt/alt/php56/usr/share/php') in /home/u771664184/public_html/attendize/bootstrap/autoload.php on line 17

**Comment by andresnijder** [comment]
try `php composer install`

**Comment by daveearley** [comment]
Did you get this working? as @andresnijder said, it looks like you haven't run composer

**Comment by cpalop** [comment]
I've tried but i get this error "could not open input file: composer"

**Comment by andresnijder** [comment]
@cpalop first you need to install Composer. Just install it in the root of the project. 
`php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('SHA384', 'composer-setup.php') === '55d6ead61b29c7bdee5cccfb50076874187bd9f21f65d8991d46ec5cc90518f447387fb9f76ebae1fbbacf329e583e30') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php composer-setup.php
php -r "unlink('composer-setup.php');"`
When finished, run `php composer.phar install`

**Comment by cpalop** [comment]
Ive installed composer on project folder and the run the attendize installation, got this error

`$ php artisan attendize:install
PHP Warning:  require(/var/www/html/attendize/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/attendize/bootstrap/autoload.php on line 17
PHP Fatal error:  require(): Failed opening required '/var/www/html/attendize/bootstrap/../vendor/autoload.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/html/attendize/bootstrap/autoload.php on line 17`

**Comment by andresnijder** [comment]
Did you run `php composer.phar install` before running artisan?

**Comment by cpalop** [comment]
yes it's intalled but then run artisan and got this 
`PHP Fatal error:  Uncaught exception 'ReflectionException' with message 'Class log does not exist' in /var/www/html/attendize/bootstrap/cache/compiled.php:1355
Stack trace:
#0 /var/www/html/attendize/bootstrap/cache/compiled.php(1355): ReflectionClass->__construct('log')
#1 /var/www/html/attendize/bootstrap/cache/compiled.php(1309): Illuminate\Container\Container->build('log', Array)
#2 /var/www/html/attendize/bootstrap/cache/compiled.php(1871): Illuminate\Container\Container->make('log', Array)
#3 /var/www/html/attendize/bootstrap/cache/compiled.php(1410): Illuminate\Foundation\Application->make('Psr\\Log\\LoggerI...')
#4 /var/www/html/attendize/bootstrap/cache/compiled.php(1387): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#5 /var/www/html/attendize/bootstrap/cache/compiled.php(1373): Illuminate\Container\Container->getDependencies(Array, Array)
#6 /var/www/html/attendize/bootstrap/cache/compiled.php(1309): Illuminate\Container\Container->build('App\\Exceptions\\...', Array)
#7 /var/www/html/att in /var/www/html/attendize/bootstrap/cache/compiled.php on line 1355`

**Comment by andresnijder** [comment]
make sure that composer installed all packages, check for any errors in the output.
try to remove: /var/www/html/attendize/bootstrap/cache/compiled.php
then please run `php composer.phar dump-autoload` 
and `php artisan optimize`

**Comment by cpalop** [comment]
I did it and this happen

`$ sudo rm  /var/www/html/attendize/bootstrap/cache/compiled.php
$ cd /var/www/html/attendize
$ php composer.phar dump-autoload
Generating autoload files
$ php artisan optimize
PHP Fatal error:  Uncaught exception 'ReflectionException' with message 'Class log does not exist' in /var/www/html/attendize/vendor/laravel/framework/src/Illuminate/Container/Container.php:734
Stack trace:
#0 /var/www/html/attendize/vendor/laravel/framework/src/Illuminate/Container/Container.php(734): ReflectionClass->__construct('log')
#1 /var/www/html/attendize/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\Container\Container->build('log', Array)
#2 /var/www/html/attendize/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(697): Illuminate\Container\Container->make('log', Array)
#3 /var/www/html/attendize/vendor/laravel/framework/src/Illuminate/Container/Container.php(849): Illuminate\Foundation\Application->make('Psr\\Log\\LoggerI...')
#4 /var/www/html/attendize/vendor/laravel/framework/src/Illuminate/Container/Container.php(804): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#5 /var/www/html/attendize/vendor/laravel/framework/src/Illuminate/Con in /var/www/html/attendize/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 734`

**Comment by andresnijder** [comment]
could you post the contents of you .env file. if some value contains a space, it will break and trigger the error

**Comment by cpalop** [comment]
You were right, there was a space on .env

          _   _                 _ _
     /\  | | | |               | (_)
    /  \ | |_| |_ ___ _ __   __| |_ _______
   / /\ \| __| __/ _ \ '_ \ / _` | |_  / _ \
  / ____ \ |_| ||  __/ | | | (_| | |/ /  __/
 /_/    \_\__|\__\___|_| |_|\__,_|_/___\___|

Success! You can now run Attendize

Now i navigate the the url where is installed and get this 

Sorry, the page you are looking for could not be found.

**Comment by andresnijder** [comment]
make sure 'public' is your webroot. edit you vhost conf

**Comment by cpalop** [comment]
I'm using amazon linux and have everything on /var/www/html attendize is there installed

**Comment by andresnijder** [comment]
locate `/etc/httpd/conf/httpd.conf`
change `DocumentRoot "/var/www/html"` to `DocumentRoot "/var/www/html/public"`
restart Apache

**Comment by cpalop** [comment]
nothing still getting the same error, and restarted mysql also!

**Comment by andresnijder** [comment]
Check the error logs and the Laravel logs located at storage/logs
Also check the permissions of the storage directory

**Comment by jeremyquinton** [comment]
If anyone is experiencing similar issues please see the new installation guide https://www.attendize.com/getting_started.html or try the troubleshooting guide 

https://www.attendize.com/troubleshooting.html
