### ISSUE TITLE
Fresh install, massively broken. 

### ISSUE THREAD

**Issue by davenull** [Attendize/Attendize#3]
No images will load, server has all deps installed. Logs provide no useful information, SELinux is set to permissive, directories are chowned properly. Any ideas on where to hunt?

**Comment by Attendize** [comment]
First off, thanks for trying it out. Second,  what web server are you using? Is there anything in the web server log files? Also does navigating to your-site.com/public/ make any difference?  Cheers!

**Comment by midorikocak** [comment]
Example virtual host configuration on Mac: /etc/apache2/extra/httpd-vhosts.conf

```
<VirtualHost *:80>
    <Directory "/Users/mtkocak/Sites/attendize/public">
        FallbackResource /index.html
        #ErrorDocument 404 /index.html #for older versions of apache
    </Directory>
    DocumentRoot "/Users/mtkocak/Sites/attendize/public"
    ServerName dev.attendize.app
</VirtualHost>
```

Example etc file for local

127.0.0.1 dev.attendize.app

**Comment by markwalet** [comment]
assets and images should still be loaded properly when the project isn't hosted on a root domain. I already made some improvements to fix this for the meta data.
