### ISSUE TITLE
Allocated Seating

### ISSUE THREAD

**Issue by kubacode** [Attendize/Attendize#30]
I've just had a quick look at the demo website and this app looks fantastic! Just wondered if there were any plans to support Allocated Seating tickets as well as General Admission?

**Comment by daveearley** [comment]
Thanks! We plan on adding a plugin system, so features like allocated seating could be added via plugins in the future.

**Comment by PrzemekSkw** [comment]
> Thanks! We plan on adding a plugin system, so features like allocated seating could be added via plugins in the future.

Hello, any change in that?
Regards

**Comment by givitgames** [comment]
> Thanks! We plan on adding a plugin system, so features like allocated seating could be added via plugins in the future.

Good day what are the current plans do bring seating charts to Attendize?
