### ISSUE TITLE
need explication about the install process

### ISSUE THREAD

**Issue by vizivir** [Attendize/Attendize#304]
hello, sorry for my not friendly english i do my best but i'm french .
i have to do some test on attendize for one of my project so i have followed the installation process on the website but this dosen't work , nothing in attendize log and nothing in apache2 log .
Im guessing i do something wrong , or i forgot to do something.
the /public dosen't work , the /install neither .
don't hesitate to ask more info , 
thanks for helping , i don't continue to write to save your eyes.

**Comment by daveearley** [comment]
Try setting APP_DEBUG to true in your .env file and see if any errors are returned.

**Comment by vizivir** [comment]
so there is my .env file : 
`APP_ENV=production
APP_DEBUG=true
APP_URL=192.168.91.18
APP_CIPHER=rijndael-128
APP_KEY=base64:Nun0DCnQO3v05ly87QjZf+/mNNmcuDsrzpNAcho3h0o=
APP_TIMEZONE=

DB_TYPE=mysql
DB_HOST=127.0.0.1
DB_DATABASE=attendize
DB_USERNAME=attendize
DB_PASSWORD=attendize

# https://github.com/NitMedia/wkhtml2pdf#driver-types
WKHTML2PDF_BIN_FILE=wkhtmltopdf-amd64

MAIL_DRIVER=mail
MAIL_PORT=25
MAIL_ENCRYPTION=
MAIL_HOST=maildev
MAIL_FROM_ADDRESS=
MAIL_FROM_NAME=
MAIL_PASSWORD=
MAIL_USERNAME=
API_PREFIX=api
GOOGLE_ANALYTICS_ID=

TWITTER_WIDGET_ID=

LOG=errorlog`

after this i start again attendize with "php artisan up ", but no result , no log, no errors , i think i have do something wrong

**Comment by vizivir** [comment]
i have found where is my error , i have read the other tickets who are open about the installation process and i saw the solution , i haven't installed attendiz in the write place , now it seems to work perfectly , thanks for your help , and sorry a lot for my bad english
