### ISSUE TITLE
Sales Volume Not Calculating

### ISSUE THREAD

**Issue by aethatsme** [Attendize/Attendize#305]
I notice that the total "sales volume" and "ticket sales volume" isn't calculating.
I've only tested using paypal checkout. Not sure if its only reflecting paypal transactions.

Unless there was a patch somewhere that I missed.

![screenshot_1](https://cloud.githubusercontent.com/assets/7725507/22580468/4ccd4c92-e99e-11e6-8f70-bfc31d46a286.jpg)

**Comment by daveearley** [comment]
Hi @aethatsme, what version are you using? also are these live sales or test sales?

**Comment by aethatsme** [comment]
It hasn't worked since ver 0.5, I've upgraded to the latest version 1.0.1 and still no luck. I tried both on test and live, same results.

I did a database migrate with the new version and still doesn't calculate.

**Comment by daveearley** [comment]
There was a similar issue before [here](https://github.com/Attendize/Attendize/issues/121). The fix linked in that thread might fix the issue

**Comment by aethatsme** [comment]
Cool, I see the issue. Thanks for the quick response!
