### ISSUE TITLE
Error when checking out

### ISSUE THREAD

**Issue by careyhead** [Attendize/Attendize#307]
The error message is when the user returns from PayPal successfully. I've checked that the PDF libraries are executable. Using **mail**. I'm getting this error:

```
Exception in Wkhtml2pdf.php line 888:
WKHTMLTOPDF didn't return any data
in Wkhtml2pdf.php line 888
at Wkhtml2pdf->_render() in Wkhtml2pdf.php line 1047
at Wkhtml2pdf->output('F', '/home/comedyarts/public_html/boxoffice/public/user_content/pdf_tickets/UUVHQ32.pdf') in 
Wkhtml2pdf.php line 243
```

I've confirmed the architecture is correct in the .env file. The wkhtml2pdf debug output shows:

```
array:3 [▼
  "input" => "/tmp/749656778.html"
  "command" => "/home/comedyarts/public_html/boxoffice/vendor/nitmedia/wkhtml2pdf/src/Nitmedia/Wkhtml2pdf/lib/wkhtmltopdf-amd64 --orientation 'Portrait' --page-size 'A4' "/tmp/749656778.html"  -"
  "content" => array:3 [▶]
]
```

**Comment by careyhead** [comment]
I fixed it by downloading the most recent binary from http://wkhtmltopdf.org/downloads.html and putting it in the `/vendor/nitmedia/wkhtml2pdf/src/Nitmedia/Wkhtml2pdf/lib/` folder as wkhtml2pdf-new, then updated the .env file accordingly. 

Perhaps something about the newer binary was more compatible with the server (I'm on a hosted server, so maybe it was running Ubuntu, which may not be supported by the binary that ships with the attendize code).

**Comment by demo7up** [comment]
This did not work for me or i didnt do it right but im having the same issue... can someone provide step by step? thanks

**Comment by mattsims** [comment]
@demo7up, make sure that the `WKHTML2PDF_BIN_FILE` setting in your `.env` file is set to the correct driver binary for your system:

> `wkhtmltopdf-0.12.1-OS-X.i386` - Mac OS X 10.8+ (Carbon), 32-bit
> `wkhtmltopdf-amd64` - Linux (Debian Wheezy), 64-bit, for recent distributions (i.e. glibc 2.13 or later)
> `wkhtmltopdf-i386` - Linux (Debian Wheezy), 32-bit, for recent distributions (i.e. glibc 2.13 or later)

Then, make sure that binary is executable, i.e.

`chmod 755 vendor/nitmedia/wkhtml2pdf/src/Nitmedia/Wkhtml2pdf/lib/wkhtmltopdf-amd64`

Hope that helps :+1:

**Comment by alexorbit** [comment]
you  just need  to install the package and you are ready. If you are running debian, 
sudo apt-get install wkhtmltopdf

good luck.
