### ISSUE TITLE
Exception in Wkhtml2pdf.php line 888: WKHTMLTOPDF didn't return any data

### ISSUE THREAD

**Issue by ashleyyounguk** [Attendize/Attendize#308]
Hello

I am getting this issue when trying to download a ticket, I also cannot complete at checkout for free tickets and paid tickets. I also cannot send invites to people.

I've done some research and had lengthy discussions with my hosting provider who came back with this:

We're using CentOS 6 but since installing them missing libraries the wkhtmltopdf-amd64 executes correctly (./attendize/vendor/nitmedia/wkhtml2pdf/src/Nitmedia/Wkhtml2pdf/lib/wkhtmltopdf-amd64) and we've installed the global one which we know works so I no longer believe this is a problem with missing libraries.

For example, converting Google works with both your and our version:

-bash-4.1$ ./public_html/attendize/vendor/nitmedia/wkhtml2pdf/src/Nitmedia/Wkhtml2pdf/lib/wkhtmltopdf-amd64 google.co.uk google.pdf
Unable to load library icui18n "Cannot load library icui18n: (icui18n: cannot open shared object file: No such file or directory)" 
Loading pages (1/6)
Counting pages (2/6)                                               
Resolving links (4/6)                                                       
Loading headers and footers (5/6)                                           
Printing pages (6/6)
Done                                                                      

-bash-4.1$ /usr/bin/wkhtmltopdf google.co.uk google.pdf
Loading pages (1/6)
Counting pages (2/6)                                               
Resolving links (4/6)                                                       
Loading headers and footers (5/6)                                           
Printing pages (6/6)
Done  

Any ideas what's causing this?

**Comment by ashleyyounguk** [comment]
I fixed this by doing the same as @careyhead in https://github.com/Attendize/Attendize/issues/307

**Comment by daveearley** [comment]
Thanks for reporting this @ashleyyounguk, and @careyhead for the fix. I'll see if I can recreate and push a fix. Cheers

**Comment by githubertus** [comment]
I installed Attendize yesterday - same problem here on checking out:
- the included wkhtmltopdf-amd64 fails loading  libgio-2.0.so.0
- latest stable one from http://wkhtmltopdf.org fails on  libXrender.so.1
- and a last try with the "bleeding edge for Ubuntu Trusty"  fails on libxcb.so.1
First of all, these kind of unresolved depencies should be checked and displayed in advance.
Besides that I don't think that relying on binary executables is a good idea anyway. At least it'll reduce the number of successful installations of this very promising package drastically.

**Comment by HighFlyerPL185** [comment]
@daveearley Did you find a fix for this? Is this an Attendize or Wkhtml2pdf issue? I can't get it working at all on Ubuntu 14.04.02.

It is always either throwing up the icui18 error for all of three of executables in the vendor folder, or the message below if I run an Ubuntu executable from .env downloaded from Wkhtml2pdf website:

Exception in Wkhtml2pdf.php line 885:
System error <pre>/home/vagrant/Code/eventum/vendor/nitmedia/wkhtml2pdf/src/Nitmedia/Wkhtml2pdf/lib/wkhtmltox-0.13.0-alpha-7b36694_linux-trusty-amd64.deb: 2: /home/vagrant/Code/eventum/vendor/nitmedia/wkhtml2pdf/src/Nitmedia/Wkhtml2pdf/lib/wkhtmltox-0.13.0-alpha-7b36694_linux-trusty-amd64.deb: Syntax error: newline unexpected
</pre>

I've tried multiple things to fix this. 

- First I had libxext and libxrender errors. Fixed it with apt-get libxext6 and apt-get libxrender1
- Downloaded executable as mentioned above and updated .env
- apt-get update, apt-get install wkhtmltopdf, apt-get install libicu48 (did not exist). [This](https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2242#issuecomment-82343649) recommended to install libicu52, I ran apt-get install libicu52 and it installed successfully.
- Followed [this](https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2242) topic thoroughly, and the end of it seems to talk about <img> tags. Do you have any ideas which tags they might be referring to?

Pulled all my hair out here, but maybe you know a magic fix!

**Comment by githubertus** [comment]
@HighFlyerPL185 
Let me put it this way:
Attendize depends on the third-party binary wkhtmltopdf. And as long as you cannot run this binary from your `command line` flawlessly it's first of all a wkhtmltopdf problem, thus you should trying to get help from the wkhtmltopdf community.

Regarding my hack:
I commented out the complete block of code from Line 870 to 891 of
vendor\nitmedia\wkhtml2pdf\src\Nitmedia\Wkhtml2pdf\Wkhtml2pdf.php
and returned $input instead of $data in the end.

**Comment by jeremyquinton** [comment]
One possible cause of this that I stumbled up is that when composer is run as the root user the vendor/nitmedia/wkhtml2pdf/src/Nitmedia/Wkhtml2pdf/lib directory has the wrong permissions.

The fix in my case was to change the ownership of vendor/nitmedia/wkhtml2pdf/src/Nitmedia/Wkhtml2pdf/lib so that the webserver has executable permissions on that directory and group ownership.
