### ISSUE TITLE
Specified key was too long error - branch develop

### ISSUE THREAD

**Issue by vietdien2005** [Attendize/Attendize#311]
I have already upgrade your source to laravel 5.4 and found this error when i ran migrate. I using MariaDB

[https://laravel-news.com/laravel-5-4-key-too-long-error](https://laravel-news.com/laravel-5-4-key-too-long-error)

So, i want make sure this code in your branch develop to fix that 
File app/Providers/AppServiceProvider.php

```
use Illuminate\Support\Facades\Schema;

public function boot()
{
    Schema::defaultStringLength(191);
}
```

By the way, i have recreate all your migration each table is a file, if you want all files comment to let me know 
Sorry for my bad English

**Comment by daveearley** [comment]
Hi @vietdien2005 

Many thanks for this, I'll add it into the develop branch. That would be great if you could share the migration files.

Many thanks!
