### ISSUE TITLE
Custom questions are not displayed on the order page

### ISSUE THREAD

**Issue by RichardGomer** [Attendize/Attendize#312]
We had a problem on our Attendize installation where custom questions were not being shown, and hence the order form couldn't be submitted.  

I had to change line 1 of `resources/views/Public/ViewEvent/Partials/AttendeeQuestions.blade.php` 

From: `@foreach($ticket->questions->where('is_enabled', 1)->sortBy('sort_order') as $question)`
To: `@foreach($ticket->questions->where('is_enabled', '1')->sortBy('sort_order') as $question)`

i.e putting quotes around the 1 in the where filter, to do a string comparison

**Comment by daveearley** [comment]
Thanks for this @RichardGomer, I hadn't come across it before. What OS, web server, & PHP version are you using?

Cheers!

**Comment by RichardGomer** [comment]
It's a (slightly outdated :o) Apache 2.4 on Ubuntu server 12.04, PHP 5.5.  The "is_enabled" flag seems to be coming through as a string, and I guess the ->where is doing a strict comparison.  

Let me know if you need any more info :)

**Comment by bagage** [comment]
This problem is also present on http://attendize.website/ demo website. Whenever you add a question as required, it does not appear on submit form and users are stuck.

**Comment by wallaceturner** [comment]
How do you even add a question ? Seems the option to do so is missing

![image](https://user-images.githubusercontent.com/2849980/55340906-3166ca80-54d8-11e9-9503-c172f99d6c82.png)

**Comment by bagage** [comment]
@wallaceturner it's totally unrelated to this issue - but it's here. You have to select in sidemenu "surveys" menu than "add question":

![image](https://user-images.githubusercontent.com/1451988/55348726-27cd6a80-54b8-11e9-8ca8-41f98e7a3f57.png)

**Comment by johannac** [comment]
This has been fixed at some point over the years and is no longer happening.
