### ISSUE TITLE
This event has already started.

### ISSUE THREAD

**Issue by githubertus** [Attendize/Attendize#318]
and people can't buy any more tickets because of that?

We're running a 3 days event from Friday to Sunday and it's absolutely normal that a lot of our visitors are buying their tickets when the event has already started but arrive late Friday evening or Saturday morning.

I've tried both: leaving the ticket selling date blank, or entering the event's start and end date explicitely. No difference. Tikets are no more available when the event has started. Wrong logic to my opinion.

**Comment by daveearley** [comment]
This is in place as the system was originally designed for general admission events where sales were stopped to make sure the door list was up to date. 

I see your point and it should definitely be an option so I'll label it as an improvement for the next version.

In the mean time it can be easily edited [here](https://github.com/Attendize/Attendize/blob/master/resources/views/Public/ViewEvent/Partials/EventTicketsSection.blade.php#L8) 

Cheers

**Comment by githubertus** [comment]
Thank you.
Especially for the link. (I'm a complete newbee here)

**Comment by jeremyquinton** [comment]
Attendize by Default now allows tickets to be bought on the day of the event and up until the event has ended. https://github.com/Attendize/Attendize/commit/b1ffb7e6fdd8390700e1801fb10f4c822c35d5b1
