### ISSUE TITLE
Seating map

### ISSUE THREAD

**Issue by giumazzi** [Attendize/Attendize#319]
I see there is not a clickable seating map.
I've seen this [https://github.com/mateuszmarkowski/jQuery-Seat-Charts](url).
Someone working on it?

**Comment by daveearley** [comment]
Hi @giumazzi, no ones working on this yet, but it would be a nice addon. Thanks for the link :+1:

**Comment by ArchGalileu** [comment]
Would be great 😉

Best regards
ArchGalileu

**Comment by MostafaAttia** [comment]
+1 GREAT FEATURE
