### ISSUE TITLE
 php artisan route:list error

### ISSUE THREAD

**Issue by Tyga76** [Attendize/Attendize#327]
when I run php artisan route:list i get the following error. it seems the ApiBaseController has an issue when you run from command line..Any ideas?

[2017-03-05 08:52:00] production.ERROR: exception 'ErrorException' with message 'Trying to get property of non-object' in /Users/tayganpillay/Dev/officialevents/stubs/app/Http/Controllers/API/ApiBaseController.php:15
Stack trace:
#0 /Users/tayganpillay/Dev/officialevents/stubs/app/Http/Controllers/API/ApiBaseController.php(15): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Trying to get p...', '/Users/tayganpi...', 15, Array)
#1 [internal function]: app\Http\Controllers\API\ApiBaseController->__construct()
#2 /Users/tayganpillay/Dev/officialevents/stubs/vendor/laravel/framework/src/Illuminate/Container/Container.php(779): ReflectionClass->newInstanceArgs(Array)
#3 /Users/tayganpillay/Dev/officialevents/stubs/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\Container\Container->build('App\\Http\\Contro...', Array)
#4 /Users/tayganpillay/Dev/officialevents/stubs/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(697): Illuminate\Container\Container->make('App\\Http\\Contro...', Array)
#5 /Users/tayganpillay/Dev/officialevents/stubs/vendor/laravel/framework/src/Illuminate/Foundation/Console/RouteListCommand.php(165): Illuminate\Foundation\Application->make('App\\Http\\Contro...')
#6 /Users/tayganpillay/Dev/officialevents/stubs/vendor/laravel/framework/src/Illuminate/Foundation/Console/RouteListCommand.php(146): Illuminate\Foundation\Console\RouteListCommand->getControllerMiddleware('App\\Http\\Contro...')
#7 /Users/tayganpillay/Dev/officialevents/stubs/vendor/laravel/framework/src/Illuminate/Foundation/Console/RouteListCommand.php(118): Illuminate\Foundation\Console\RouteListCommand->getMiddleware(Object(Illuminate\Routing\Route))
#8 /Users/tayganpillay/Dev/officialevents/stubs/vendor/laravel/framework/src/Illuminate/Foundation/Console/RouteListCommand.php(88): Illuminate\Foundation\Console\RouteListCommand->getRouteInformation(Object(Illuminate\Routing\Route))
#9 /Users/tayganpillay/Dev/officialevents/stubs/vendor/laravel/framework/src/Illuminate/Foundation/Console/RouteListCommand.php(75): Illuminate\Foundation\Console\RouteListCommand->getRoutes()
#10 [internal function]: Illuminate\Foundation\Console\RouteListCommand->fire()
#11 /Users/tayganpillay/Dev/officialevents/stubs/vendor/laravel/framework/src/Illuminate/Container/Container.php(507): call_user_func_array(Array, Array)
#12 /Users/tayganpillay/Dev/officialevents/stubs/vendor/laravel/framework/src/Illuminate/Console/Command.php(169): Illuminate\Container\Container->call(Array)
#13 /Users/tayganpillay/Dev/officialevents/stubs/vendor/symfony/console/Command/Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /Users/tayganpillay/Dev/officialevents/stubs/vendor/laravel/framework/src/Illuminate/Console/Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /Users/tayganpillay/Dev/officialevents/stubs/vendor/symfony/console/Application.php(791): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /Users/tayganpillay/Dev/officialevents/stubs/vendor/symfony/console/Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Foundation\Console\RouteListCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /Users/tayganpillay/Dev/officialevents/stubs/vendor/symfony/console/Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /Users/tayganpillay/Dev/officialevents/stubs/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /Users/tayganpillay/Dev/officialevents/stubs/artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 {main}

  [ErrorException]
  Trying to get property of non-object

**Comment by vietdien2005** [comment]
Too much things to do if you want to run `php artisan route:list`
In `routes.php` comment lines below: 
```
include_once('api_routes.php');

Route::get('install', [
     'as'   => 'showInstaller',
     'uses' => 'InstallerController@showInstaller',
]);

Route::post('install', [
     'as'   => 'postInstaller',
     'uses' => 'InstallerController@postInstaller',
]);

Route::get('{event_id}/tickets/questions', [
      'as'   => 'showTicketQuestions',
      'uses' => 'EventTicketQuestionsController@showQuestions',
]);
Route::post('{event_id}/tickets/questions/create', [
       'as'   => 'postCreateQuestion',
       'uses' => 'EventTicketQuestionsController@postCreateQuestion',
]);

```

In `App\Http\Controllers\MyBaseController.php` change function `__construct()` :  
```
       if (Auth::check()) {
            JavaScript::put([
                'User'                => [
                    'full_name'    => Auth::user()->full_name,
                    'email'        => Auth::user()->email,
                    'is_confirmed' => Auth::user()->is_confirmed,
                ],
                /*
                 * @todo These should be user selectable
                 */
                'DateFormat'          => 'dd-MM-yyyy',
                'DateTimeFormat'      => 'dd-MM-yyyy hh:mm',
                'GenericErrorMessage' => 'Whoops! An unknown error has occurred. Please try again or contact support if the problem persists.'
            ]);    
        

            /*
             * Share the organizers across all views
             */
            View::share('organisers', Organiser::scope()->get());
        }
```

In `App\Models\MyBaseModel.php` change function `scopeScope` : 
```
       table = $this->getTable();
        
        if (!auth()->check()) {
            return $query->where(function ($query) use ($accountId, $table) {
                $query->whereRaw(\DB::raw('(1=0)'));
            });
        }

        if (!$accountId) {
            $accountId = Auth::user()->account_id;
        }

        $query->where(function ($query) use ($accountId, $table) {
            $query->whereRaw(\DB::raw('(' . $table . '.account_id = ' . $accountId . ')'));
        });

        return $query;
``` 
It's too much errors 😢

**Comment by daveearley** [comment]
I've never had reason to list the routes so I haven't come across this, however I'll have a look into it and see if I can find fix the problem. Cheers
