### ISSUE TITLE
missing: one-day tickets for multi-day events

### ISSUE THREAD

**Issue by githubertus** [Attendize/Attendize#329]
With multi-day events it would be nice to have tickets which are valid for a specific day (time period) only.

**Comment by daveearley** [comment]
currently people have been creating a ticket for each day. For example 

- Weekend ticket
- Saturday ticket
- Sunday Ticket

This seems to work so I think adding additional features around this may add unnecessary complexity. But I'd be open to adding it as a plugin in v2.0.0

**Comment by githubertus** [comment]
Hmm, maybe you got me wrong...
Let's say: I'm running a 3-days event from Friday to Sunday.
Of course I can create individual tickets for each day, but the entrance validation will be a problem. The staff at the cash points is used to rely on the qr code scanning -> green/red, only. Thus, a criminal visitor who bought a Sunday Ticket, but arrives already on Friday CAN PASS. Because there's no way to store a 'Valid from to' with the individual tickets.
