### ISSUE TITLE
User can take printouts of the ticket even after cancelling the ticket from backend admin

### ISSUE THREAD

**Issue by ramesh-tr** [Attendize/Attendize#33]
STR: 

1. Create an event
2. Create a free ticket
3. Access the event as a user and book some tickets
4. Cancel those tickets from backend
5. "Order successful" message is displayed to the user even if the user refresh the page
        http://domain/order/<OrderNUM>
It shows no indication of the cancellation of the ticket in the page. 

Also, the user can download a ticket (pdf) after the ticket being cancelled (Again shows no indication of cancellation in the downloaded ticket)

**Comment by bretto36** [comment]
@daveearley - Hey Dave, when i cancel an order it doesn't change is_cancelled to 1 against the order entry in db at all. I can't seem to figure out how to get it to even be the status "Cancelled" it's always partially refunded, or refunded, if i cancell everything and don't give a refund it still doesn't mark order as cancelled. 

May need to think about how that status stuff is going to relate. It correctly sets attendees to cancelled. I've got a pull request for a few bits that i could figure out

**Comment by daveearley** [comment]
Fixed now by @bretto36
