### ISSUE TITLE
Contact request integration Attendize

### ISSUE THREAD

**Issue by Eventtest** [Attendize/Attendize#330]
I tried several time to get in contact with the developers of attendize, but without results. Is anyone still working on it? We are a Swiss based company and we would be interested to discuss some possibilities of integration/development.

**Comment by daveearley** [comment]
Hi @eventtest, yes this is still being worked on. You can get in touch at contact@attendize.com

Cheers

**Comment by Eventtest** [comment]
Hi!
I wrote several email to that address without getting any reply.
Would it be possible to have a Skype contact for example?

Regards,
Eleonora Guido

***************************
Kampagenforum
Hermetschloostrasse 70, 4.01
8048 Zürich/Schweiz
+41 44 515 59 38 Tel.
+41 44 500 16 01 Fax
E-Mail: eguido@kampagnenforum.ch
Web: www.kampagnenforum.ch
Twitter: @kampagneforum <https://twitter.com/Kampagnenforum>
Facebook: www.facebook.com/kampagneforum
<https://www.facebook.com/Kampagnenforum/?fref=ts>
***************************

Am 7. März 2017 um 09:59:41, Dave Earley (notifications@github.com) schrieb:

Hi @eventtest <https://github.com/eventtest>, yes this is still being
worked on. You can get in touch at contact@attendize.com

Cheers

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Attendize/Attendize/issues/330#issuecomment-284661135>,
or mute the thread
