### ISSUE TITLE
Database Columns for Tickets sold vs Quantity Sold

### ISSUE THREAD

**Issue by aethatsme** [Attendize/Attendize#333]
Are these columns suppose to match up in the database?

The quantity_sold column is the actual correct data. However, the tickets_sold column, where is that data displayed at ?

**Comment by daveearley** [comment]
The **tickets_sold** columns are related to affiliates and event stats tables. The affiliates data is shown under the **customize** table on event admin pages, and the event stats are mostly stored for generating charts etc.
