### ISSUE TITLE
Mixed Content Issues behind SSL Proxy

### ISSUE THREAD

**Issue by dfiel** [Attendize/Attendize#336]
Hello,

I have a front-facing Caddy server, that I use for automatic HTTPS, that proxies all requests to an nginx server that serves my instance of Attendize and other things. 

When accessing Attendize externally, I get mixed content errors. In .env, I have set the APP_URL with https, and that doesn't change the outcome. What do I have to change to get all assets to load over HTTPS?

**Comment by githubertus** [comment]
hmm ... no problems here with https, neither on the backend nor on the event page. Which files exactly appear to be loaded via http instead of https?

**Comment by dfiel** [comment]
![image](https://cloud.githubusercontent.com/assets/7292540/23872347/5c5d176c-0804-11e7-9230-8d6fbe17ce36.png)

Looks like everything tries to load over http, but my web server redirects some content to https.

**Comment by githubertus** [comment]
Okay, all I can tell is that files like jquery.min.js are loaded correctly via https on my own site - no exception.
I never had a proxy in front - but I think it's worth to have a look at its configuration.

**Comment by dfiel** [comment]
What can I do to expedite that process?
