### ISSUE TITLE
Problems installing

### ISSUE THREAD

**Issue by opiollo** [Attendize/Attendize#339]
I´m trying to use Attendize to give some free service to some asotiations.
I put the files in a web (online) server with CPanel: 213.136.94.131
But when I try to go to the main url (http://213.136.94.131) I get this message:
//
SORRY!
If you are the owner of this website, please contact your hosting provider: webmaster@213.136.94.131
It is possible you have reached this page because:
//

If I go to public folder (http://213.136.94.131/public) I get this message:

//
404 Not Found
Please forward this error screen to 213.136.94.131's WebMaster.
The server can not find the requested page:
//

What can be the problem? Can I solve?

**Comment by githubertus** [comment]
As I'm getting already a 404 error on trying to display Attendize's readme.md, it looks like the complete package is simply missing.

**Comment by samdb** [comment]
As githubertus has said it looks like you haven't got the webserver looking in the right directory for the Attendize installation. Your best course of action would be to speak to your web host about this and then come back here if you have installation problems.
