### ISSUE TITLE
Payment Gateway on orders table

### ISSUE THREAD

**Issue by bretto36** [Attendize/Attendize#35]
Hi @daveearley  I haven't quite figured out migrations yet on laravel. I want to start implementing a feature for adding multuiple payment gateways, I feel the first thing that needs to be done is add a payment gateway colum to the orders table. That way when we want to issue a refund using a different payment gateway we can. 

Fields i think should be added
payment_gateway - string (default to 'stripe')
payment_reference - string (default to empty) - actually just say trasnaction_id  so nevermind this one. 

ok so it's just the one column. Any chance you could add the migration for that

**Comment by bretto36** [comment]
Also, maybe a payment methods table would be good. 

Table details
code
name
authorisation details (possibly just a text field that we store a serialised array in, instead of having to do a column against the account table)

**Comment by daveearley** [comment]
There's another project built using Laravel which uses Omnipay for payments, they appear to have done it quite well. From what I can see they have a Payment Gateway table in the DB, as you suggested above. You can have a look here: [https://github.com/invoiceninja/invoiceninja](https://github.com/invoiceninja/invoiceninja)

Following their approach could be a good idea.

**Comment by bretto36** [comment]
Yeah, i've gone and looked at invoiceninja. Quite well done. I might use that for my own invoicing system instead of the one i currently pay for. 

I still can't figure out where it adds the gateway table in the migrations.

**Comment by daveearley** [comment]
It's a nice platform alright. The DB migrations should be in the /database/migrations directory. I'm on a phone now so can't link it unfortunately.
