### ISSUE TITLE
[Payment] None of payment gateways is available in Middle-East

### ISSUE THREAD

**Issue by MostafaAttia** [Attendize/Attendize#353]
Hi,
I'm trying to use a gateway called Paytabs because Omnipay, Stripe, Coinbase, Paypal etc.. are not available in the Middle-East (Bahrain/Saudi Arabia/ United Arab Emarites).

The problem is that the solution provided by Paytabs gateway is Javascript-based, so I need to delete all the payment gateways from `postCreateOrder` method in `EventCheckoutController` but I don't know where to begin.

Any help would be much appreciated.
Thanks.

**Comment by samdb** [comment]
Hi Mostafa,

Omnipay is a library that makes it easy to add additional gateways. There are people who have written paytabs drivers for Omnipay that you can integrate.

https://packagist.org/packages/jestillore/omnipay-paytabs
