### ISSUE TITLE
Tests?

### ISSUE THREAD

**Issue by jncampbell** [Attendize/Attendize#36]
How should we develop them? Any suggestions on the directory structure?...conventions?...namespacing?

I think [this](http://stackoverflow.com/questions/8313283/phpunit-best-practices-to-organize-tests) may be a good start.

We should probably start implementing this now while the project is still young.

**Comment by daveearley** [comment]
Tests should definitely be started sooner rather than later alright.  Laravel actually supports testing with PHP unit out of the box, so a lot of the work is done for you. The docs are fairly comprehensive too: [https://laravel.com/docs/5.2/testing](https://laravel.com/docs/5.2/testing)

**Comment by jncampbell** [comment]
Cool. I'm writing some Model tests now. Will likely push them up tomorrow. I'll follow the conventions in the link I posted in the first comment. If anyone has any other suggestions regarding the testing structure, please chime in.

**Comment by daveearley** [comment]
Nice one , cheers @jncampbell!
