### ISSUE TITLE
Can we add new payment gatway in existing script?

### ISSUE THREAD

**Issue by kuldeepJain11** [Attendize/Attendize#366]
Hello,

I want to integrate  'pesapal' payment gatway. Can you please guid me how can i integrate in existing script.

Thanks

**Comment by samdb** [comment]
Attendize uses the Omnipay library to make adding new payment gateways easier. You will need to be proficient in PHP but the following implementation should help.

https://github.com/fruitcake/omnipay-pesapal

**Comment by kuldeepJain11** [comment]
Thanks for reply.

I have already installed this package. and also updated attendize backend payment option as pesapal. you can see it from : http://prntscr.com/jf7m4c
But it is not working. i have also insert new record in database, see: http://prntscr.com/jf7ndf

can you please guid me, how can i remove error and make perfect working application with pesapal.  i will do all coding as per your guidance. if you can. 
After integration i can send you whole the code so you can use in your next version.

Thanks,
Appuno

**Comment by samdb** [comment]
Unfortunately we don't have the development resources to do custom requests like this.

**Comment by kuldeepJain11** [comment]
Ok no problem.

Thanks for your help.

I am a PHP developer. so if you need any help in your project. I can help you.

Thanks

**Comment by kuldeepJain11** [comment]
Hello,

I have setup 'pesapal' payment gatway acoording to 'https://github.com/Attendize/Attendize/issues/179'
and 'https://github.com/fruitcake/omnipay-pesapal' and also change 'is_on_site' to 1 in database, see screenshot: http://prntscr.com/jfmv6y. 
I have created demo account in pesapal and received consumer key and consumer secrete and this information store against pesapal from attendize account setting: https://prnt.sc/jf7m4c.
After all this process, when i checkout from event url, getting error like this:

**(index):3 Uncaught Error: You did not set a valid publishable key. Call Stripe.setPublishableKey() with your publishable key. For more info, see https://stripe.com/docs/stripe.js
    at Function.b.validateKey ((index):3)
    at Function.b.create ((index):2)
    at Function.c.createToken ((index):2)
    at HTMLFormElement.<anonymous> (frontend.js:4673)
    at HTMLFormElement.dispatch (frontend.js:2)
    at HTMLFormElement.r.handle (frontend.js:2)
b.validateKey @ (index):3
b.create @ (index):2
c.createToken @ (index):2
(anonymous) @ frontend.js:4673
dispatch @ frontend.js:2
r.handle @ frontend.js:2**

can you check this? 
Please guide me how can i remove this error.

Thanks
