### ISSUE TITLE
manual install - something went wrong

### ISSUE THREAD

**Issue by TheFridgeMaster** [Attendize/Attendize#369]
Hi there,

I have successfully installed the docker image which allowed me to configure and play with attendize, but now I am attempting to install it in a more production environment manually with php and apache.

When attempting to access http://url-name/install after unzipping I receive 2 messages of "Whoops, looks like something went wrong." and there is nothing available in the storage/logs folder.

I am not sure what is happening here. afaik I am following the instructions to the dot.

**Comment by TheFridgeMaster** [comment]
I derped. All sorted. Upon inspection of the apache error logs, mcrypt.so was not loaded properly.

**Comment by TheFridgeMaster** [comment]
It was just a path issue on my server install. `locate mcrypt.so` and chuck the returned path into `/etc/php5/mods/mcrypt.ini`

**Comment by TomasVotruba** [comment]
I understand that. But how did you find this out?

**Comment by TheFridgeMaster** [comment]
Just looked at the Apache logs and noticed the module couldn't be found.
