### ISSUE TITLE
Invited attendees are flagged "awaiting payment" on the check-in page

### ISSUE THREAD

**Issue by doegox** [Attendize/Attendize#371]
Hi,

symptoms:
* create *free* tickets
* invite a bunch of people via Attendees / Invite Attendees
* go to Check-in
* => they are flagged with a "awaiting payment" banner
Well, even if tickets were not for free, this seems weird to flag them as such anyway.

**Comment by jeremyquinton** [comment]
@doegox I can't replicate this issue anymore. I think this commit https://github.com/Attendize/Attendize/commit/4f252691a43f8c2a9e7ba741c598a5ae9aecc785 fixes the issue

Above where you say free tickets do you mean tickets with a price of zero.

**Comment by doegox** [comment]
yes I meant price=0.
I wanted to test the patch you referred to in the codebase we used (in April), but the code around changed too much. You can this bugreport and I'll reopen it if I see the issue next year when we'll set it up on an updated version.

**Comment by jeremyquinton** [comment]
@doegox thanks for the feedback please re-open it if the issue persists on the new codebase. I have tested thoroughly and can't replicate anymore on master.
