### ISSUE TITLE
docker run --rm -v $(pwd):/app composer/composer install

### ISSUE THREAD

**Issue by odomojuli** [Attendize/Attendize#374]
Having the following issue with composer install.

  Problem 1
    - symfony/class-loader v3.4.9 requires php ^5.5.9|>=7.0.8 -> your PHP version (7.0.7) does not satisfy that requirement.
    - symfony/class-loader v3.4.9 requires php ^5.5.9|>=7.0.8 -> your PHP version (7.0.7) does not satisfy that requirement.
    - Installation request for symfony/class-loader v3.4.9 -> satisfiable by symfony/class-loader[v3.4.9].

**Comment by odomojuli** [comment]
composter update did not resolve the issue

**Comment by shachibista** [comment]
Try:

`docker run --rm -v $(pwd):/app composer --ignore-platform-reqs --no-scripts install`

**Comment by gettyhub** [comment]
I've done that but now it makes all these suggestions about installing other packages...which leads to an error about pdo-sqlite [PDOExecption] driver not found when running the final command:
docker-compose run php php artisan attendize:install

**Comment by jeremyquinton** [comment]
I also go the same issue the message from composer is as follows
```
Problem 1
    - Installation request for symfony/css-selector v3.4.8 -> satisfiable by symfony/css-selector[v3.4.8].
    - symfony/css-selector v3.4.8 requires php ^5.5.9|>=7.0.8 -> your PHP version (7.0.7) does not satisfy that requirement.
  Problem 2
    - Installation request for symfony/filesystem v3.4.8 -> satisfiable by symfony/filesystem[v3.4.8].
    - symfony/filesystem v3.4.8 requires php ^5.5.9|>=7.0.8 -> your PHP version (7.0.7) does not satisfy that requirement.
  Problem 3
    - Installation request for symfony/stopwatch v3.4.8 -> satisfiable by symfony/stopwatch[v3.4.8].
    - symfony/stopwatch v3.4.8 requires php ^5.5.9|>=7.0.8 -> your PHP version (7.0.7) does not satisfy that requirement.
  Problem 4
    - Installation request for symfony/class-loader v3.4.8 -> satisfiable by symfony/class-loader[v3.4.8].
    - symfony/class-loader v3.4.8 requires php ^5.5.9|>=7.0.8 -> your PHP version (7.0.7) does not satisfy that requirement.
  Problem 5
    - Installation request for symfony/dom-crawler v3.4.8 -> satisfiable by symfony/dom-crawler[v3.4.8].
    - symfony/dom-crawler v3.4.8 requires php ^5.5.9|>=7.0.8 -> your PHP version (7.0.7) does not satisfy that requirement.
  Problem 6
    - Installation request for symfony/yaml v3.3.16 -> satisfiable by symfony/yaml[v3.3.16].
    - symfony/yaml v3.3.16 requires php ^5.5.9|>=7.0.8 -> your PHP version (7.0.7) does not satisfy that requirement.
  Problem 7
    - symfony/filesystem v3.4.8 requires php ^5.5.9|>=7.0.8 -> your PHP version (7.0.7) does not satisfy that requirement.
    - friendsofphp/php-cs-fixer v1.13.3 requires symfony/filesystem ^2.1 || ^3.0 -> satisfiable by symfony/filesystem[v3.4.8].
    - Installation request for friendsofphp/php-cs-fixer v1.13.3 -> satisfiable by friendsofphp/php-cs-fixer[v1.13.3].```

For some reason when docker builds the containers the php:7.0-fpm container has version 7.0.7 of php but the php dependancies for these packages is 7.0.8

To fix this issue you can run the following commands
1. docker pull php:7.0-fpm
2. docker-compose build 
3. docker run --rm -v $(pwd):/app composer/composer install
3. docker-compose up -d

**Comment by gettyhub** [comment]
When I get to the step 3 docker run --rm -v $(pwd):/app composer/composer install it gives me OP message.

When I do docker run --rm -v $(pwd):/app composer --ignore-platform-reqs --no-scripts install it says there is nothing to do, but guzzle/guzzle is abandoned, use guzzlehttp/guzzle instead and phpoffice/phpexcel is abandoned, use phpoffice/phpspreadsheet instead.

docker-compose run php php artisan attendize:install still gives me the error about pdo

And http://localhost:8080/install still says there is something gone wrong...
The following warnings may or may not be a problem:
Warning: /usr/share/nginx/html/attendize/bootstrap/cache is not writable
Warning: /usr/share/nginx/html/attendize/.env is not writable
Warning: /usr/share/nginx/html/attendize is not writable

**Comment by jeremyquinton** [comment]
@gettyhub the mysql pdo messages are related to #390 and #386. The Dockerfile is using pgsql as the adapter instead of mysql. 

As for your permissions issues it depends how you are running docker. If you can give me some more info about your host operating system e.g. Linux or Windows I might be able to help.

**Comment by gettyhub** [comment]
I'm running ArchLinux, but I'm also looking at putting this on a CentOS machine (haven't tried it yet just testing to see if I can get it going).

**Comment by jeremyquinton** [comment]
@gettyhub @odomojuli @shachibista. There is a new docker environment merged into master. If you run that setup you should have no problems with composer. 

I created a separate composer docker image which uses the same version of PHP as the PHP containers so should help with composer errors or at least make debugging easier going forward.

**Comment by jeremyquinton** [comment]
Closing off the issue for now as the docker environment is working as expected.
