### ISSUE TITLE
Database connection test in localhost:8080/install

### ISSUE THREAD

**Issue by re1nth** [Attendize/Attendize#379]
Below is the attached image in which the database connection test shows success for random inputs too. Please check over it. Correct me if I am wrong somewhere. 
![details](https://user-images.githubusercontent.com/20339367/40596684-1e6f1eee-625a-11e8-995b-8fc92be693c2.png)

**Comment by gettyhub** [comment]
I've noticed what seems to be the same thing occurring.  
This is possibly followed by whoops something went wrong page, but I'm not sure.

**Comment by samdb** [comment]
We are working on the install process to make it easier to get up and running.

**Comment by re1nth** [comment]
I am no more facing the same error. It is working well.
