### ISSUE TITLE
Install failure

### ISSUE THREAD

**Issue by yhorian1** [Attendize/Attendize#38]
I couldn't get the install to work - having done the manual install and navigated to /public, I'm redirected to: https://cardiff.marketing/attendize/public/select_organiser with a 404.

Am I missing something obvious?

**Comment by bretto36** [comment]
Hi @yhorian1 Can you try setting up a subdomain that points to the public directory directly. Eg https://attendize.cardiff.marketing/select_organiser

**Comment by bretto36** [comment]
I have mine set up locally using wamp. If i change my base directory for my vhost to the Attendize folder i can still use http://devattendize/public/select_organiser and it loads. 

Can you give us some information about your server environment

**Comment by bretto36** [comment]
Final possibility, normally if it's an error in the code we'd get a Laravel "Something went wrong message"

It is not seeing the htaccess file which handles routing websites - I just went to index.php (https://cardiff.marketing/attendize/public/index.php/login) and it worked. So please turn on mod_rewrite in your apache conf file

**Comment by bretto36** [comment]
Can you please let me know if that solved your issue @yhorian1

**Comment by yhorian1** [comment]
rehosted on a subdomain: https://attendize.cardiff.marketing
I've tested the rewrite mod: https://attendize.cardiff.marketing/test.php
.htaccess is in place:
RewriteRule ^(.*)$ public/$1 [L]

**Comment by daveearley** [comment]
You may have to set AllowOverride All in your Apache configuration. There's information on how to do it here: [http://stackoverflow.com/questions/18740419/how-to-set-allowoverride-all](http://stackoverflow.com/questions/18740419/how-to-set-allowoverride-all)

Let me know if that works.

**Comment by yhorian1** [comment]
Explicitly set AllowOverride All for the directory - the public page now works but no joy getting it set up.

**Comment by daveearley** [comment]
Can you run the installer at /public/install or create an account at
/public/signup?

**Comment by yhorian1** [comment]
The sign up works - but not the install. I've manually set a database but no email server just to move forward.

**Comment by yhorian1** [comment]
Also - is there no way to prevent further sign ups, if the sign up link is public?

**Comment by yhorian1** [comment]
I've now tried a full manual install with all the dependancies - still no joy in getting it to work.

**Comment by dzulhelmi** [comment]
Same problem, but on nginx here

**Comment by JapSeyz** [comment]
Could retry from fresh, and send laravel + php + nginx/apache error logs with the steps to reproduce, and where it fails exactly.

**Comment by kstefanou52** [comment]
I have same problem here. 
I have a VPN on Amazon servers running Ubuntu server.  
I tried both install methods but the result is still the same, a blank white page. 

I have change my AllowOveride settings and still something. 

Any help ?

**Comment by daveearley** [comment]
Are the folders **storage**, **public** and **bootstrap** all writable?

**Comment by bretto36** [comment]
Is anyone getting any errors in the error_logs that we can take a look at. I recently had issues with the storage folder (and child folders) not being set to 777 

running this command in the base dir solved my issues for a different laravel app
chmod -R 777 storage

**Comment by wh211212** [comment]
I couldn't get the install to work - having done the manual install and navigated to /public, I'm redirected to: https://cardiff.marketing/attendize/public/select_organiser with a 404.  this problem I hava

**Comment by aoslm** [comment]
try to run: sudo a2enmod rewrite
then sudo service apache2 restart

**Comment by RandomHeroo** [comment]
Set " AllowOverride All" in your httpd.conf file for the folder your Attendize files are located
