### ISSUE TITLE
Wrong/broken email subject for attendee emails

### ISSUE THREAD

**Issue by Fohdeesha** [Attendize/Attendize#382]
Just set up attendize (from latest code on git) and everything including signup is working great, however the emails sent to the attendee with their ticket and info has the subject line of "Controllers.tickets_for_event" - No name of the event or anything, this will make it very hard for attendees to keep track of their ticket email.

Oddly, the email sent to the event organizer has a perfectly working subject line of "New order received on the event EVENT-NAME etc etc"

picture from my email client: 
https://i.imgur.com/k0WKnLf.png

**Comment by Fohdeesha** [comment]
this is the commit that broke email subjects: https://github.com/Fohdeesha/Attendize/commit/d1ad31d253ceca563d1f3ca984a7b8b8a8372435#diff-dc0b295a2b5674b251859466a871718e

that change to the subject generation in ordermailer.php - reverting to the previous line of:
`$message->subject('Your tickets for the event ' . $order->event->title);`

fixes email subjects, they once again have the event title

**Comment by Fohdeesha** [comment]
@jmarianski

**Comment by samdb** [comment]
This commit added translations but the line specified did not exist in the translation files. Does the most recent commit work for you?

**Comment by Fohdeesha** [comment]
Hi! finally had time to check latest code. It removed the controllers.ticket line, but the name of the event is still missing (it seems to not be processing the `["event"=>$order->event->title]));` bit

example with latest commit: https://i.imgur.com/sq17RiI.png

**Comment by jmarianski** [comment]
Just added a comment to a merge commit, you can find a quick fix here:

https://github.com/Attendize/Attendize/commit/dec455c38919cc2562c8d02e951994d27f0af068#comments

**Comment by Fohdeesha** [comment]
Thanks, that worked! changed both language files and sent a commit!
