### ISSUE TITLE
Implement schema.org schema for events

### ISSUE THREAD

**Issue by midorikocak** [Attendize/Attendize#4]
Did you use schema.org schema for events? If you want I can help to implement that https://schema.org/Event I think usinf RDFa is best but you can prefer Json ld too.

**Comment by Attendize** [comment]
Hi there,

Thanks for trying it out. I haven't implemented any event schema yet, but completely open to it and would welcome any help!

Cheers

**Comment by G0dLik3** [comment]
Created a pull request for this here: #48.

**Comment by daveearley** [comment]
Cheers @G0dLik3 !

**Comment by ampliads** [comment]
> Hi there,
> 
> Thanks for trying it out. I haven't implemented any event schema yet, but completely open to it and would welcome any help!
> 
> Cheers

I have just installed Attendize and created the event, but can not see the schema. Does anyone here have any experience with Event Schema Implementation?
