### ISSUE TITLE
Survey question prevents ticket checkout

### ISSUE THREAD

**Issue by fibre** [Attendize/Attendize#404]
To recreate:
1. Use the demo site at http://attendize.website
2. Create user account
3. Create event
4. Create ticket
5. Create short-text survey question (& set as required for the ticket created).
6. Attempt registration of ticket on event page.

Outcomes:
1. The "Checkout" button changes to "Just a second..." then back to "Checkout".
2. User is stuck and unable to register a ticket.
3. In the event dashboard, the available ticket count in the demo dashboard goes down by one although there is no ticket registered.

Thank you for this software product.
I attempted to submit this bug to the email listed on the bug/feedback page but the email bounced.

**Comment by samdb** [comment]
Hi @fibre, have you tried installing the project yourself yet? The demo site is a little out of date as we've made a lot of bug fixes recently. We will get it updated as soon as we can.

Which email address is it that bounced?

**Comment by Rdhivakar** [comment]
Hi,

I am also facing this issue too. When there is a survey, I am not able to complete the registration. 

it gets stuck in check out process. The survey question is also not visible for the user. Your help is highly appreciated.
