### ISSUE TITLE
Count of remaining tickets is wrong

### ISSUE THREAD

**Issue by ajilal95** [Attendize/Attendize#409]
Suppose I have 3 type of tickets A, B and C
All of them have AVAILABLE_QUANTITY = 500

When I create an order which contains all the 3 types of tickets, the remaining tickets count in each of the ticket becomes wrong.

That is, now  **SOLD + REMAINING != AVAILABLE_QUATITIY** for all of the ticket types.

Now, if I create another order which contains only one kind of the ticket(Say B), then the remaining tickets count of other ticket types(A and C here) gets corrected(B is still wrong).

**Comment by jeremyquinton** [comment]
@ajilal95 did you manage to fix the bug happy to accept a PR for it.
