### ISSUE TITLE
ideal payments

### ISSUE THREAD

**Issue by Flexa** [Attendize/Attendize#412]
Hello,
Did somebody already made a payment gateway with Mollie?
Or can someone build one for me for a reasonable price?

Cheers

**Comment by Flexa** [comment]
I made a connection with stripe only the creditcard payment is showing up. Anyone has the solution for showing more payments ?

**Comment by jeremyquinton** [comment]
@Flexa on your first question you can look at this implementation which implements a dummy payment gateway for Attendize but you could do something similar for Mollie.  https://github.com/Attendize/Attendize/commit/3b4e3fdc0de3128d62d0a4ba889de50804928ade
 
@Flexa to my knowledge I think you can only use one payment gateway at a time based on the understanding of the codebase I have in my head. Which be a useful feature to add.

**Comment by Flexa** [comment]
@jeremyquinton Thank you for your update. Would be nice to have multiple payments methods active :).
I added most of the current methods and now get errors with checkout. Need to this one out =]

**Comment by Flexa** [comment]
keep getting this error at checkout: Whoops!, it looks like the server returned an error. Please try again, or contact the webmaster if the problem persists.

Also with a fresh install

**Comment by jeremyquinton** [comment]
@Flexa check your webservers error log to see the actual error message. 

In the application folder
chmod -R a+w storage
chmod -R a+w public/user_content 

might fix it.

**Comment by Flexa** [comment]
Cheers, but we got it fixed ;)
