### ISSUE TITLE
Questions about features and functionality

### ISSUE THREAD

**Issue by emergingdzns** [Attendize/Attendize#413]
I couldn't find a contact function on the main site so this was the only way I could figure out how to ask these questions. I tried the demo as well but I'm not seeing some of thing others are referring to in the github issues, so I want to clarify. Thank you!

1. Is there the ability to set maximum number of tickets total for any given event?
2. Is it possible to have 2 different variants of tickets? Example standard ticket versus VIP ticket? (and be able to limit how many of each are available)?
3. Is it possible to set a max to how many tickets one person can purchase/reserve?
4. How does the system handle dealing with multiple people checking out at once. For example if you use Fandango to purchase 4 movie tickets, it will "lock" out 4 seats for you for up to 6 minutes to allow you time to complete the purchase. This way, if there are only say 6 seats left and you choose 4 seats, then the next person that comes in could not possibly purchase more than 2 tickets before you finish unless your session times out. We need to be able to avoid over-selling events.
5. How hard is it to code in a new payment processor? My client is with First Data and have been for many years. They aren't about to change, so I need to work with their system. Does Attendize utilize Laravel Cashier?

**Comment by jeremyquinton** [comment]
@emergingdzns To answer your questions

1. Yes.
2. Yes.
3. The short answer is Yes. You can can set the minimum and maximum tickets per order for a particular ticket type.  
4. The functionality you describe exists in Attendize except session timeout is set to 30 minutes. I'm not sure if this is configurable. 
5. Attendize uses the Ominpay library. https://github.com/thephpleague/omnipay. Omnipay supports First Data. Adding a new payment gateway is relatively straightforward once. You can look at the dummy payment gateway implementation as an example. https://github.com/Attendize/Attendize/tree/dummy-payment-gateway

**Comment by emergingdzns** [comment]
Awesome Thanks!!!!

**Comment by emergingdzns** [comment]
Ok so I've installed Attendize on a domain. I've got through and I'm able to log in and create events. However, there's no mention of setting prices, levels, maximum number of tickets etc. Are there plugins or something that I'm missing? Configuration somewhere? I can't find anything in the documentation.

**Comment by emergingdzns** [comment]
Disregard. I see I needed to create tickets for the event. I thought that was a list of tickets purchased. Duh. Sorry.
