### ISSUE TITLE
Incorrect month displayed in Event List

### ISSUE THREAD

**Issue by scottybo** [Attendize/Attendize#414]
In `resources/views/ManageOrganiser/Partials/EventPanel.blade.php` on line 5 we have the following:

`{{strtoupper(explode("|", trans("basic.months_short"))[$event->start_date->format('n')])}}`

`basic.months_short` is an array of the months, but format('n') returns the month number. So January is returned as 1 but the array starts at 0, so instead of showing "Jan" we're shown "Feb".

To fix this, we need to subtract 1 from the start date month:

`{{strtoupper(explode("|", trans("basic.months_short"))[$event->start_date->format('n')-1])}}`

And to the inevitable "can you do a pull request" question, sorry, no I can't as I'm working on a codebase which is modified ;)

**Comment by jeremyquinton** [comment]
@scottybo thanks for reporting will try look at this soon
