### ISSUE TITLE
Payment failure in gateway with omnipay

### ISSUE THREAD

**Issue by emergingdzns** [Attendize/Attendize#419]
I've got my Payeezy gateway added in and everything up to the point of submitting the payment is working. However, when the payment is submitted I am getting this error:

CurlException in CurlMulti.php line 359:
[curl] 60: SSL certificate problem: self signed certificate in certificate chain [url] https://api-cert.payeezy.com/v1/transactions

I am using a valid SSL cert and Payeezy's SSL cert is also valid. I don't know how to fix this. Seems there's some validation that isn't working right.

If you want the full stacktrace you can see it here: http://jsbin.com/xidapivojo/edit?html

Any help would be greatly appreciated.

**Comment by jeremyquinton** [comment]
@emergingdzns googling your error seems like its an issue with the payment provider. I found this thread which might help https://github.com/guzzle/guzzle/issues/394. 

I don't think this is Attendize specific. If you go your implementation working could you please close this ticket.
