### ISSUE TITLE
Inconsistencies between BitPay/Coinbase constants

### ISSUE THREAD

**Issue by ethode** [Attendize/Attendize#426]
In attendize.php config and backed settings there's references to both bitpay and coinbase for payment gateway options, but when looking in code the constants and numeric assignments look to have been changed over at once point as 3 references bitpay and also coinbase in the same config file

**Comment by jeremyquinton** [comment]
Thanks for reporting this. In the latest version we have removed support for Migs and Coinbase. I have also made some changes to remove the incorrect references to the Coinbase and Migs which I will merge in the coming days.

**Comment by ethode** [comment]
Thanks Jeremy, we have a fork currently to get BitPay working again, does this collide with any other on-going work that we should know about?  If not, when we're done and tested we will do a pull request and update the main readme

**Comment by jeremyquinton** [comment]
@ethode master of Attendize and release 1.1 only have support for Stripe and Paypal by default. https://github.com/Attendize/Attendize/releases/tag/v1.1.0 

If you want to make to continue to use bitpay use the laravel-5.2 branch. Full Docs coming soon. https://github.com/Attendize/Attendize/tree/laravel-5.2. That branch will receive bug fixes but no major new features.

**Comment by jeremyquinton** [comment]
@ethode this has been fixed in master so closing this off.
