### ISSUE TITLE
[feature] Ticket packs

### ISSUE THREAD

**Issue by mvanderkruk** [Attendize/Attendize#427]
We are missing a feature in the system: purchase multiple tickets in a pack.
For example an event has 2 days. Tickets are only valid for one of the days and buying a pack for both days is cheaper than both days separate.
Example: 
- Saturday is 25
- Sunday is 25
- Weekend ticket is 40 and consists of 1 Saturday and 1 Sunday ticket.

**Comment by samdb** [comment]
We achieve this ourselves using a third ticket type (see phpconference.co.uk/tickets for an example). This isn’t something we will be building into the core project.

**Comment by mvanderkruk** [comment]
If you use this way, the persons responsible for scanning the visitors will MANUALLY have to verify ticket validity..... this is something you would not let a human do, because they make mistakes.......
