### ISSUE TITLE
Share buttons on event dashboard

### ISSUE THREAD

**Issue by markwalet** [Attendize/Attendize#43]
My html5 validator gives an error on the share button on the event dashboard, that's how I discovered this issue.
Spaces aren't allowed in url's. But when you look to the actual output, you see that the whole description is being used (with markup syntax)
Simple solution: Make social media fields for the event. In this way you can create a custom message for e.g. Facebook or Twitter (max 140 characters).
Solution number 2: Do some magic to format the description properly.

I prefer solution 1. If you want I could implement this in the coming days.

**Comment by daveearley** [comment]
I'd go with option 1. There's actually already a 'social_share_text' column in the events table. I had the option to have custom share text and removed it (I can't remember why though). The textarea is still on the event social settings page, just hidden.
