### ISSUE TITLE
Bad indexing to months_short

### ISSUE THREAD

**Issue by jhheider** [Attendize/Attendize#434]
Passing 1-origin month numbers to a 0-origin index of month names produces an off-by-one error.

```
resources/views/ManageOrganiser/Partials/EventPanel.blade.php
5:                {{strtoupper(explode("|", trans("basic.months_short"))[$event->start_date->format('n')])}}

resources/lang/en/basic.php
33:  'months_short' => 'Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec',
```

Two fixes are possible. One is changing basic.php to read:
```
33:  'months_short' => '|Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec',
```
(tested working)

Or changing EventPanel.blade.php (and EventListingPanel.blade.php) to
```
5:                {{strtoupper($event->start_date->format('M'))}}
```
which should work, but I didn't waste time testing.

**Comment by jeremyquinton** [comment]
@jhheider this has been fixed in master
