### ISSUE TITLE
Emails not coming

### ISSUE THREAD

**Issue by netart91** [Attendize/Attendize#436]
After press "Checkout" it's showing success page but email with tickets is not coming

**Comment by jeremyquinton** [comment]
@netart91 are you using the latest version of Attendize? Are you using the docker install?

**Comment by netart91** [comment]
I've downloaded it from the official site

**Comment by heilgar** [comment]
Try SMTP and mailgun, its works fine for me. On clean docker setup mail won't works, don know why

**Comment by netart91** [comment]
Actually, I managed to get it to work by setting MAIL_FROM_ADDRESS constant to NULL
But how to be without sender information?

**Comment by netart91** [comment]
Thank's!! SMTP worked for me

**Comment by jeremyquinton** [comment]
@heilgar if you are using the docker version if you browse to http://localhost:1080 you should see all the emails that get sent by Attendize.

**Comment by heilgar** [comment]
Thx @jeremyquinton
