### ISSUE TITLE
Whoops, looks like something went wrong.

### ISSUE THREAD

**Issue by adesoye0** [Attendize/Attendize#437]
Good day. I got the above error while trying to install the script sir. Please is there anything I can do or you can do to resolve this error? Thanks.

Whoops, looks like something went wrong.

**Comment by jeremyquinton** [comment]
@adesoye0  The error will be contained in the log file. In the root directory in storage/logs

![screen shot 2018-08-28 at 20 45 45](https://user-images.githubusercontent.com/1847770/44743657-5f7bca80-ab03-11e8-8d83-7443cfbbbf27.png)

**Comment by adesoye0** [comment]
Thanks for your RESPONSE sir. But sir, I already checked it since and I found no error there. 
This is what I see when I check the file there 
[ *
!.gitignore ]
Please if there anything you can do to help me, I will forever be gracious sir. And I won't mind if I can give you my cPanel login access so you can see for yourself and rectify it sir. Thank you sir,

**Comment by jeremyquinton** [comment]
@adesoye0 Please try the steps in the troubleshooting guide to see if they help. 

https://github.com/Attendize/Attendize#troubleshooting

**Comment by jeremyquinton** [comment]
@adesoye0 Attendize is a platform where you can be the organiser and create events. It currently doesn't have the functionality to allow people to sign up and create events. As the organiser you can create other organisers who will get an invite email and can create events. 

1) You can create an organiser. An organiser can create other organisers.  
2) An organiser can create events from the admin section.   
3) An organiser can create tickets for an event from the admin section. 

I suggest browsing the admin panel to see what Attendize can and can't do and the functionality it has. 

Please see the new documentation website for more information. http://www.attendize.com/
