### ISSUE TITLE
error when run project

### ISSUE THREAD

**Issue by iosandroidwebtopdev** [Attendize/Attendize#440]
![screen shot 2018-08-29 at 10 22 32 pm](https://user-images.githubusercontent.com/15466829/44787325-2a8e7700-abda-11e8-9387-fdb9b286e477.png)

I installed docker and run docker-compose up -d
I got error in http://localhost:8000 of browser, pls check screenshot.

**Comment by jeremyquinton** [comment]
Please take a look at the troubleshooting guide.

https://github.com/Attendize/Attendize#troubleshooting

**Comment by jeremyquinton** [comment]
A new documentation website has been launched 

Please see the troubleshooting guide http://www.attendize.com/troubleshooting.html to help you debug your installation. 

Please see manual installation instructions here http://www.attendize.com/getting_started.html#manual-installation

Please see docker installation instructions here 
http://www.attendize.com/getting_started.html#running-attendize-in-docker-for-development
