### ISSUE TITLE
error when set database

### ISSUE THREAD

**Issue by fullstackdeveloper90** [Attendize/Attendize#441]
I built project successfully.
I got setting page for database.
After set, I can't open page.

**Comment by jeremyquinton** [comment]
Please take a look at the troubleshooting guide https://github.com/Attendize/Attendize#troubleshooting

and the manual install instructions
https://github.com/Attendize/Attendize#manual-installation

**Comment by jeremyquinton** [comment]
A new documentation website has been launched 

Please see the troubleshooting guide http://www.attendize.com/troubleshooting.html to help you debug your installation. 

Please see manual installation instructions here http://www.attendize.com/getting_started.html#manual-installation

Please see docker installation instructions here 
http://www.attendize.com/getting_started.html#running-attendize-in-docker-for-development
