### ISSUE TITLE
Logic of generating QR and 2D codes

### ISSUE THREAD

**Issue by heilgar** [Attendize/Attendize#443]
Hi, I interested in place where I can see logic of generating Qr and 2d code or could somebody describe how i can get user data by that codes.

For example: 
- I wrote api resource with get action 
- I sent scanned data to resource described above
- I want get form data by that code ?

I will be very appreciated for any help.

**Comment by heilgar** [comment]
I have software for printing badges and for now can't find logic of generating of qr or 2d codes

**Comment by heilgar** [comment]
anybody?

**Comment by publicarray** [comment]
Is https://github.com/milon/barcode what you are after? Please use your favourite search engine.

**Comment by jeremyquinton** [comment]
@heilgar as @publicarray mention this is the library you are most likely after https://github.com/milon/barcode.

Closing this off as its not an issue
