### ISSUE TITLE
Date set and shown are different

### ISSUE THREAD

**Issue by rkhyd** [Attendize/Attendize#450]
I have set the event date for September month and on the front end it shows up as in October!!!
please fix this issue.

![backend](https://user-images.githubusercontent.com/15903310/45016578-b40ed080-b042-11e8-9b11-7a597bea49a8.jpg)
![frontend](https://user-images.githubusercontent.com/15903310/45016580-b40ed080-b042-11e8-9f80-cf90756dbff0.jpg)

**Comment by scottybo** [comment]
See #414

**Comment by rkhyd** [comment]
I have changed the code and also cleared the cache and views. The behavior still persists.

**Comment by jeremyquinton** [comment]
@scottybo @rkhyd this has been fixed. Merged to master.
