### ISSUE TITLE
Fopen

### ISSUE THREAD

**Issue by nickzasa** [Attendize/Attendize#454]
Good Day guys and girls,

So I have enabled the allow_url_fopen but when I run composer install it gives me an error saying that allow_url_fopen =0 and needs to be enabled.

The other thing is the installer page does not show up.

Any help or ideas would be much appreciated.

Kind Regards,
Nicholas Lefebvre

**Comment by samdb** [comment]
This is a composer error, have you run "composer diagnose"?

**Comment by nickzasa** [comment]
okay so when I run composer install it gives the following error:

Package phpoffice/phpexcel is abandoned, you should avoid using it, Use phpoffice/phpspreadsheet instead.

**Comment by nickzasa** [comment]
[cyberuit@sarge Attendize]$ composer diagnose
Checking composer.json: FAIL
License "Attribution Assurance License" is not a valid SPDX license identifier, see https://spdx.org/licenses/ if you use an open license.
If the software is closed-source, you may use "proprietary" as license.
require.guzzlehttp/guzzle : exact version constraints (6) should be avoided if the package follows semantic versioning
require.guzzlehttp/psr7 : exact version constraints (1.4) should be avoided if the package follows semantic versioning
require.maxhoffmann/parsedown-laravel : unbound version constraints (dev-master) should be avoided
require.nitmedia/wkhtml2pdf : unbound version constraints (dev-master) should be avoided
Checking platform settings: FAIL

The allow_url_fopen setting is incorrect.
Add the following to the end of your `php.ini`:
    allow_url_fopen = On



The php.ini used by your command-line PHP is: /opt/cpanel/ea-php56/root/etc/php.ini
If you can not modify the ini file, you can also run `php -d option=value` to modify ini values on the fly. You can use -d multiple times.

Checking git settings: OK
Checking http connectivity to packagist: Warning: Accessing packagist.org over http which is an insecure protocol.
FAIL
[Composer\Downloader\TransportException] The "http://packagist.org/packages.json" file could not be downloaded: allow_url_fopen must be enabled in php.ini (http:// wrapper is disabled in the server configuration by allow_url_fopen=0
failed to open stream: no suitable wrapper could be found)
Checking https connectivity to packagist: FAIL
[Composer\Downloader\TransportException] The "https://packagist.org/packages.json" file could not be downloaded: allow_url_fopen must be enabled in php.ini (https:// wrapper is disabled in the server configuration by allow_url_fopen=0
failed to open stream: no suitable wrapper could be found)
Checking github.com rate limit: FAIL
[Composer\Downloader\TransportException] The "https://api.github.com/rate_limit" file could not be downloaded: allow_url_fopen must be enabled in php.ini (https:// wrapper is disabled in the server configuration by allow_url_fopen=0
failed to open stream: no suitable wrapper could be found)
Checking disk free space: OK
Checking pubkeys: FAIL
Missing pubkey for tags verification
Missing pubkey for dev verification
Run composer self-update --update-keys to set them up
Checking composer version:

  [Composer\Downloader\TransportException]
  The "https://getcomposer.org/versions" file could not be downloaded: allow_url_fopen must be enabled in php.ini (https:// wrapper is disabled in the ser
  ver configuration by allow_url_fopen=0
  failed to open stream: no suitable wrapper could be found)


diagnose

**Comment by samdb** [comment]
I have just corrected the licence line so that will now disappear but Composer diagnose is telling you fopen still isn't correctly configured. You will need that sorted in your PHP installation to progress any further. It might be worth asking your CPanel host for some help with that.

**Comment by nickzasa** [comment]
I have asked them to and when I look php.ini it is allowed

**Comment by samdb** [comment]
If you read through the composer diagnose output you will see

> The php.ini used by your command-line PHP is: /opt/cpanel/ea-php56/root/etc/php.ini

This is the php.ini file that composer is using. Until fopen is corrected there it won't work.

You could try running composer with

> php -n -c /path/to/my/edited/php.ini composer install

**Comment by nickzasa** [comment]
Problem 1
    - symfony/var-dumper v4.1.4 requires php ^7.1.3 -> your PHP version (5.6.37) does not satisfy that requirement.
    - symfony/var-dumper v4.1.4 requires php ^7.1.3 -> your PHP version (5.6.37) does not satisfy that requirement.
    - Installation request for symfony/var-dumper v4.1.4 -> satisfiable by symfony/var-dumper[v4.1.4].
 
Am I correct  that by upgrading to 7.1.3 it will resolve the issue

**Comment by samdb** [comment]
That is correct. If you check out the Readme it will point you to the installation guide where you will find a note explaining which version of Attendize to use, depending on your PHP version.

**Comment by samdb** [comment]
You could try taking this up with the Composer developers as we are only able to help debug errors with the Attendize software itself.

**Comment by jeremyquinton** [comment]
@nickzasa @samdb as this is not an Attendize issue.
