### ISSUE TITLE
Add payfast as payment gateway

### ISSUE THREAD

**Issue by nickzasa** [Attendize/Attendize#456]
How do I add payfast as a payment gateway to Attendize

**Comment by jeremyquinton** [comment]
Hi @nickzasa. A full comprehensive guide will be launched in the coming months. 

https://www.attendize.com/payment_gateways.html has some more information. You will need to use the https://github.com/Attendize/Attendize/tree/laravel-5.2 most likely. 

If you have programming experience you can look at this implementation of a dummy payment gateway https://github.com/Attendize/Attendize/pull/398/files to see how to implement a payment gateway in general.

**Comment by waqasraza123** [comment]
@jeremyquinton any update on this?
