### ISSUE TITLE
App Suggestion

### ISSUE THREAD

**Issue by kennedyrs** [Attendize/Attendize#47]
Maybe put a validation ticket in the application is a good idea . For the tickets be validated at the event entrance.

**Comment by bretto36** [comment]
Hi, can you elaborate a little more on what you are suggesting. 

There is an area of the app already in devlopment for checking attendees in. You get their ticket, type in the number of find their name and then mark them as checked in. It's at this url yourdomain.com/event/3/check_in where 3 is the event id. 

Are you suggesting something like that? or am i missing it

**Comment by kennedyrs** [comment]
I was talking about the validation with the Mobile app, but I saw, it's already at the plan.
