### ISSUE TITLE
Exception when trying to reset password

### ISSUE THREAD

**Issue by error17191** [Attendize/Attendize#470]
When I try to reset password the following exception gets thrown
 
BadMethodCallException
Call to undefined method App\Models\User::notify()

**Comment by jeremyquinton** [comment]
@error17191 did you get this error on the master branch of attendize?

**Comment by error17191** [comment]
> @error17191 did you get this error on the master branch of attendize?

Yes

**Comment by jeremyquinton** [comment]
@error17191 this is fixed in #481 thanks for reporting 👍
