### ISSUE TITLE
Request: When QR reader is attempted to be loaded without SSL, recommend the user switch to the SSL (https) version of the page

### ISSUE THREAD

**Issue by fortepc** [Attendize/Attendize#482]
This would alleviate some issues of users using chrome where the browser doesn't even ask permission for the camera if you're not on an https page.

It would also just be a good thing overall to encourage the user to protect their privacy.

**Comment by githubertus** [comment]
Running a shop like this over http should be impossible from the very beginning anyway. Thus, adding a rewrite rule to .htaccess instead would be a much better solution to my opinion.

**Comment by johannac** [comment]
Thank you for your feedback. We don't plan to implement any non-SSL features for Attendize. As the previous comment states, the best option for improving the situation you're experiencing is to put an automatic redirect in your HTTP server config to send requests from HTTP to HTTPS.
