### ISSUE TITLE
German Translation

### ISSUE THREAD

**Issue by Modding** [Attendize/Attendize#489]
Is it possible to provide my german Translation to your Repository?

Greetings

Valentin

**Comment by ftbastler** [comment]
Sure thing!

**Comment by jeremyquinton** [comment]
I will be happy to merge this once its completed.

**Comment by devxpoint** [comment]
Hi Valentin,

where can I find your German translation?

Cheers 
André

**Comment by johannac** [comment]
The German translations from #491 have just been merged and will be tagged in a release on June 1st.
