### ISSUE TITLE
Unable to register for a ticket both free or paid

### ISSUE THREAD

**Issue by Deassismoneira** [Attendize/Attendize#498]
Whoops!, it looks like the server returned an error. Please try again, or contact the webmaster if the problem persists.

**Comment by jeremyquinton** [comment]
@Deassismoneira please read the troubleshooting guide https://www.attendize.com/troubleshooting.html. If you manage to fix your problem please close this issue thanks!

**Comment by johannac** [comment]
This ticket is being closed due to receiving no further response from the original author.
