### ISSUE TITLE
WKHTMLTOPDF didn't return any data

### ISSUE THREAD

**Issue by chinel** [Attendize/Attendize#499]
I get this in my log file after i try to send a user a ticket. 
I made my research i in the wkhtmltopdf/wkhtmltopdf.php file i removed
   `     $command = $this->_getCommand($input);

        $content = $this->_pipeExec($command);

        if($this->config->get('debug'))
        {
            dump(array(
                'input' => $input,
                'command' => $command,
                'content' => $content
            ));
        }

        if(preg_match('/error(?! ignored)/i', $content['stderr']))
		throw new Exception("System error <pre>" . $content['stderr'] . "</pre>");

        if (strlen($content['stdout']) === 0)
            throw new Exception("WKHTMLTOPDF didn't return any data");

        $data = $content['stdout'];`
and  returned input instead of data.

which sent an empty pdf file. So i reversed it and it still sends an empty pdf file.

Please has anyone encounter or has a solution to this DID NOT RETURN ANY DATA ERROR

**Comment by maxymevs** [comment]
Hi

I had the same problem last night, you need to change permissions on the entire directory

if you host Attendize on your personal server try this command
`chmod -R 777 /vendor/nitmedia/wkhtml2pdf/src/Nitmedia/Wkhtml2pdf/*`

**Comment by chinel** [comment]
thanks apart from changing the permissions of the directory. I moved from shared hosting to VPS before it finally worked
