### ISSUE TITLE
Charts on Event Dashboard

### ISSUE THREAD

**Issue by pccolella** [Attendize/Attendize#501]
Chart dates are off by 1 month - javascript months are 0-11. :)

**Comment by jeremyquinton** [comment]
@pccolella what version of attendize are you using as this bug I think has been fixed. Can you perhaps attach a screenshot?

**Comment by pccolella** [comment]
I downloaded the master just today -- just seeing if this project would be a good fit for a local theatre company. Sorry no screen shot as I fixed my local copy already. Dashboard.blade.php

function formatDate(x) {
            var m_names = <?=json_encode(explode("|", trans("basic.months_short")))?>;
            var sup = "",
                    curr_date = x.getDate();
            <?php if(Lang::locale()=="en") { ?>
            if (curr_date == 1 || curr_date == 21 || curr_date == 31) {
                sup = "st";
            }
            else if (curr_date == 2 || curr_date == 22) {
                sup = "nd";
            }
            else if (curr_date == 3 || curr_date == 23) {
                sup = "rd";
            }
            else {
                sup = "th";
            }
            <?php } ?>
            /*  {{Lang::locale()}} */

            return curr_date + sup + ' ' + m_names[x.getMonth()+1];
        }
