### ISSUE TITLE
PHP 7.2.10 compatibility error with Laravel - Checkout Not Working (WORKAROUND INCLUDED)

### ISSUE THREAD

**Issue by ScottCrumpler** [Attendize/Attendize#504]
Checkout was returning this error in the log:

production.ERROR: count(): Parameter must be an array or an object that implements Countable {"exception":"[object] (ErrorException(code: 0): count(): Parameter must be an array or an object that implements Countable at /[my path]/app/Http/Controllers/EventCheckoutController.php:196)

I found some posts from other people with this issue with Laravel and PHP 7.2 where they confirmed it's a compatibility problem.  I added this code at line 29 of EventCheckoutController.php:

`if (version_compare(PHP_VERSION, '7.2.0', '>=')) {
    // Ignores notices and reports all other kinds... and warnings
    error_reporting(E_ALL ^ E_NOTICE ^ E_WARNING);
    // error_reporting(E_ALL ^ E_WARNING); // Maybe this is enough
}`

and this allows checkout to work properly, but, obviously, this is not a solution.  The installation documentation should be updated to note that Attendize is not compatible with PHP 7.2 until this is fixed somehow.

**Comment by ScottCrumpler** [comment]
@jeremyquinton - Thanks for the follow-up!  No, you're right - I installed using the release download.

**Comment by jeremyquinton** [comment]
got my numbers mixed up the PR above fixes #469 469
