### ISSUE TITLE
Getting an error while generating an key by 'php artisan key:generate' command

### ISSUE THREAD

**Issue by bdavid68** [Attendize/Attendize#505]
I am trying to run this repo on my Ubuntu EC2 instance. But I am getting an error while running the command to generate key.
Actually, there is a file name as `artisan` in `/Attendize` directory.
I am not sure what's going on. Any help would be appreciate!

```php
PHP Warning:  require(/var/www/Attendize/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/Attendize/artisan on line 18
PHP Fatal error:  require(): Failed opening required '/var/www/Attendize/vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/Attendize/artisan on line 18
```

**Comment by jeremyquinton** [comment]
@bdavid68 have you had a look at the https://www.attendize.com/getting_started.html#manual-installation guide? 

Looks like you perhaps have not run composer first as the artisan file is referencing the vendor/autoload.php which does not exist.

If you managed to resolve your problem please close the issue.

**Comment by jeremyquinton** [comment]
@bdavid68 do you have any feedback? If you manage to solve your problem please close this issue.

**Comment by johannac** [comment]
This ticket is being closed due to receiving no further response from the original author.
