### ISSUE TITLE
Model Structure to allow for more flexibility in Events and Tickets

### ISSUE THREAD

**Issue by RPillz** [Attendize/Attendize#507]
Hello, I'm a new convert to Laravel and looking to retrace my steps on a ticket system I have been developing over the last few years. Attendize looks like a great project and I'd love to get on board with this system.

I noticed that there is an integral aspect of the Model structure that limits the versatility of the Events and Tickets. **Currently Attendize is organized like this:**

- **Event** (with a specific date/time)
  - **Ticket** (with a quantity available)

While I understand this is a fundamental change, **I would recommend turning these two into four separate Models:**

- **Event** (the branding and description only)
  - **Show** (specific date/time and venue)
    - **Inventory** (the number of saleable seats in the venue or section)
      - **Ticket** (a set price for a seat)

This allows for a few great things to happen:

1. You can have an event with multiple "shows", ie: The 8 PM show and the 10 PM show.
2. A "festival" style event with a collection of unique shows within it.
3. Separating the inventory from the ticket allows you to have multiple tickets drawing from the same pool of seats, ie: Adult and Child admissions... different price but they both take one of the same group of seats.
4. You can also have multiple inventories for a show, allowing you to have a "VIP section" that only has 10 seats, while the general inventory has 100.

I'll be looking at implementing this myself, and happy to share my progress.

**Comment by RPillz** [comment]
I see that a Venue model should probably be created as part of this as well, as it's currently part of the Event.

That would lay the groundwork on #406

**Comment by jeremyquinton** [comment]
@RPillz The changes you have suggested make perfect sense and would certainly cater for a lot more scenarios. 

The core idea however behind Attendize is a simple solution to manage general admission for events e.g. things like conferences, one off events where a simple ticketing system is needed at the door.  

It wasn't originally intended for theatres or festivals or events that have a specific seating arrangements with different ticket prices for different seats and different setups.

**Comment by justynpride** [comment]
@RPillz Just wondering what you did to solve your problem? Did you build something separately? I like the logic that you proposed.
