### ISSUE TITLE
Stuck at We'll be back soon screen

### ISSUE THREAD

**Issue by knireis** [Attendize/Attendize#513]
I have an issue installing Attendize. All items in the install screen are green, the database test gives OK. But after selecting the install button i get stuck on the 'we'll be back soon screen'. Refreshing the window brings me back to the install screen. There is nothing in the laravel.log or the nginx error.log.

I installed on ubuntu 18.04

**Comment by jeremyquinton** [comment]
Take a look at the troubleshooting guide 
https://www.attendize.com/troubleshooting.html

APP_DEBUG=true

should give you something in the error log.

**Comment by MonsterfulVR** [comment]
getting the same thing via docker
app_debug = true 
showing nothing

**Comment by jeremyquinton** [comment]
@MonsterfulVR 

the case is important APP_DEBUG=true.

there should be an error message in your_app_directory/storage/logs provided you have set permissions correctly.

**Comment by MonsterfulVR** [comment]
Yea i am getting nothing there and every thing is writeable.
i checked source, and data base not seen that message anywhere wondering if it's nginx or system

**Comment by jeremyquinton** [comment]
@MonsterfulVR I need to update the bug reporting guidelines.

Depending on your nginx configuration 
```/var/log/nginx/error.log```
should have something in it. 

Also might be a log file with a name similar to php7.1-fpm.log or  php7.1-fpm-error.log depending on config. 

Can you give me your version of PHP, Webserver and operating system?

**Comment by NanneHuiges** [comment]
The permission topic in the troubleshooting guide is missing a file: after installation the `InstallationController` tries to write a file called `installed` to the root. But there is no write access there if you're using the simple docker setup.

I fixed that specific error (unsure if that's the one @knireis has) by manually making that file after trying to run the installer, but that's not a solid sollution. You can't pre-create the file, as the controller will return a 404 if it allready exists.

**Comment by johannac** [comment]
Thank you both for your reports. This bug will be fixed via https://github.com/Attendize/Attendize/issues/786
