### ISSUE TITLE
Feedback/bug report url is broken on http://attendize.website/

### ISSUE THREAD

**Issue by bagage** [Attendize/Attendize#519]
On http://attendize.website/organiser/ you have in top right menu an item feedback/bug report:

![image](https://user-images.githubusercontent.com/1451988/48514734-59be9700-e85f-11e8-9a72-fa763fea4dc9.png)

But it redirects to a 404 not found page https://www.attendize.com/feedback.php?v=1.0.0

**Comment by jeremyquinton** [comment]
@bagage thanks for reporting @ghoeffner thanks for fixing.
