### ISSUE TITLE
Allow "offline methods" payment only

### ISSUE THREAD

**Issue by bagage** [Attendize/Attendize#523]
I'd like to setup Attendize for an event with offline payment only (no Paypal or bank account available).

Is it something already possible? If not, are you open to it (eg. if I do a merge request, will it be merged?).

Thanks!

**Comment by bagage** [comment]
Yes @jeremyquinton I found that option which is nice, but it only enables offline payment. You can still pay online, which I personally would like to disable (because of #530, I have no payment gateway available). For instance list of online payments are displayed:

![image](https://user-images.githubusercontent.com/1451988/49332734-c1d8e100-f5b2-11e8-9005-4f70b0867b16.png)

I personally would like to disable online payments totally. Do you think an option for that could be added? I can do the MR I believe for it but I just want to make sure that it would be accepted upstream first.

**Comment by Purushoth-53** [comment]
use dummy payment gateway
'enable_dummy_payment_gateway'  => true in attendize config
