### ISSUE TITLE
Ticket functionality should be optional

### ISSUE THREAD

**Issue by terolahtinen** [Attendize/Attendize#525]
Most events are not ticket based, such as business meetings, conferences, social gatherings, etc. 

Attendize should have an optional mode, where it does not generate tickets, but only takes in registrations. Admission is based on attendee lists.

**Comment by jeremyquinton** [comment]
@terolahtinen The main problem Attendize solves is to be event selling ticket platform. If you require a registration system Attendize is not the software to use. 

Unfortunately we cannot cover all use cases.
