### ISSUE TITLE
Issue in Installing Attendize

### ISSUE THREAD

**Issue by AnjuP92** [Attendize/Attendize#527]
Hi,
I was trying to install Attendize on my machine. I followed the manual installation steps given in the site https://www.attendize.com/getting_started.html
In the step 7, when I tried to navigate to http://Attendize/install, it showed 404 Not found.So I tried to install that through command-line php artisan attendize:install. In the command line, it showed Success. Tables are also generated in the database.
![attendize](https://user-images.githubusercontent.com/35358592/48932349-6ad36c00-ef21-11e8-85fd-b0deecf514ac.png)

When I tried to access the site in browser http://Attendize (Attendize is the folder name of the project saved in var/www/), it is showing "This Site can’t be reached". 
I am not sure how to access the project in browser.  
Following is the folder structure:
![attendize2](https://user-images.githubusercontent.com/35358592/48932329-49728000-ef21-11e8-8395-a0d7990cc712.png)

**Comment by D3vStAr** [comment]
Have did you run php artisan serve from the folder? Or have you set up the virtual hosts on apache?
Id suggest you browse to the /var/www/attendize folder form terminal then run php artisan serve then visit localhost:8000 on your pc

**Comment by AnjuP92** [comment]
Yes, It worked for me. Thanks a lot.
