### ISSUE TITLE
Attendance Certificate Feature?

### ISSUE THREAD

**Issue by kerti** [Attendize/Attendize#535]
Hi,

I was wondering if there are any plans to implement an attendance certificate feature. This would come in handy for academic events (conferences, seminars, etc.). The details could be as follows:

* The event organizer could upload a certificate template with room for the guest's name. Attendize could then generate JPEGs/PDFs based on that template.
* A certificate can only be generated if the guest actually checked in on the event.
* Certificate distribution may have the following channels:
  * Attending guests can have the certificates emailed to them
  * Attending guests can have links to download the certificates emailed to them
  * Attending guests can visit the event page to retrieve their certificate by entering their email and/or order ref. after the event has ended

I think Attendize already has a great feature set to support academic events (minus the attendance certificate). I also appreciate the work done thus far, and hopefully this idea can make Attendize even better.

Thanks!

**Comment by samdb** [comment]
Hi Kerti,

There are no plans to add this kind of feature to the core platform. As this is not essential to ticket sales it is something we would leave to an external system or plugin. For example, if I wanted to do this I would export my attendee data to CSV and run a mail merge on a certificate template in Word, InDesign or something similar.

Sam

**Comment by shashikanth171** [comment]
Hi Sam,

I just came to the repo to find if I can reqeust for the same feature Kerti explained.

I understand that this feature is not essential to ticket sales. But it is an integral part of event management of all academic and also other events where certificate of participation is needed. 

I think event management includes post event work which can be as simple as sending a thank you note. Maybe this feature can be thought of as sending a personalized card to attendees (via email) just like sending a ticket before the event. Maybe both sending tickets and sending cards can use same functionality (setting custom templates? for personalized emails). Organizers can use this feature to send a thank you note or a certificate or invitation for later events (engaging the audience).

Thanks!
Shashikanth
