### ISSUE TITLE
Tickets start_sale_date / end_sale_date defaults to null

### ISSUE THREAD

**Issue by MostafaAttia** [Attendize/Attendize#536]
When creating a new ticket, I'm not able to create a ticket without expanding "more options" and specify a date manually, it was working before that I can create it without even expanding the "more options" button.

The request looks like this: 

```
[
  "_token" => "rNb3yBx2EG3gNtpQVcuorcjqGMbbAzQ9qYcl8QXl"
  "title" => "General Admission"
  "price" => "0"
  "quantity_available" => "100"
  "description" => null
  "start_sale_date" => null
  "end_sale_date" => null
  "min_per_person" => "1"
  "max_per_person" => "30"
]
```

What may cause this problem?

**Comment by jeremyquinton** [comment]
@MostafaAttia please see my comment on #543. Your configuration file might be missing some config options.

**Comment by MostafaAttia** [comment]
@jeremyquinton thanks for your reply, I saw your comment on #543 but it's not the case for me, when `"start_sale_date" => ''` it works but with `"start_sale_date" => null` is not working!

I can't find a reason why it sends `null` instead of `' '` !

**Comment by philip-loyd** [comment]
Was this resolved?

**Comment by MostafaAttia** [comment]
@philip-loyd  Not Yet!

**Comment by johannac** [comment]
I'm not able to replicate this with the current version. Please reopen if anyone is still getting this with the current version.
