### ISSUE TITLE
Unable to connect to database

### ISSUE THREAD

**Issue by loganfreeman** [Attendize/Attendize#54]
```
git show HEAD~
commit 20b736117874379ebeb041cb2194eb9220ba29c2
```

```
Unable to connect to database.
Please fill valid database credentials into .env and rerun this command.
```

```
APP_ENV=production
APP_DEBUG=false
APP_URL=
APP_CIPHER=rijndael-128
APP_KEY=SomeRandomString
APP_TIMEZONE

DB_TYPE=pgsql
DB_HOST=localhost
DB_DATABASE=attendize_dev
DB_USERNAME=attendize
DB_PASSWORD=password

MAIL_DRIVER=smtp
MAIL_PORT=587
MAIL_ENCRYPTION=tls
MAIL_HOST=
MAIL_FROM_ADDRESS=
MAIL_FROM_NAME=
MAIL_PASSWORD=
MAIL_USERNAME=

GOOGLE_ANALYTICS_ID=

TWITTER_WIDGET_ID=
```

**Comment by JapSeyz** [comment]
Can you connect with other tools?

Please try a standalone database viewer, to make sure there's not a spelling mistake in the credentials.

**Comment by loganfreeman** [comment]
I can connect from command line.
```
psql -U attendize -h localhost -d attendize_dev
```

**Comment by loganfreeman** [comment]
`php -m | grep sql`
output: 
```
mysql
mysqli
pdo_mysql
pdo_pgsql
pgsql
```

**Comment by JapSeyz** [comment]
That is odd, make sure the env names match the ones in the config file, otherwise I don't know what to tell you except try with mysql instead of pgsql, as I am positive that works.

**Comment by daveearley** [comment]
I think this is an issue with using PostgreSQL, as someone just emailed me with the same problem. Their install worked with MySQL but not Postgre. I'll try replicate it now and see if I can find the issue.

**Comment by loganfreeman** [comment]
Thanks. I figured it out.

In config/database.php, line 29:
```
  'default' => 'mysql',
```

I thought the DB_TYPE comes from the .env file, but not.

I have to change the database.php:

```
    'default' => 'pgsql',
```

then it works.

**Comment by daveearley** [comment]
Nice spot, pushed a fix there.
