### ISSUE TITLE
Unable to edit survey questions (with solution)

### ISSUE THREAD

**Issue by scottybo** [Attendize/Attendize#545]
Just reviving this very old issue #159 

The solution is pretty simple, in the `EventSurveyController.php` file, in the `postEditEventQuestion` function, modify:

```php
$question->is_required = $request->get('is_required');
```
to be 

```php
$question->is_required = null !== $request->get('is_required') ? $request->get('is_required') : false;
```
So that a value is always set.

**Comment by philip-loyd** [comment]
Did you make a pull request for this? @scottybo

**Comment by johannac** [comment]
This was fixed via https://github.com/Attendize/Attendize/pull/906
