### ISSUE TITLE
namespaceing  and packaging

### ISSUE THREAD

**Issue by pelim** [Attendize/Attendize#56]
consider to split the application into several parts and or namespace by domain logic. i.e:

```
Attendize 
     Account
         Register
    Payment
    Event
       Ticket
       Venue
```

storing all controllers in one folder could lead to lose the track over the project

**Comment by daveearley** [comment]
I'll add this to the v1.0.0 milestone. The Controller directory is already getting a bit bloated so would be a nice improvement.

**Comment by etiennemarais** [comment]
Closing this due to age
