### ISSUE TITLE
use resource routing and model binding

### ISSUE THREAD

**Issue by pelim** [Attendize/Attendize#57]
https://laravel.com/docs/5.2/controllers#restful-resource-controllers

```
Route::resource('events. tickets', EventsTicketsControl::class);
Route::resource('events. attendees', EventsAttendeesControl::class);
```

and bind the models to the route in the routeServiceProvider

https://laravel.com/docs/5.2/routing#route-model-binding

**Comment by jncampbell** [comment]
I don't think the resource routes is a good idea. Listing routes individually is much more explicit, which makes it easier to give a bird's eye view of the application.

But +1 for the model binding.
