### ISSUE TITLE
Is it possible to rank tickets with the default function?

### ISSUE THREAD

**Issue by matometaru** [Attendize/Attendize#578]
Is it possible to rank tickets with the default function?

For example.
A seat: $ 50
B seat: $ 25

**Comment by samdb** [comment]
You can re-order the tickets that you have created by dragging them with the handle in the bottom left corner.
<img width="471" alt="screenshot 2019-02-25 at 11 01 19" src="https://user-images.githubusercontent.com/5083658/53333052-b7499180-38ec-11e9-9875-4d9100da378f.png">

**Comment by matometaru** [comment]
Thank you!!
It was able to be created.
