### ISSUE TITLE
Question about operation(Management?) of the Attendize.

### ISSUE THREAD

**Issue by matometaru** [Attendize/Attendize#582]
It is a question about operation of the Attendize.
The organizer is free to create an event.
If a malicious organizer did not hold an event after selling the ticket, how do you deal with it?

Do site administrators need to compensate users?

**Comment by ajmas** [comment]
Since you are self-hosting the service, then I would imagine this comes down to how as a business you wish to manage this, local laws and what terms and conditions are in place?

Attendize provides the tooling to help organise events, but that is all. The risk and how it is to be managed ultimately comes down the operators. That being said, what features do you think could be added to help an organisation reduce that risk?

**Comment by samdb** [comment]
As ajmas said, this would be down to how you manage the service if you decide to use it in a SAAS setup.

**Comment by Iamscalla** [comment]
Just to give my take, I did a total rewrite of Attendize with new features, thinking in direction of malicious organizers, the money can't be cleared till event is over. But if you want a fast clearing, as an organizer, you under go a verification process to determine if you should be allow instant payout.

**Comment by matometaru** [comment]
Thank you for your reply. It was helpful.

The way I am planning to operate,

The first is
A method called escrow. For example, all of the organizer 's stripe' serckekey is also made by the administrator.

Secondly,
Issue account only to reliable organizers.

@Iamscalla 
Is your way first?

> But if you want a fast clearing, as an organizer, you under go a verification process to determine if you should be allow instant payout.

Do you change the organizer's secret key only at this time?

**Comment by Iamscalla** [comment]
> 
> 
> Thank you for your reply. It was helpful.
> 
> The way I am planning to operate,
> 
> The first is
> A method called escrow. For example, all of the organizer 's stripe' serckekey is also made by the administrator.
> 
> Secondly,
> Issue account only to reliable organizers.
> 
> @Iamscalla
> Is your way first?
> 
> > But if you want a fast clearing, as an organizer, you under go a verification process to determine if you should be allow instant payout.
> 
> Do you change the organizer's secret key only at this time?

the first option is better, the second option is restrictive.

i don't change organizer's secret key, as my implementation is an  automated bank deposit after event is cleared via the payment processor

**Comment by matometaru** [comment]
> an automated bank deposit

I can not understand the above.

I will create it in the first way.

Thank you.
