### ISSUE TITLE
message.php and validation.php are duplicated.

### ISSUE THREAD

**Issue by matometaru** [Attendize/Attendize#594]
message.php and validation.php are duplicated.

- https://github.com/Attendize/Attendize/blob/master/resources/lang/en/validation.php
- https://github.com/Attendize/Attendize/blob/master/resources/lang/en/messages.php

Delete message.php?

**Comment by jeremyquinton** [comment]
@matometaru thanks for pointing this out. I will meed to look into this and sort it out.
