### ISSUE TITLE
Use of Confusing and incorrect variable names

### ISSUE THREAD

**Issue by mohapinkepane** [Attendize/Attendize#598]
$event  is used instead of $organiser  ,the code still works of course but it is confusing.

  This is what  i am talking about(check out the first line in the function):
 

    /**
     * Edits organiser profile page colors / design
     *
     * @param Request $request
     * @param $organiser_id
     * @return mixed
     */
    public function postEditOrganiserPageDesign(Request $request, $organiser_id)
    {
        $event = Organiser::scope()->findOrFail($organiser_id);

        $rules = [
            'page_bg_color'        => ['required'],
            'page_header_bg_color' => ['required'],
            'page_text_color'      => ['required'],
        ];
        $messages = [
            'page_header_bg_color.required' => trans("Controllers.error.page_header_bg_color.required"),
            'page_bg_color.required'        => trans("Controllers.error.page_bg_color.required")
 
        ];

        $validator = Validator::make($request->all(), $rules, $messages);

        if ($validator->fails()) {
            return response()->json([
                'status' => 'error',
                'messages' => $validator->messages()->toArray(),
            ]);
        }

        $event->page_bg_color        = $request->get('page_bg_color');
        $event->page_header_bg_color = $request->get('page_header_bg_color');
        $event->page_text_color      = $request->get('page_text_color');
        
        $event->save();

        return response()->json([
            'status'  => 'success',
            'message' => trans("Controllers.organiser_design_successfully_updated"),
        ]);
    }

**Comment by Iamscalla** [comment]
It's just a variable name, nothing fancy. You can replace it and move on

**Comment by jeremyquinton** [comment]
I have renamed this variable name. @mohapinkepane we accept PRs so feel free to fix in future 👍
