### ISSUE TITLE
someone can help me set up the database in a docker on windows system?

### ISSUE THREAD

**Issue by oTTa** [Attendize/Attendize#603]
Hi, I'm using docker in windows 10 System.

This is a step 9 of [Running Attendize in Docker for development](http://www.attendize.com/getting_started.html#running-attendize-in-docker-for-development).  

My ploblem is I run `docker-compose run php php artisan attendize:install` and display:

`Access denied for user 'attendize'@'172.19.0.9' (using password: YES) (SQL: select * from information_sche
  ma.tables where table_schema = attendize and table_name = migrations)`

The .env file is a default, Do I need to change it?
how to configure the docker database?

thanks.

**Comment by jakkritz** [comment]
you need to create database in mysql.

**Comment by oTTa** [comment]
> you need to create database in mysql.

yes, I created database but it didn't work :(

**Comment by jakkritz** [comment]
what's the error?

**Comment by oTTa** [comment]
> what's the error?

I tried to connect to database but I cant, I dont know the default user and password.
The database was created in other docker instance, that's the problem

Do you know de user and password?
sorry for the inconvenience

**Comment by jakkritz** [comment]
You can set mysql_root_password in docker-compose file.

**Comment by oTTa** [comment]
> You can set mysql_root_password in docker-compose file.

Thank you
