### ISSUE TITLE
Event start date popup is closed immediently using Google Chrome

### ISSUE THREAD

**Issue by jonathanwerle** [Attendize/Attendize#608]
When you create a new event and try to select the event's start (or end) date, the popup closes itself immediently. 
This problem only occurs to me using Google Chrome. I tried Edge as an alternative and it works like a charm!
Therefore it's impossible to create new events in Chrome.
Any ideas?

![attendizebug](https://user-images.githubusercontent.com/18647622/55239201-74a20e80-5236-11e9-9083-1f23c48fb1a4.gif)

**Comment by weddingjuma** [comment]
I get the same problem in Chrome

**Comment by Hoglan** [comment]
You can temporarily work around by right clicking the date field, this opens both the date picker and the chrome options, click away from the chrome options panel and the date picker stays in place.

(this worked for our clients who were badgering us anyway!)

**Comment by mohapinkepane** [comment]
@jonathanwerle    

Go to the search bar in your text editor and search : **$(document).on("click.DateTimePicker", function(e)**  .
You show get about 5 results and then in each of the 5 files comment the following lines of code : 

**$(document).on("click.DateTimePicker", function(e)
  {
   oDTP._hidePicker("");
 });**

Also refer to  https://github.com/nehakadam/DateTimePicker/issues/155   for  the gory details.
Hope it helps!!!

**Comment by mrlexley** [comment]
I made a pull request to fix the issue :-) #612

**Comment by jeremyquinton** [comment]
@jonathanwerle thanks for reporting
@mrlexley thanks for fixing I have merged your PR this will go out in the next release.

**Comment by manuelgeek** [comment]
@mohapinkepane  thanks man, that did the hack, saved my day :+1: :100:
