### ISSUE TITLE
Installing is stuck

### ISSUE THREAD

**Issue by MohanadI** [Attendize/Attendize#609]
Hi all , 

I have problem while installing 
everything seems ok like this image , but when I press " Install Attendize " nothing happens just a refresh

![attendize](https://user-images.githubusercontent.com/26893608/55280684-f6c72b80-5339-11e9-9f3a-14407fb89303.png)

Laravel log says "   local.ERROR: Please enter all app settings. The given data was invalid.   "

my .env 

> APP_ENV=local
> APP_DEBUG=true
> APP_URL=http://local.attendize.com
> APP_CIPHER=AES-256-CBC
> APP_KEY=base64:GSWbE7jjx5Fm1UYxUS3SWcMgqARZzPHRhUorAW7luVs=
> APP_TIMEZONE=
> 
> DB_CONNECTION=mysql
> DB_TYPE=mysql
> DB_HOST=127.0.0.1
> DB_PORT=3306
> DB_DATABASE=attendize
> DB_USERNAME=root
> DB_PASSWORD=
> 
> DEFAULT_DATEPICKER_SEPERATOR="-"
> DEFAULT_DATEPICKER_FORMAT="yyyy-MM-dd HH:mm"
> DEFAULT_DATETIME_FORMAT="Y-m-d H:i"
> 
> WKHTML2PDF_BIN_FILE=wkhtmltopdf-amd64
> 
> MAIL_DRIVER=smtp
> MAIL_PORT=25
> MAIL_ENCRYPTION=
> MAIL_HOST=maildev
> MAIL_FROM_ADDRESS=testing@attendize.com
> MAIL_FROM_NAME=testing_service
> MAIL_PASSWORD=
> MAIL_USERNAME=
> 
> GOOGLE_ANALYTICS_ID=
> GOOGLE_MAPS_GEOCODING_KEY=
> 
> TWITTER_WIDGET_ID=
> 
> LOG=errorlog

any suggestions ?

**Comment by spiddacino** [comment]
Experienced the same yesterday.
Thought i probably missed a step and re ran the process again.

When i click on install attendize, i get a blank screen.

**Comment by MohanadI** [comment]
Got the problem , 

Inside InstallerController.php - line : 108

> 'database_password' => 'required'

I do not have password for my local server so I just stop the code and it works fine

**Comment by spiddacino** [comment]
Don't know if mine is an isolated issue but i still have it even after doing a reinstall.
With reference to Mohanadi last comment, i'm good but after install, both the signup and login url gives me a blank page.
No errors in logs also.
I'd appreciate any ideas.
Thanks

**Comment by Nikto655** [comment]
I get a blank screen even before the install screen.
