### ISSUE TITLE
Event CheckIn with QRCode Scanning

### ISSUE THREAD

**Issue by mercuryseries** [Attendize/Attendize#61]
Hi,

I just want to know if it will be a good idea to work on a Web Platform for Event Check-In via QR Code. If the answer is YES, i will start working on that and I will make a pull request tomorrow.

Let me know.

Cheers,

**Comment by daveearley** [comment]
Hi Honoré,

Got for it! There's  an existing  check-in page so if it could be
incorporated into that it would be great. Out of curiosity how would you
achieve web based QR reading?

Cheers!

**Comment by mercuryseries** [comment]
I made a pull request for that. Let me know what you think of that.

PS: I'm not really good with CSS. Someone else will probably work on the UI aspect :).

**Comment by daveearley** [comment]
Nice work!,  feel free to add yourself to the contributors in the readme. Cheers.

**Comment by mercuryseries** [comment]
Great. Thanks :)
