### ISSUE TITLE
Blank Post Installation Login & Signup Screen

### ISSUE THREAD

**Issue by spiddacino** [Attendize/Attendize#611]
Don't know if mine is an isolated issue but i still have it even after doing a reinstall.
With reference to Mohanadi last comment, i'm good but after install, both the signup and login url gives me a blank page.
No errors in logs also.
I'd appreciate any ideas.
Thanks

_Originally posted by @spiddacino in https://github.com/Attendize/Attendize/issues/609#issuecomment-479329852_

**Comment by mrlexley** [comment]
Can you give more details about your env? Like if you running it on a docker container or of you running it on a webserver and wich one?

Can you rerun the installation with debug mode on and post the content of storage\logs\laravel.log?

**Comment by spiddacino** [comment]
Thanks.
That did the magic.
The key point was to run in debug mode as true.
It gave an error saying unidentified trailing white spaces in Mailing Name cos i used a three word mailing name, gave same issue with two words.
Making it one word made it sail through like a breeze.

By the way, i was running it on a linux webserver.

**Comment by icklecows** [comment]
Alternatively putting the multi-word Mailing Name in quote marks is equally effective.

**Comment by stylefieber** [comment]
Had same issue. That should definitely be validated in frontend form.

**Comment by ampliads** [comment]
I spent nearly 4 hours just to figure this out! Thanks all. 
May someone work to fix this? It would be deeply appriciated!

**Comment by Nikto655** [comment]
This is still an issue. How to fix?
