### ISSUE TITLE
Which device use for QR Code and How To Setup In Local Device 

### ISSUE THREAD

**Issue by harshit1235** [Attendize/Attendize#614]
Hi,

Thanks for making this type of Good System I like it..

I have a question , How i read QR Code in below screen(sent screenshot) , I tried my system (laptop) camera but that camera not able to read this so Is there any device I need to purchase or any way for read this QR Code ?

![image](https://user-images.githubusercontent.com/48353622/55561832-7b39f580-5710-11e9-80a1-7eb004b15a0b.png)

Please help me

Thanks&Regards

**Comment by mrlexley** [comment]
The blue page seems to indicate that you didn't give permission to the camera.
Did you get a popup for giving permission to the camera? Does you camera work on other apps?

**Comment by mrlexley** [comment]
Can you also put the output of your console? Hopfully we can indicate the problem.
I'm running the app in XAMPP like you, also using chrome latest version, so it should work.
CTRL+SHIFT+J

**Comment by jakkritz** [comment]
@mrlexley 
How do you fix camera not working on macos below 10.14 and iOS below 12.2? I can confirm camera is working previously but not since recently os update.

<img width="683" alt="Screen Shot 2562-04-06 at 22 41 29" src="https://user-images.githubusercontent.com/44876520/55671722-24bdea00-58bd-11e9-9616-60ec96c903c3.png">

I have seen this https://webrtc.github.io/samples/src/content/getusermedia/gum/  and tried without success.

**Comment by jakkritz** [comment]
I got it working. If anybody faces the same issue, please see https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia

**Comment by mrlexley** [comment]
Can you do al pull with the changes? So the developer can do a merge to master with the fix.

**Comment by jakkritz** [comment]
sure

**Comment by Geoffry304** [comment]
> I got it working. If anybody faces the same issue, please see https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia
> 
> Edit:
> Also you need to add this to CheckIn.blade
> ` <meta name="apple-mobile-web-app-capable" content="yes" />`

Could you tell me what to change in the check_in.js plz?

**Comment by jakkritz** [comment]
I did not have time to do pull request but here it is: 
p.s if you could, please do the PR
            qrcode.callback = this.QrCheckin;

            // FIX SAFARI CAMERA
            if (navigator.mediaDevices === undefined) {
                navigator.mediaDevices = {};
            }

            if (navigator.mediaDevices.getUserMedia === undefined) {
                navigator.mediaDevices.getUserMedia = function(constraints) {
                    var getUserMedia = navigator.webkitGetUserMedia || navigator.mozGetUserMedia;

                    if (!getUserMedia) {
                        return Promise.reject(new Error('getUserMedia is not implemented in this browser'));
                    }

                    return new Promise(function(resolve, reject) {
                        getUserMedia.call(navigator, constraints, resolve, reject);
                    });
                }
            }

            navigator.mediaDevices.getUserMedia({
                video: {
                    facingMode: "user" //TODO: Add switch to toggle "user" or "enviroment"
                },
                audio: false
            }).then(function(stream) {
                that.stream = stream;

                if (that.videoElement.mozSrcObject !== undefined) { // works on firefox now
                    that.videoElement.mozSrcObject = stream;
                } else if(window.URL) { // and chrome, but must use https
                    that.videoElement.srcObject = stream;
                };
            }).catch(function(err) {
                console.log(err.name + ": " + err.message);
                alert(lang("checkin_init_error"));
            });

/* ----- DELETE THESE -------------
            navigator.getUserMedia = navigator.getUserMedia || navigator.webkitGetUserMedia || navigator.mozGetUserMedia;

            navigator.getUserMedia({
                video: {
                    facingMode: 'environment'
                },
                audio: false
            }, function (stream) {

                that.stream = stream;

                if (that.videoElement.mozSrcObject !== undefined) { // works on firefox now
                    that.videoElement.mozSrcObject = stream;
                } else if(window.URL) { // and chrome, but must use https
                    that.videoElement.srcObject = stream;
                };

            }, function () { // error
                alert(lang("checkin_init_error"));
            });
 ----------------------------------------------------------------------------- */

            this.isInit = true;
`

**Comment by justynpride** [comment]
I must be missing something when I try this fix. Has one got it working and can push a fix?

**Comment by mstaack** [comment]
having the same problem currently.. no camera only blue screen with ios chrome/safari..

@jakkritz your code works?

**Comment by jakkritz** [comment]
It works

> having the same problem currently.. no camera only blue screen with ios chrome/safari..
> 
> @jakkritz your code works?

**Comment by mstaack** [comment]
Can you cleanup your instructions/code so I can make a proper pull request? Thanks

**Comment by jakkritz** [comment]
file - resources/views/ManageEvent/CheckIn.blade.php 
add line 17
https://pastebin.com/YkynxhaR

file - public/assets/javascript/check_in.js
replace lines 134 thru 155 with 97 thru 132
https://pastebin.com/arFBrHns

**Comment by mstaack** [comment]
thanks, this works on safari with ios12.2. but chrome does not work yet

**Comment by jakkritz** [comment]
I can confirm it is working on Chrome and Firefox as well tested on Ubuntu 18.04 and macos 10.14.5 Beta. The only problem I have is Chrome and Firefox on iOS particularly 12.2. I remember they were working before recent iOS firmware upgrade though.

**Comment by Bellusterra** [comment]
@jakkritz Thank you for the fix.
