### ISSUE TITLE
Export Ref Codes

### ISSUE THREAD

**Issue by Reece0Connor** [Attendize/Attendize#617]
Looking to export ref codes to use an external scanner device, what would be the easiest way of doing so?

I thought playing with the current export sheet to add a field to export the "secret ref code" but had no joy, has anyone else ever done this successfully or have any other recommendations?

**Comment by mrlexley** [comment]
Hello, when you use the export of attendees. You have a field named "Ticket ID".
This field is the secret ref code or QR data your looking for ;-)

**Comment by Reece0Connor** [comment]
@mrlexley I don't have this field.
This is the file I receive when I export https://imgur.com/BnxUYgI

**Comment by mrlexley** [comment]
Can you tell me what version are you running? I see its added to te latest release.
You can update the app, or just thange the lines in de commit: 41ead8b

**Comment by Reece0Connor** [comment]
Ohh I didn't notice that,

I'm running a version from over a year ago, due to all the changes we've made

**Comment by mrlexley** [comment]
If it worked out just close the ticket :-)
