### ISSUE TITLE
upgrade from 1.0.0

### ISSUE THREAD

**Issue by clawfire** [Attendize/Attendize#619]
Hi there, where's the doc about how to upgrade from a version to another. I though they where something somewhere but lost it :/

**Comment by jeremyquinton** [comment]
@clawfire 

As always its best to test the new software in an environment other than production I would follow the following steps to upgrade. 

1. Take a copy of the production database to another environment like staging. 
2. Update this environment to the latest version. 
3. Run the database migrations using artisan.
    ```php artisan migrate```

That should do it.

**Comment by clawfire** [comment]
Yeah I was planning to do some testing before (getting a snapshot of my prod and testing in it).
So It's just replacing file and trigger migration via artisan. cool sound easy. 

Thanks

**Comment by clawfire** [comment]
When I'm launching the php artisan migrate command I got this 
```
production.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Class 'Illuminate\Notifications\NotificationServiceProvider' not found in /srv/data/web/vhosts/[REDACTED]/htdocs/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php:146
```

**Comment by jeremyquinton** [comment]
clear out 
```bootstrap/cache/```
and 
```storage/cache/*```

Also worth running all the cache clear commands.
```php artisan cache:clear
php artisan route:cache
php artisan config:cache
php artisan view:clear```

**Comment by clawfire** [comment]
Hi there,

every `php artisan` command return a 
```
[Symfony\Component\Debug\Exception\FatalThrowableError]
Class 'Illuminate\Notifications\NotificationServiceProvider' not found
```

**Comment by clawfire** [comment]
ok, found it. 

1. `php composer.phar update`
2. `php composer.phar upgrade`
3. `php artisan migrate`

And voila :)
