### ISSUE TITLE
Error when updating Laravel 5.2

### ISSUE THREAD

**Issue by jncampbell** [Attendize/Attendize#62]
I ran into an error when working on #53.

After updating the composer.json file to include "laravel/framework": "5.2.*" and running the `composer update` command, an `Uncaught ReflectionException: Class log does not exist in...` error is returned. 

I've narrowed down the problem to line 27 of the Attendize/config/attendize.php : 
`'checkout_timeout_after' => app()->environment('local', 'development') ? 30 : 8, #mintutes`

If I comment that line out, the problem is fixed. I think it's happening because the app isn't fully loaded yet so, the app() global function isn't available and it's causing an exception that may have previously been silenced. But, that's just a theory at this point. 

I suggest creating a CHECKOUT_TIMEOUT_AFTER variable in the .env file. It's a simple fix but, I wanted to get confirmation that it's okay before I made unexpected changes to any config and/or .env files.

**Comment by daveearley** [comment]
Ye go for it! I added that line as a quick workaround while I was testing the payment gateways; it makes more sense to have it in the .env

 Cheers!
