### ISSUE TITLE
unable to activate dummy payment

### ISSUE THREAD

**Issue by ShouldIPressTheButton** [Attendize/Attendize#620]
Version 1.0.0

editing 'enable_dummy_payment_gateway => true' to './conf/attendize.php' didn't enabled dummy payment method in tab 'account-setting/Payment'. 

Is there an extra step ?

**Comment by jeremyquinton** [comment]
@ShouldIPressTheButton its possible that you have updated the option in './conf/attendize.php' but the configuration option is still cached. 

try running the following to clear and re-create the cache.
```
php artisan config:clear
php artisan config:cache
```

**Comment by etiennemarais** [comment]
Closing this due to age
