### ISSUE TITLE
GDPR issues

### ISSUE THREAD

**Issue by ilu33** [Attendize/Attendize#622]
We used attendize 1.0 for about a year and really liked it but we had to dump it due to GDPR issues. Main problem was the missing double-opt-in feature (activating accounts only after email confirmation) which also resulted in some spam. May I ask whether the new version addresses this problem?
Also there were some minor issues with widgets and javascripts (facebook, stripe, google) as listed here https://github.com/Toppoint/Attendize/issues, some of them we had already fixed.
I'm looking forward to testing attendize again.

**Comment by samdb** [comment]
@ilu33 What is the GDPR issue in your opinion? There should be no issue sending transactional emails related to a purchase.

https://gdpr-info.eu/art-6-gdpr/
> (f) Legitimate interests: Processing is necessary for the purposes of legitimate interests. Recital 47 of GDPR lays out six situations when processing personal data is lawful.

https://gdpr-info.eu/recitals/no-47/
> (2) Such legitimate interest could exist for example where there is a relevant and appropriate relationship between the data subject and the controller in situations such as where the data subject is a client or in the service of the controller.

**Comment by ilu33** [comment]
You can send emails to a person that registered if you made sure that that person REALLY registered. Without double opt-in anybody can register with anybody else's email address. We never know who did the registering. Double opt-in is a sensible standard and even before GDPR we were not allowed to operate a server without it (there was just no fine). Actually it's in our best interest to make sure that only the email owner uses an address on our server.

Legitimate interests are fine as long as the data processing is necessary for delivering the service. But if the services of facebook, stripe, google are not necessary for the event there is no legitimate interest. We want to use a self-hosted event system because we don't want to hand any data over to any other company. Otherwise we could just use eventbrite.

**Comment by ilu33** [comment]
I put effort into answering your question. Just closing the issue without you answering my question seems harsh. To remind: Does attendize now support double opt-in upon registering or not?

**Comment by samdb** [comment]
No, it does not and we don’t plan on implementing double opt-in.

If at some point in the future we introduce the concept of purchasers having accounts then we will review this again.

**Comment by ilu33** [comment]
Ok thanks for answering. I understand that in your mind of thinking about "purchasers" double-opt-in doesn't make much sense. Since all our events are free while attendees are limited, fake registrations with fake emails are really an important issue. I guess we'll look for another platform to use.
