### ISSUE TITLE
InvalidArgumentException View [Mailers.TicketMailer.SendOrderTickets] not found.

### ISSUE THREAD

**Issue by WASOE** [Attendize/Attendize#637]
I am having this error, someone knows what it could be?
![WhatsApp Image 2019-05-07 at 10 24 13](https://user-images.githubusercontent.com/45973933/57285277-285ab180-70b3-11e9-8936-d13890bd0654.jpeg)

**Comment by publicarray** [comment]
What language are you using with Attendize?

**Comment by publicarray** [comment]
The file is only present in the following languages en, es, fr, js and pl. Translators need to create the file maybe you can help out?

**Comment by johannac** [comment]
This ticket is being closed due to receiving no further response from the original author.
