### ISSUE TITLE
Unable to delete primary photo on "customize" screen.

### ISSUE THREAD

**Issue by MixoloAPPteam** [Attendize/Attendize#641]
The organizers have been able to delete the photo in the past by putting a check mark in the delete photo box and saving changes. Recently, we find we cannot delete the primary photo.  Photos uploaded later on the customize screen can be deleted, however.

**Comment by jeremyquinton** [comment]
@MixoloAPPteam I have tested this on the master branch and it works correctly.

**Comment by johannac** [comment]
This ticket is being closed due to receiving no further response from the original author.
