### ISSUE TITLE
Adding a form prior to accept the ticket booking

### ISSUE THREAD

**Issue by zenny** [Attendize/Attendize#649]
Hi,

I appreciate if someone can elaborate on adding a form prior to the payment because the event organizer needs some prior physical data of the applicant for approval into the event (participant).

Thanks, and cheers,
/z

**Comment by samdb** [comment]
Have you tried adding a custom survey (on the left menu) after creating an event? The questions can be set to be required but are per-ticket rather than per-order.

**Comment by zenny** [comment]
@samdb Thanks!

**Comment by zenny** [comment]
@samdb Is it possible to separate custom survey form from the registration page?

Any hints to change/customize the look? 

Cheers,
/z
