### ISSUE TITLE
Unable to remove access codes

### ISSUE THREAD

**Issue by vienh2o** [Attendize/Attendize#658]
The new access code feature is great, but we cannot delete ones that already exist. We can remove it from a ticket, but the code still remains.

**Comment by etiennemarais** [comment]
@vienh2o There is a rule in the system that specifies that when an access code has been used already, it cannot be removed. Please see here: https://github.com/Attendize/Attendize/blob/master/app/Http/Controllers/EventAccessCodesController.php#L100-L105

What is the pain you are experiencing here?
