### ISSUE TITLE
How to add new currencies

### ISSUE THREAD

**Issue by w00p** [Attendize/Attendize#66]
Hi, is it possible to add Norwegian Krone?

**Comment by daveearley** [comment]
If you un-comment the lines related to the Krone here: https://github.com/Attendize/Attendize/blob/master/database/seeds/ConstantsSeeder.php#L258 and then perform the install you will be able to use Norwegian Krone. Cheers.

**Comment by kuldeepJain11** [comment]
You can add via database. open database and insert new record in 'currencies' table.
