### ISSUE TITLE
 Error when inputting location on google maps

### ISSUE THREAD

**Issue by willyadinata** [Attendize/Attendize#661]
Error when inputting location on google maps "Venue Name" and displaying the following error message "This page can't load Google Maps correctly". Please correct. Thank you

**Comment by phillypro** [comment]
I had the same issue

you have to create a google maps API key....

through google cloud platform

heres how you do it

create a google cloud platform account
create a project
click on that project then search for javascript map api
and select enable
then search for places api
and select enable

then you have to add a billing option on the account....but dont worry it wont bill you for a whole year its a 12 month free trial

AND! ....if you're a small traffic site its basically peanuts to use it :)

**Comment by robetus** [comment]
I entered my geocoding API key in config/attendize.php but it still gives an error on v2.4.0.
