### ISSUE TITLE
 Error when invited attendee

### ISSUE THREAD

**Issue by willyadinata** [Attendize/Attendize#662]
Version 1.0.0

Log :

[2019-07-22 17:13:02] production.INFO: {"id":2,"account_id":"1","order_status_id":"1","created_at":"2019-07-22 17:13:02","updated_at":"2019-07-22 17:13:02","deleted_at":null,"first_name":"Jono Susilo","last_name":"Utomo","email":"jonosusiloutomo@gmail.com","ticket_pdf_path":null,"order_reference":"bFk0Y227","transaction_id":null,"discount":null,"booking_fee":null,"organiser_booking_fee":null,"order_date":null,"notes":null,"is_deleted":"0","is_cancelled":"0","is_partially_refunded":"0","is_refunded":"0","amount":"0.00","amount_refunded":null,"event_id":"1","payment_gateway_id":null,"is_payment_received":"1","taxamt":"0.00"}  
[2019-07-22 17:13:03] production.INFO: Ticket generated!  
[2019-07-22 17:13:03] production.INFO: Sending invite to: jonosusiloutomo@gmail.com  
[2019-07-22 17:13:33] production.ERROR: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away (SQL: select * from `attendees` where `attendees`.`id` = 2 limit 1) {"userId":1,"exception":"[object] (Illuminate\\Database\\QueryException(code: HY000): SQLSTATE[HY000]: General error: 2006 MySQL server has gone away (SQL: select * from `attendees` where `attendees`.`id` = 2 limit 1) at /home/wilgatri/public_html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, Doctrine\\DBAL\\Driver\\PDOException(code: HY000): SQLSTATE[HY000]: General error: 2006 MySQL server has gone away at /home/wilgatri/public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:63, PDOException(code: HY000): SQLSTATE[HY000]: General error: 2006 MySQL server has gone away at /home/wilgatri/public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:61)
[stacktrace]
#0 /home/wilgatri/public_html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(624): Illuminate\\Database\\Connection->runQueryCallback('select * from `...', Array, Object(Closure))
#1 /home/wilgatri/public_html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(333): Illuminate\\Database\\Connection->run('select * from `...', Array, Object(Closure))
#2 /home/wilgatri/public_html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2120): Illuminate\\Database\\Connection->select('select * from `...', Array, false)
#3 /home/wilgatri/public_html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2108): Illuminate\\Database\\Query\\Builder->runSelect()
#4 /home/wilgatri/public_html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2594): Illuminate\\Database\\Query\\Builder->Illuminate\\Database\\Query\\{closure}()
#5 /home/wilgatri/public_html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2109): Illuminate\\Database\\Query\\Builder->onceWithColumns(Array, Object(Closure))
#6 /home/wilgatri/public_html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(519): Illuminate\\Database\\Query\\Builder->get(Array)
#7 /home/wilgatri/public_html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(503): Illuminate\\Database\\Eloquent\\Builder->getModels(Array)
#8 /home/wilgatri/public_html/vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php(77): Illuminate\\Database\\Eloquent\\Builder->get(Array)
#9 /home/wilgatri/public_html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(448): Illuminate\\Database\\Eloquent\\Builder->first(Array)
#10 /home/wilgatri/public_html/vendor/laravel/framework/src/Illuminate/Queue/SerializesAndRestoresModelIdentifiers.php(85): Illuminate\\Database\\Eloquent\\Builder->firstOrFail()
#11 /home/wilgatri/public_html/vendor/laravel/framework/src/Illuminate/Queue/SerializesAndRestoresModelIdentifiers.php(55): App\\Jobs\\SendAttendeeInvite->restoreModel(Object(Illuminate\\Contracts\\Database\\ModelIdentifier))
#12 /home/wilgatri/public_html/vendor/laravel/framework/src/Illuminate/Queue/SerializesModels.php(45): App\\Jobs\\SendAttendeeInvite->getRestoredPropertyValue(Object(Illuminate\\Contracts\\Database\\ModelIdentifier))
#13 [internal function]: App\\Jobs\\SendAttendeeInvite->__wakeup()
#14 /home/wilgatri/public_html/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(144): unserialize('O:27:\"App\\\\Jobs\\\\...')
#15 /home/wilgatri/public_html/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(201): Illuminate\\Queue\\CallQueuedHandler->failed(Array, Object(Swift_TransportException))
#16 /home/wilgatri/public_html/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(180): Illuminate\\Queue\\Jobs\\Job->failed(Object(Swift_TransportException))
#17 /home/wilgatri/public_html/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(119): Illuminate\\Queue\\Jobs\\Job->fail(Object(Swift_TransportException))
#18 /home/wilgatri/public_html/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(46): Illuminate\\Queue\\SyncQueue->handleException(Object(Illuminate\\Queue\\Jobs\\SyncJob), Object(Swift_TransportException))
#19 /home/wilgatri/public_html/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(184): Illuminate\\Queue\\SyncQueue->push(Object(App\\Jobs\\SendAttendeeInvite))
#20 /home/wilgatri/public_html/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(160): Illuminate\\Bus\\Dispatcher->pushCommandToQueue(Object(Illuminate\\Queue\\SyncQueue), Object(App\\Jobs\\SendAttendeeInvite))
#21 /home/wilgatri/public_html/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(73): Illuminate\\Bus\\Dispatcher->dispatchToQueue(Object(App\\Jobs\\SendAttendeeInvite))
#22 /home/wilgatri/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Bus/DispatchesJobs.php(17): Illuminate\\Bus\\Dispatcher->dispatch(Object(App\\Jobs\\SendAttendeeInvite))
#23 /home/wilgatri/public_html/app/Http/Controllers/EventAttendeesController.php(210): App\\Http\\Controllers\\Controller->dispatch(Object(App\\Jobs\\SendAttendeeInvite))
#24 [internal function]: App\\Http\\Controllers\\EventAttendeesController->postInviteAttendee(Object(Illuminate\\Http\\Request), '1')
#25 /home/wilgatri/public_html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#26 /home/wilgatri/public_html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('postInviteAtten...', Array)
#27 /home/wilgatri/public_html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\EventAttendeesController), 'postInviteAtten...')
#28 /home/wilgatri/public_html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\\Routing\\Route->runController()
#29 /home/wilgatri/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(680): Illuminate\\Routing\\Route->run()
#30 /home/wilgatri/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#31 /home/wilgatri/public_html/app/Http/Middleware/FirstRunMiddleware.php(34): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#32 /home/wilgatri/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): app\\Http\\Middleware\\FirstRunMiddleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#33 /home/wilgatri/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#34 /home/wilgatri/public_html/app/Http/Middleware/Authenticate.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#35 /home/wilgatri/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): App\\Http\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#36 /home/wilgatri/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#37 /home/wilgatri/public_html/vendor/mcamara/laravel-localization/src/Mcamara/LaravelLocalization/Middleware/LaravelLocalizationViewPath.php(33): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#38 /home/wilgatri/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Mcamara\\LaravelLocalization\\Middleware\\LaravelLocalizationViewPath->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#39 /home/wilgatri/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#40 /home/wilgatri/public_html/vendor/mcamara/laravel-localization/src/Mcamara/LaravelLocalization/Middleware/LaravelLocalizationRedirectFilter.php(45): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#41 /home/wilgatri/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Mcamara\\LaravelLocalization\\Middleware\\LaravelLocalizationRedirectFilter->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#42 /home/wilgatri/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#43 /home/wilgatri/public_html/vendor/mcamara/laravel-localization/src/Mcamara/LaravelLocalization/Middleware/LocaleSessionRedirect.php(56): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#44 /home/wilgatri/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Mcamara\\LaravelLocalization\\Middleware\\LocaleSessionRedirect->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#45 /home/wilgatri/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#46 /home/wilgatri/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#47 /home/wilgatri/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(682): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#48 /home/wilgatri/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(657): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#49 /home/wilgatri/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(623): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#50 /home/wilgatri/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(612): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#51 /home/wilgatri/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#52 /home/wilgatri/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#53 /home/wilgatri/public_html/app/Http/Middleware/GeneralChecks.php(25): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#54 /home/wilgatri/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): app\\Http\\Middleware\\GeneralChecks->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#55 /home/wilgatri/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#56 /home/wilgatri/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(75): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#57 /home/wilgatri/public_html/app/Http/Middleware/VerifyCsrfToken.php(24): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#58 /home/wilgatri/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): App\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#59 /home/wilgatri/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#60 /home/wilgatri/public_html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#61 /home/wilgatri/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#62 /home/wilgatri/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#63 /home/wilgatri/public_html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#64 /home/wilgatri/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#65 /home/wilgatri/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#66 /home/wilgatri/public_html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#67 /home/wilgatri/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#68 /home/wilgatri/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#69 /home/wilgatri/public_html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#70 /home/wilgatri/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#71 /home/wilgatri/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#72 /home/wilgatri/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#73 /home/wilgatri/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#74 /home/wilgatri/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#75 /home/wilgatri/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#76 /home/wilgatri/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#77 /home/wilgatri/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#78 /home/wilgatri/public_html/public/index.php(51): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#79 {main}
"}

**Comment by samdb** [comment]
This is not an Attendize-specific error. Please check your MySQL server settings first.
