### ISSUE TITLE
Strong Customer Authentication | Stripe

### ISSUE THREAD

**Issue by Tuvens** [Attendize/Attendize#665]
Hi,

I am not a developer, but I would like to ask my developer to work on Strong Customer Authentication in Stripe to ensure two-factor authentication, either as a separate checkout page or within the Attendize payment flow via the Payment Intents API.

I would like to know if there is someone else working on this feature in the Attendize community.

**Comment by scottybo** [comment]
This is an extremely important thing to do - without it we could be see cart rejection sky rocket.

Could we get some clarification on this from the Attendize team?

More information on this can be found here: https://stripe.com/gb/payments/strong-customer-authentication

**Comment by samdb** [comment]
Attendize relies on Omnipay's Stripe module to handle Stripe payments.

There is an upgrade to the Omnipay Stripe module to support SCA that is currently under development here: https://github.com/thephpleague/omnipay-stripe/pull/128

Once this is merged officially we will start testing it with Attendize.

**Comment by scottybo** [comment]
@samdb - it looks like this is now merged. Do you have a schedule for testing it with Attendize? (I need to report back to clients as to when we will be getting this sorted).

Thanks in advance

**Comment by samdb** [comment]
It's still not merged to a release but we've been testing off of the master. It has caused us to refactor some other bits of the checkout process but we are nearly there.

**Comment by scottybo** [comment]
Great to hear

**Comment by jeremyquinton** [comment]
Need some feedback here https://github.com/thephpleague/omnipay-stripe/pull/128#issuecomment-525920915 before I can open a PR with my changes

**Comment by jeremyquinton** [comment]
Here is the branch which is WIP https://github.com/Attendize/Attendize/compare/stripe-sca-payment

**Comment by scottybo** [comment]
Any news on when this will be released? SCA is going live by the end of next week...

**Comment by scottybo** [comment]
@jeremyquinton sorry to pester, but time is running out very quickly..

**Comment by jeremyquinton** [comment]
@scottybo there is a PR https://github.com/Attendize/Attendize/pull/683/files waiting to go which should be merged in soon. Main concern is that we have to run off 
```omnipay/stripe": "3.1.x-dev"```
 as that has not been merged here https://github.com/thephpleague/omnipay-stripe/pull/128

**Comment by clawfire** [comment]
> as that has not been merged here [thephpleague/omnipay-stripe#128](https://github.com/thephpleague/omnipay-stripe/pull/128)

Seems it's now merged :)

**Comment by jeremyquinton** [comment]
@clawfire 👍

**Comment by jeremyquinton** [comment]
This has now merged https://github.com/Attendize/Attendize/pull/683 so closing this issue off.

**Comment by scottybo** [comment]
Brilliant, thank you!

**Comment by clawfire** [comment]
When can we expect a release for that? Like ... Is `master` code stable. Because you guys stopped using tags and release mechanism in May 2019 :/
