### ISSUE TITLE
Code style fixes

### ISSUE THREAD

**Issue by ArmCM** [Attendize/Attendize#669]
### Coding Style

We follow the same coding style as the [Laravel](https://laravel.com/docs/contributions#coding-style) project which is the [PSR-2](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md) coding standard

Below is an example of a valid Laravel documentation block. Note that the `@param` attribute **is followed by two spaces, the argument type, two more spaces, and finally the variable name**:

```
/**
 * Register a binding with the container.
 *
 * @param  string|array  $abstract
 * @param  \Closure|string|null  $concrete
 * @param  bool  $shared
 * @return void
 * @throws \Exception
 */
public function bind($abstract, $concrete = null, $shared = false)
{
    //
}
```

**Comment by etiennemarais** [comment]
@ArmCM We have recently upgraded the project to use the latest laravel version _(6.5.1 at the time of writing)_

We are also looking at hooking this up to a github action/styleCI at some point but I am closing this issue for the moment.
