### ISSUE TITLE
QR Code Scanner Issues

### ISSUE THREAD

**Issue by DeathCamel58** [Attendize/Attendize#675]
I've been doing some digging into past issues on here, unfortunately none of the fixes work.

When I'm attempting to check someone in using the QR Scanner, I'm getting the blue screen people have previously had issues with.

![Blue screen with console open](https://user-images.githubusercontent.com/37940282/63022987-13d84300-be72-11e9-9deb-628956003f47.png)

As a heads up, I have allowed access to the camera, and the site is being served over HTTPS.

I've tried multiple different browsers, all of which are showing the same issue. Browsers I've tested are logged below:

### Vivaldi:
Vivaldi | 2.6.1566.49 (Stable channel) (64-bit)
-- | --
Revision | d126d99a97ff62b9503aa8f44003e70741c4d90f
OS | Linux
JavaScript | V8 7.5.288.30
Flash | 32.0.0.238 /home/deathcamel57/.config/google-chrome/PepperFlash/32.0.0.238/libpepflashplayer.so
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.145 Safari/537.36 Vivaldi/2.6.1566.49
Command Line | /usr/bin/vivaldi-stable --flag-switches-begin --allow-insecure-localhost --disable-accelerated-2d-canvas --enable-devtools-experiments --enable-gpu-rasterization --enable-oop-rasterization --enable-dom-distiller --ignore-gpu-blacklist --enable-features=NewTabLoadingAnimation,SiteSettings,WebAssemblyThreads,WebRTCPipeWireCapturer --flag-switches-end --save-page-as-mhtml

### Chrome
Google Chrome | 75.0.3770.142 (Official Build) (64-bit)
-- | --
Revision | 8d93477bd18154c67a70a67019cb8032382c55dd-refs/branch-heads/3770@{#1160}
OS | Linux
JavaScript | V8 7.5.288.30
Flash | 32.0.0.238 /home/deathcamel57/.config/google-chrome/PepperFlash/32.0.0.238/libpepflashplayer.so
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36
Command Line | /usr/bin/google-chrome-stable --flag-switches-begin --flag-switches-end

### Chrome (Android 8.0.0)
Google Chrome | 76.0.3809.89 (Official Build) (32-bit)
-- | --
Revision | 875a9f7de5d3a7aff4cb5c5ffec2849622368289-refs/branch-heads/3809@{#973}
OS | Android 8.0.0; moto e5 play Build/ODP27.91-121-14
Google Play services | SDK=12848000; Installed=18382017; Access=1p
JavaScript | V8 7.6.303.28
User Agent | Mozilla/5.0 (Linux; Android 8.0.0; moto e5 play) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.89 Mobile Safari/537.36

### EDIT:
I forgot some extremely relevant information.

The specific error that's logged is `Couldn't find enough finder patterns`
I'm using Attendize v1.3.0, from the releases page.

**Comment by scottyeung** [comment]
Encountered this issue myself, more like the issue the part of `navigator.GetUserMedia` rather than the QRcode part...

**Comment by scottyeung** [comment]
Here's the crude fix I applied to make it work, more like an trial and error thing...

`
initScanner: function () {
 
            var that = this;
            this.isScanning = true;
            this.scanResult = false;
 
            /*
             If the scanner is already initiated clear it and start over.
             */
            if (this.isInit) {
                clearTimeout(this.QrTimeout);
                this.QrTimeout = setTimeout(function () {
                    that.captureQrToCanvas();
                }, 500);
                return;
            }
 
            qrcode.callback = this.QrCheckin;
 
            // FIX SAFARI CAMERA
            if (navigator.mediaDevices === undefined) {
                navigator.mediaDevices = {};
            }
 
            if (navigator.mediaDevices.getUserMedia === undefined) {
                navigator.mediaDevices.getUserMedia = function(constraints) {
                    var getUserMedia = navigator.webkitGetUserMedia || navigator.mozGetUserMedia;
 
                    if (!getUserMedia) {
                        return Promise.reject(new Error('getUserMedia is not implemented in this browser'));
                    }
 
                    return new Promise(function(resolve, reject) {
                        getUserMedia.call(navigator, constraints, resolve, reject);
                    });
                }
            }
 
            navigator.mediaDevices.getUserMedia({
                video: {
                    facingMode: "environment" //TODO: Add switch to toggle "user" or "enviroment"
                },
                audio: false
            }).then(function(stream) {
                that.stream = stream;
 
                if (that.videoElement.mozSrcObject !== undefined) { // works on firefox now
                    that.videoElement.mozSrcObject = stream;
                } else if(window.URL) { // and chrome, but must use https
                    that.videoElement.srcObject = stream;
                };
            }).catch(function(err) {
                console.log(err.name + ": " + err.message);
                alert(lang("checkin_init_error"));
            });
 
            this.isInit = true;
            this.QrTimeout = setTimeout(function () {
                that.captureQrToCanvas();
            }, 500);
 
        }
`

**Comment by DeathCamel58** [comment]
I really appreciate it! Thanks so much!

**Comment by mstaack** [comment]
on ios chrome this still does not work. so use safari for now.
relevant chrome/apple issue: https://bugs.chromium.org/p/chromium/issues/detail?id=752458

**Comment by scottyeung** [comment]
This scanner works way better than the current llqrcode, you can also fallback to us camera to capture image and decode, then post the result to the server.
https://github.com/gruhn/vue-qrcode-reader

**Comment by gerogr** [comment]
With latest release I have the same issue! Blue screen and it's not possible to scan Qr code. I tried with Chrome, Vivaldi and Firefox from Macbook and Chrome and Firefox from Android.

**Comment by scottyeung** [comment]
I will open a PR for that

> With latest release I have the same issue! Blue screen and it's not possible to scan Qr code. I tried with Chrome, Vivaldi and Firefox from Macbook and Chrome and Firefox from Android.

**Comment by gerogr** [comment]
Many thanks @scottyeung

**Comment by techepet** [comment]
@scottyeung were you able to implement using https://github.com/Attendize/Attendize/issues/675#issuecomment-527720273
if so could you provide me some assistance into how? I am 0 skilled at programming, apologies.

**Comment by oluwaseun-ebenezer** [comment]
The solution above https://github.com/Attendize/Attendize/issues/675#issuecomment-521690923 doesn't solve the QR Scanning problem at my end. Please, is there any way out?
