### ISSUE TITLE
Check-in function not working | Accessing camera but not displaying on screen

### ISSUE THREAD

**Issue by Tuvens** [Attendize/Attendize#677]
Hi,

I have a demo set up on https. When I go to validate a ticket the check-in function does not access the camera, all I get is a blue screen. The frustrating thing is that the camera does seem to be accessed, as the LED activates beside the lense and the browser tab indicates the camera has been accessed.

We'd tried chrome and firefox on Android and Windows PC and its not working.

Any ideas what this could relate to?

**Comment by Tuvens** [comment]
@samdb @jeremyquinton @anyone!

We set up a new instance of Attendize and the ticket validation is still not working. Is anyone else having this problem?

We just get a blue screen, so the app access the camera but nothing displays on screen and the web app cannot scan the QR codes.

**Comment by Tuvens** [comment]
Error we're seeing: Uncaught: Couldn't find enough finder patterns

**Comment by shreyanshpanchal** [comment]
Hi,
Please refer to #675

**Comment by Tuvens** [comment]
@shreyanshpanchal 

Thanks
