### ISSUE TITLE
Refund Issue

### ISSUE THREAD

**Issue by Reece0Connor** [Attendize/Attendize#684]
Seems to be an issue with Refunds since the new SCA Gateway update, getting this error

" Unrecognized request URL (POST: /v1/payment_intents//cancel). If you are trying to list objects, remove the trailing slash. If you are trying to retrieve an object, make sure you passed a valid (non-empty) identifier in your code. Please see https://stripe.com/docs or we can help at https://support.stripe.com/ "

When you check the post request all seems to be fine, I've tried the normal stripe gateway and still receiving this error, if anyone knows a fix it would be great if not I'll let you know if we find anything.

**Comment by jeremyquinton** [comment]
@Reece0Connor did you run the migrations? The payment intent for SCA is stored against the orders table does your orders table have payment_intent column.

**Comment by jeremyquinton** [comment]
@Reece0Connor I managed to replicated this error. 

When testing the SCA payment journey you need to use the following card number
4000 0000 0000 3063

When testing the Stripe payment journey you need to use the following card number
4242 4242 4242 4242 

I'll get this added to the docs.

**Comment by Reece0Connor** [comment]
This was on a fresh install @jeremyquinton, was on a live stripe test so dummy cards do not come into play.

**Comment by jeremyquinton** [comment]
@Reece0Connor ok so I tested a live transaction to. 

Here is what is happening. When you do an SCA payment it's supposed to redirect you to a third party page where the user enters some additional information that they were sent via their bank. 

However in some cases users aren't redirected and the payment goes through without a re-direction. This means that the transaction will not have a payment intent. Then when the code is trying to refund it excepts the payment intent to be set. I will need to look at how we solve this as its an edge case.

For now you should be able to refund via the stripe dashboard. Not ideal but a work around for now.
