### ISSUE TITLE
Unable to install, keep getting weird errors

### ISSUE THREAD

**Issue by blumedia85** [Attendize/Attendize#69]
Here's a dump of the log file

[2016-04-18 18:36:08] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Cannot redeclare class CreateUsersTable' in /home/blumedia85/public_html/framework/database/migrations/2014_10_12_000000_create_users_table.php:34
Stack trace:
#0 /home/blumedia85/public_html/framework/bootstrap/cache/compiled.php(2088): Symfony\Component\Debug\Exception\FatalErrorException->__construct()
#1 /home/blumedia85/public_html/framework/bootstrap/cache/compiled.php(2083): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError()
#2 /home/blumedia85/public_html/framework/bootstrap/cache/compiled.php(0): Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#3 /home/blumedia85/public_html/framework/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(271): Illuminate\Filesystem\Filesystem->requireOnce()
#4 /home/blumedia85/public_html/framework/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(83): Illuminate\Database\Migrations\Migrator->requireFiles()
#5 /home/blumedia85/public_html/framework/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(74): Illuminate\Database\Migrations\Migrator->run()
#6 /home/blumedia85/public_html/framework/bootstrap/cache/compiled.php(1181): Illuminate\Database\Console\Migrations\MigrateCommand->fire()
#7 /home/blumedia85/public_html/framework/bootstrap/cache/compiled.php(1181): call_user_func_array:{/home/blumedia85/public_html/framework/bootstrap/cache/compiled.php:1181}()
#8 /home/blumedia85/public_html/framework/vendor/laravel/framework/src/Illuminate/Console/Command.php(150): Illuminate\Container\Container->call()
#9 /home/blumedia85/public_html/framework/vendor/symfony/console/Command/Command.php(256): Illuminate\Console\Command->execute()
#10 /home/blumedia85/public_html/framework/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Symfony\Component\Console\Command\Command->run()
#11 /home/blumedia85/public_html/framework/vendor/laravel/framework/src/Illuminate/Console/Application.php(62): Illuminate\Console\Command->run()
#12 /home/blumedia85/public_html/framework/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(159): Illuminate\Console\Application->call()
#13 /home/blumedia85/public_html/framework/bootstrap/cache/compiled.php(6019): Illuminate\Foundation\Console\Kernel->call()
#14 /home/blumedia85/public_html/framework/app/Http/Controllers/InstallerController.php(117): Illuminate\Support\Facades\Facade::__callStatic()
#15 /home/blumedia85/public_html/framework/app/Http/Controllers/InstallerController.php(117): Illuminate\Support\Facades\Artisan::call()
#16 /home/blumedia85/public_html/framework/bootstrap/cache/compiled.php(8844): App\Http\Controllers\InstallerController->postInstaller()
#17 /home/blumedia85/public_html/framework/bootstrap/cache/compiled.php(8844): call_user_func_array:{/home/blumedia85/public_html/framework/bootstrap/cache/compiled.php:8844}()
#18 /home/blumedia85/public_html/framework/bootstrap/cache/compiled.php(8913): Illuminate\Routing\Controller->callAction()
#19 /home/blumedia85/public_html/framework/bootstrap/cache/compiled.php(8893): Illuminate\Routing\ControllerDispatcher->call()
#20 /home/blumedia85/public_html/framework/bootstrap/cache/compiled.php(9555): Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}()
#21 /home/blumedia85/public_html/framework/bootstrap/cache/compiled.php(9555): call_user_func:{/home/blumedia85/public_html/framework/bootstrap/cache/compiled.php:9555}()
#22 /home/blumedia85/public_html/framework/bootstrap/cache/compiled.php(9537): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#23 /home/blumedia85/public_html/framework/bootstrap/cache/compiled.php(9537): call_user_func:{/home/blumedia85/public_html/framework/bootstrap/cache/compiled.php:9537}()
#24 /home/blumedia85/public_html/framework/bootstrap/cache/compiled.php(8894): Illuminate\Pipeline\Pipeline->then()
#25 /home/blumedia85/public_html/framework/bootstrap/cache/compiled.php(8879): Illuminate\Routing\ControllerDispatcher->callWithinStack()
#26 /home/blumedia85/public_html/framework/bootstrap/cache/compiled.php(7833): Illuminate\Routing\ControllerDispatcher->dispatch()
#27 /home/blumedia85/public_html/framework/bootstrap/cache/compiled.php(7804): Illuminate\Routing\Route->runWithCustomDispatcher()
#28 /home/blumedia85/public_html/framework/bootstrap/cache/compiled.php(7457): Illuminate\Routing\Route->run()
#29 /home/blumedia85/public_html/framework/bootstrap/cache/compiled.php(9555): Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#30 /home/blumedia85/public_html/framework/bootstrap/cache/compiled.php(9555): call_user_func:{/home/blumedia85/public_html/framework/bootstrap/cache/compiled.php:9555}()
#31 /home/blumedia85/public_html/framework/bootstrap/cache/compiled.php(9537): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#32 /home/blumedia85/public_html/framework/bootstrap/cache/compiled.php(9537): call_user_func:{/home/blumedia85/public_html/framework/bootstrap/cache/compiled.php:9537}()
#33 /home/blumedia85/public_html/framework/bootstrap/cache/compiled.php(7458): Illuminate\Pipeline\Pipeline->then()
#34 /home/blumedia85/public_html/framework/bootstrap/cache/compiled.php(7446): Illuminate\Routing\Router->runRouteWithinStack()
#35 /home/blumedia85/public_html/framework/bootstrap/cache/compiled.php(7431): Illuminate\Routing\Router->dispatchToRoute()
#36 /home/blumedia85/public_html/framework/bootstrap/cache/compiled.php(2303): Illuminate\Routing\Router->dispatch()
#37 /home/blumedia85/public_html/framework/bootstrap/cache/compiled.php(9555): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
#38 /home/blumedia85/public_html/framework/bootstrap/cache/compiled.php(9555): call_user_func:{/home/blumedia85/public_html/framework/bootstrap/cache/compiled.php:9555}()
#39 /home/blumedia85/public_html/framework/app/Http/Middleware/GeneralChecks.php(25): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#40 /home/blumedia85/public_html/framework/bootstrap/cache/compiled.php(9547): app\Http\Middleware\GeneralChecks->handle()
#41 /home/blumedia85/public_html/framework/bootstrap/cache/compiled.php(9547): call_user_func_array:{/home/blumedia85/public_html/framework/bootstrap/cache/compiled.php:9547}()
#42 /home/blumedia85/public_html/framework/bootstrap/cache/compiled.php(2927): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#43 /home/blumedia85/public_html/framework/app/Http/Middleware/VerifyCsrfToken.php(24): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle()
#44 /home/blumedia85/public_html/framework/bootstrap/cache/compiled.php(9547): App\Http\Middleware\VerifyCsrfToken->handle()
#45 /home/blumedia85/public_html/framework/bootstrap/cache/compiled.php(9547): call_user_func_array:{/home/blumedia85/public_html/framework/bootstrap/cache/compiled.php:9547}()
#46 /home/blumedia85/public_html/framework/bootstrap/cache/compiled.php(12875): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#47 /home/blumedia85/public_html/framework/bootstrap/cache/compiled.php(9547): Illuminate\View\Middleware\ShareErrorsFromSession->handle()
#48 /home/blumedia85/public_html/framework/bootstrap/cache/compiled.php(9547): call_user_func_array:{/home/blumedia85/public_html/framework/bootstrap/cache/compiled.php:9547}()
#49 /home/blumedia85/public_html/framework/bootstrap/cache/compiled.php(11498): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#50 /home/blumedia85/public_html/framework/bootstrap/cache/compiled.php(9547): Illuminate\Session\Middleware\StartSession->handle()
#51 /home/blumedia85/public_html/framework/bootstrap/cache/compiled.php(9547): call_user_func_array:{/home/blumedia85/public_html/framework/bootstrap/cache/compiled.php:9547}()
#52 /home/blumedia85/public_html/framework/bootstrap/cache/compiled.php(12616): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#53 /home/blumedia85/public_html/framework/bootstrap/cache/compiled.php(9547): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle()
#54 /home/blumedia85/public_html/framework/bootstrap/cache/compiled.php(9547): call_user_func_array:{/home/blumedia85/public_html/framework/bootstrap/cache/compiled.php:9547}()
#55 /home/blumedia85/public_html/framework/bootstrap/cache/compiled.php(12555): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#56 /home/blumedia85/public_html/framework/bootstrap/cache/compiled.php(9547): Illuminate\Cookie\Middleware\EncryptCookies->handle()
#57 /home/blumedia85/public_html/framework/bootstrap/cache/compiled.php(9547): call_user_func_array:{/home/blumedia85/public_html/framework/bootstrap/cache/compiled.php:9547}()
#58 /home/blumedia85/public_html/framework/bootstrap/cache/compiled.php(2977): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#59 /home/blumedia85/public_html/framework/bootstrap/cache/compiled.php(9547): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle()
#60 /home/blumedia85/public_html/framework/bootstrap/cache/compiled.php(9547): call_user_func_array:{/home/blumedia85/public_html/framework/bootstrap/cache/compiled.php:9547}()
#61 /home/blumedia85/public_html/framework/bootstrap/cache/compiled.php(9537): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#62 /home/blumedia85/public_html/framework/bootstrap/cache/compiled.php(9537): call_user_func:{/home/blumedia85/public_html/framework/bootstrap/cache/compiled.php:9537}()
#63 /home/blumedia85/public_html/framework/bootstrap/cache/compiled.php(2250): Illuminate\Pipeline\Pipeline->then()
#64 /home/blumedia85/public_html/framework/bootstrap/cache/compiled.php(2233): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#65 /home/blumedia85/public_html/framework/public/index.php(52): Illuminate\Foundation\Http\Kernel->handle()
#66 /home/blumedia85/public_html/framework/public/index.php(0): {main}()
#67 {main

**Comment by daveearley** [comment]
The latest push should work now. Let me know if you get any further errors. Cheers

**Comment by blumedia85** [comment]
Issue not resolved

**Comment by daveearley** [comment]
Try running *php artisan clear-compiled*, and then running the installer.

**Comment by blumedia85** [comment]
Resolved thats I did a manual install the installer kept doing weird stuff
