### ISSUE TITLE
Adicionar Mercado Pago

### ISSUE THREAD

**Issue by rjmvaz** [Attendize/Attendize#692]
Gostaria de saber como adicionar o Mercado pago, como meio de pagamento.
Version 1.0.0

**Comment by fhferreira** [comment]
https://www.attendize.com/payment_gateways.html

**Comment by techepet** [comment]
@rjmvaz pudiste? can you explain how? thanks!

**Comment by etiennemarais** [comment]
Please look at my reply in #696
