### ISSUE TITLE
We'll be back soon We're currently making improvements to our website.

### ISSUE THREAD

**Issue by messidiq** [Attendize/Attendize#695]
can you guys help me ? find out ![image](https://user-images.githubusercontent.com/22187541/66305423-7ce7ae80-e929-11e9-994b-96423e565abf.png)

**Comment by samdb** [comment]
There are lots of reasons this might appear. We will need to see your log files to help debug this @messidiq

**Comment by messidiq** [comment]
> There are lots of reasons this might appear. We will need to see your log files to help debug this @messidiq

And where to find it ?

**Comment by Ezyweb-uk** [comment]
For me it was the PHP mysqld extension missing from my PHP  configuration, but your log file at \storage\logs\laravel.log should hopefully poiint you in the right direction.

**Comment by CountParadox** [comment]
same thing happens for me using docker.... no log file :(

**Comment by cherif-bayo** [comment]
i get the same issue after installation . is some one knows how to fixe it ? thank u

**Comment by etiennemarais** [comment]
@cherif-bayo @CountParadox Please can you talk us through your setup steps to get to this issue?

My initial feeling is that the app never comes out of maintenance mode properly. What happens if you run `php artisan up` ? Does it come back up?

**Comment by cherif-bayo** [comment]
hey ,
everything is good now . juste restart my computer :) .

Thanks

**Comment by etiennemarais** [comment]
Good to hear :)
