### ISSUE TITLE
Unable to setup paypal

### ISSUE THREAD

**Issue by my2k** [Attendize/Attendize#696]
Hello There,

Just installed the platform and followed all installation steps.

At account panel I am unable to setup paypal account as there is no dropdown.

It shows Stripe SCA and Stripe and Dummy, please see attached screenshot.

![screencapture-ibusinessolution-organiser-1-events-2019-10-09-17_17_07](https://user-images.githubusercontent.com/5006847/66479064-55275080-eab9-11e9-838b-15a63ffad115.png)

Please help as it is urgent.

Thanks

**Comment by fhferreira** [comment]
As I've seen into docs you will need to do it manually to install **paypal**

https://www.attendize.com/payment_gateways.html

**Comment by fhferreira** [comment]
https://github.com/Attendize/Attendize/issues/620

**Comment by mwphglga** [comment]
I am having the same issue. I was running 1.2 and upgraded to 1.3 and my paypal configuration disappeared. In the database i notice that my payment gateway info moved to a new table and the paypal info was deleted from the new db. Is there a new way of configuring PayPal?

**Comment by CristianDeluxe** [comment]
The Paypal payment gateway has been deleted because the way to manage payments has been completely changed, it has to be created again.

You can wait for someone to implement it or implement it yourself.

I would love to do it myself, but the truth is that I don't have much time right now.

The only solution right now is to go back to the previous version or use Stripe.

**Comment by etiennemarais** [comment]
@my2k Thank you for raising this issue. Unfortunately we do not support paypal anymore, and the documentation is also unfortunately outdated :( I will update the docs.

We need to have an internal discussion about supporting more payment methods first but for the time being Stripe is the way to go. @CristianDeluxe please can you link to the correct version? 

Unfortunately we are only getting into tagging proper versions now with the #721 release and hopefully we will be getting better at it going forward. I am sorry if there were any confusion.

**Comment by CristianDeluxe** [comment]
I think the last version where Paypal worked is this one:

https://github.com/Attendize/Attendize/tree/ee01292f53064720dba6b5c6c3292390fd469bb8

I hope, @etiennemarais , that the result of that discussion is that: yes you can add more payment gateways, the only problem I see is that if we add to the official repository of Attendize gateways made by third parties may become obsolete and it would be difficult to maintain them (being many specific to each country).

We'd have to think of a way to add one as you add a payment gateway to Omnipay, plugin style, 

This would give a great flexibility to the platform and avoid having to modify controllers and views to add a new gateway, although in my opinion Paypal should come back, is one of the most used gateways in the world and many people who use Attendize are using it from the beginning.

**Comment by vladi550821** [comment]
Hi, the version above doesn't show PayPal as option. Is there anywhere description how activate it? Or a version with Paypal?

**Comment by mwphglga** [comment]
Version 1.26 had PayPal working.. You may have to pull a few blades from
the later version to get some other functionality working.. ie password
resets..
