### ISSUE TITLE
Unable to fill up database during installation

### ISSUE THREAD

**Issue by tomtomklima** [Attendize/Attendize#70]
**While using manual install, i get stuck at this:**

[Illuminate\Database\QueryException]                                           
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'picker_format' in 'field list' (SQL: insert into `datetime_formats` (`format`, `picker_format`, `label`) values (d/M/Y g:i a, , 10/Mar/2016))                                    
                                                      
[PDOException]
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'picker_format' in 'field list'

**log output:**

[2016-04-18 18:18:39] developement.ERROR: exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'picker_format' in 'field list'$
Stack trace:
#0 /var/www/html/attendize/vendor/laravel/framework/src/Illuminate/Database/Connection.php(408): PDO->prepare('insert into `da...')
#1 /var/www/html/attendize/vendor/laravel/framework/src/Illuminate/Database/Connection.php(666): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(I$
#2 /var/www/html/attendize/vendor/laravel/framework/src/Illuminate/Database/Connection.php(629): Illuminate\Database\Connection->runQueryCallback('insert into `da...',$
#3 /var/www/html/attendize/vendor/laravel/framework/src/Illuminate/Database/Connection.php(409): Illuminate\Database\Connection->run('insert into `da...', Array, Objec$
#4 /var/www/html/attendize/vendor/laravel/framework/src/Illuminate/Database/Connection.php(365): Illuminate\Database\Connection->statement('insert into `da...', Array)
#5 /var/www/html/attendize/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php(32): Illuminate\Database\Connection->insert('insert into `da$
#6 /var/www/html/attendize/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1963): Illuminate\Database\Query\Processors\Processor->processInsertGetId$
#7 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id')
#8 /var/www/html/attendize/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1337): call_user_func_array(Array, Array)
#9 /var/www/html/attendize/bootstrap/cache/compiled.php(10791): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
#10 /var/www/html/attendize/bootstrap/cache/compiled.php(10791): Illuminate\Database\Eloquent\Builder->insertGetId(Array, 'id')
#11 /var/www/html/attendize/bootstrap/cache/compiled.php(10780): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
#12 /var/www/html/attendize/bootstrap/cache/compiled.php(10731): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder), Array)
#13 /var/www/html/attendize/bootstrap/cache/compiled.php(10391): Illuminate\Database\Eloquent\Model->save()
#14 /var/www/html/attendize/database/seeds/ConstantsSeeder.php(358): Illuminate\Database\Eloquent\Model::create(Array)
#15 /var/www/html/attendize/vendor/laravel/framework/src/Illuminate/Database/Seeder.php(39): ConstantsSeeder->run()
#16 /var/www/html/attendize/database/seeds/DatabaseSeeder.php(16): Illuminate\Database\Seeder->call('ConstantsSeeder')
#17 /var/www/html/attendize/vendor/laravel/framework/src/Illuminate/Database/Console/Seeds/SeedCommand.php(63): DatabaseSeeder->run()
#18 /var/www/html/attendize/bootstrap/cache/compiled.php(11064): Illuminate\Database\Console\Seeds\SeedCommand->Illuminate\Database\Console\Seeds\{closure}()
#19 /var/www/html/attendize/vendor/laravel/framework/src/Illuminate/Database/Console/Seeds/SeedCommand.php(64): Illuminate\Database\Eloquent\Model::unguarded(Object(Cl$
#20 [internal function]: Illuminate\Database\Console\Seeds\SeedCommand->fire()
#21 /var/www/html/attendize/bootstrap/cache/compiled.php(1240): call_user_func_array(Array, Array)
#22 /var/www/html/attendize/vendor/laravel/framework/src/Illuminate/Console/Command.php(169): Illuminate\Container\Container->call(Array)
#23 /var/www/html/attendize/vendor/symfony/console/Command/Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArrayInput), Ob$
#24 /var/www/html/attendize/vendor/laravel/framework/src/Illuminate/Console/Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\C$
#25 /var/www/html/attendize/vendor/symfony/console/Application.php(791): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Sym$
#26 /var/www/html/attendize/vendor/symfony/console/Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Database\Console\Seeds\S$
#27 /var/www/html/attendize/vendor/symfony/console/Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArrayInput$
#28 /var/www/html/attendize/vendor/laravel/framework/src/Illuminate/Console/Application.php(64): Symfony\Component\Console\Application->run(Object(Symfony\Component\Co$
#29 /var/www/html/attendize/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(159): Illuminate\Console\Application->call('db:seed', Array)
#30 /var/www/html/attendize/bootstrap/cache/compiled.php(6291): Illuminate\Foundation\Console\Kernel->call('db:seed', Array)
#31 /var/www/html/attendize/app/Console/Commands/Install.php(57): Illuminate\Support\Facades\Facade::__callStatic('call', Array)
#32 /var/www/html/attendize/app/Console/Commands/Install.php(57): Illuminate\Support\Facades\Artisan::call('db:seed', Array)
#33 [internal function]: App\Console\Commands\Install->handle()
#34 /var/www/html/attendize/bootstrap/cache/compiled.php(1240): call_user_func_array(Array, Array)
#35 /var/www/html/attendize/vendor/laravel/framework/src/Illuminate/Console/Command.php(169): Illuminate\Container\Container->call(Array)
#36 /var/www/html/attendize/vendor/symfony/console/Command/Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Obj$
#37 /var/www/html/attendize/vendor/laravel/framework/src/Illuminate/Console/Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\C$
#38 /var/www/html/attendize/vendor/symfony/console/Application.php(791): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symf$
#39 /var/www/html/attendize/vendor/symfony/console/Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(App\Console\Commands\Install), Obje$
#40 /var/www/html/attendize/vendor/symfony/console/Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput)$
#41 /var/www/html/attendize/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Compo$
#42 /var/www/html/attendize/artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Conso$
#43 {main}

**Comment by daveearley** [comment]
This should be fixed now. Let me know if works.

**Comment by ylecuyer** [comment]
That's OK for me. Thank you.

`deploy@ubuntu:~/attendize$ php artisan attendize:install
PHP Notice:  Use of undefined constant MCRYPT_RIJNDAEL_128 - assumed 'MCRYPT_RIJNDAEL_128' in /home/deploy/attendize/config/app.php on line 95
Attempting to install Attendize v0.5.0
App key exists -- skipping
Migrating database
Seeding DB data
Success! You can now run Attendize
Navigate to /signup to create your account.`

**Comment by tomtomklima** [comment]
works, thaks!
