### ISSUE TITLE
Event date selector won't stay in focus

### ISSUE THREAD

**Issue by narcan** [Attendize/Attendize#703]
New Events created in the Demo Back-end Demo: (http://attendize.website/signup) can't select event dates. A down click on the date picker shows the options, but releasing the mouse button causes it to fade. Pasting a date into the field is not an option in the right click context menu.

**Comment by samdb** [comment]
We don't always keep the demo updated. Do you have the same issue on a fresh checkout of the latest code on GitHub?

**Comment by Adam-78** [comment]
It happens in chrome but works in IE

**Comment by Blueacedesign** [comment]
same issue in Brave browser on DEMO
