### ISSUE TITLE
Service fee percentage is not added to total

### ISSUE THREAD

**Issue by scottyeung** [Attendize/Attendize#719]
I found the revenue for the ticket is not reflecting the service fee percentage I added on. For example, if I added 12% to the service fee percentage, I supposed to get 62GBP for 5 tickets it's reflecting on Stripe for 56GBP.

**Comment by etiennemarais** [comment]
@scottyeung Thank you for reporting. This has been fixed in #721.

**Comment by etiennemarais** [comment]
Unfortunately there is no ETA yet but it will be shipped to master once we are happy with the stability of things. Please track #721 if you are keen to see the changes incoming.
