### ISSUE TITLE
Update from 1.0.0 to 1.3.0

### ISSUE THREAD

**Issue by webkultur** [Attendize/Attendize#727]
Hello,
We have current Attendize verison 1.0.0 running. Is there a procedere to update to 1.3.0?
How can I update to the latest version?

Thanks
Mathias

**Comment by etiennemarais** [comment]
@webkultur Unfortunately we haven't had the time to write a proper upgrade path onto each release and that is something I will do in the next while to make things easier for other people. Thank you for bringing it to our attention. 🙏 

To my knowledge the upgrade path should be straightforward as in the normal way of releasing a new version of a laravel app:

```sh
# Put the application into maintenance mode
php artisan down 

# Pull latest tag or master
git pull 

# Installs composer dependencies
composer install 

# PLEASE MAKE A BACKUP OF YOUR LIVE DATABASE SOMEWHERE

# Run migrations
php artisan migrate

# Clear caches
php artisan config:clear && php artisan cache:clear && php artisan view:clear && php artisan route:clear && php artisan optimize:clear && php artisan clear-compiled && composer dump-autoload

# Take the app out of maintenance mode
php artisan up
```

The frontend resources are bundled with the application so no need to build frontend again. We will move them out into webpack and laravel mix in the `next` release that will tag `v2.0.0`

## NOTE: Please make a backup of your database before running migrations. 

Please let me know if you run into any problems along the way?

**Comment by webkultur** [comment]
Hi,

I tried it, but received an error;

root@tf-test1 /var/web # php artisan migrate
[2019-12-23 14:46:34] production.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Class 'Illuminate\Notifications\NotificationServiceProvider' not found in /var/web/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php:146
Stack trace:
#0 /var/web/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(114): Illuminate\Foundation\ProviderRepository->createProvider('Illuminate\\Noti...')
#1 /var/web/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(60): Illuminate\Foundation\ProviderRepository->compileManifest(Array)
#2 /var/web/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(530): Illuminate\Foundation\ProviderRepository->load(Array)
#3 /var/web/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterProviders.php(17): Illuminate\Foundation\Application->registerConfiguredProviders()
#4 /var/web/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(203): Illuminate\Foundation\Bootstrap\RegisterProviders->bootstrap(Object(Illuminate\Foundation\Application))
#5 /var/web/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(219): Illuminate\Foundation\Application->bootstrapWith(Array)
#6 /var/web/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(105): Illuminate\Foundation\Console\Kernel->bootstrap()
#7 /var/web/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 {main}



  [Symfony\Component\Debug\Exception\FatalThrowableError]
  Class 'Illuminate\Notifications\NotificationServiceProvider' not found


any idea?
Thanks
Mathias

**Comment by etiennemarais** [comment]
@webkultur Please take a look at the latest version. It uses laravel 6.5. The above issue might be related to a bad laravel upgrade path or it not being followed.
