### ISSUE TITLE
CURDATE doesn't work within postgres

### ISSUE THREAD

**Issue by ylecuyer** [Attendize/Attendize#73]
see all occurrences with `grep 'CURDATE' -rni .`

**Comment by daveearley** [comment]
I'm not overly familiar with using postgres; is there an alternative to CURDATE that can be used?

**Comment by ylecuyer** [comment]
you should use CURRENT_DATE which is portable, i'm preparing a PR for postgresql support

**Comment by daveearley** [comment]
Brilliant, cheers!

**Comment by ylecuyer** [comment]
Fixed in PR #77
