### ISSUE TITLE
We'll be back soon

### ISSUE THREAD

**Issue by homebakecompany** [Attendize/Attendize#730]
Version 1.0.0

**Comment by homebakecompany** [comment]
unable to print pdf copy ...error showing up as We'll be back soon
We're currently making improvements to our website.

**Comment by JoaquinMVR** [comment]
Same here, Ubuntu 18.04.3, Apache/2.4.29 (Ubuntu), PHP 7.2.24-0ubuntu0.18.04.1 and Attendize v1.3.0.

**Comment by etiennemarais** [comment]
Please check if the application is in maintenance mode? I have a feeling it will work if you run `php artisan up` and then trying again? /cc @homebakecompany @JoaquinMVR

**Comment by JoaquinMVR** [comment]
Nope, I ran it, it said: `Application is already up.` and the problem persists.

**Comment by etiennemarais** [comment]
<img width="391" alt="Screenshot 2019-12-19 at 10 32 25" src="https://user-images.githubusercontent.com/4479918/71157541-dbdf7300-224a-11ea-8edc-d650d5d98bc6.png">

Looking at the above screenshot, That error is only in two places, `503`, `500`. After you ran application up, I am guessing it's not the `503` one but rather the `500`. 

If you go to your `/storage/logs/...`. What errors can you see in the logs?

**Comment by johannac** [comment]
Closing support ticket automatically after 7 days with no response.
