### ISSUE TITLE
Add attendees from csv

### ISSUE THREAD

**Issue by ylecuyer** [Attendize/Attendize#74]
It would be nice to add a list of attendees from a csv file

**Comment by daveearley** [comment]
I'll keep this open as it would be a nice feature. The [package](http://www.maatwebsite.nl/laravel-excel/docs/import) currently being used to export attendees also handles importing CSV files, so it shouldn't be too difficult to implement.

**Comment by DanHaas** [comment]
@ylecuyer a simple version has now been added csv needs First Name, Last Name and Email. Once I get some time I'll optimise and extend to generate a preview with add,edit and delete before committing.

**Comment by JapSeyz** [comment]
In addition to this;

Allow users to select who they are from a guest list upon purchasing a ticket.

**Use case:**
For private parties etc. where you can load in a list of possible guests, and then you select who you are when you purchase a ticket.

**Comment by ylecuyer** [comment]
thanks @DanHaas I'm going to test this week

**Comment by ylecuyer** [comment]
@DanHaas It works well, may be it may be mentioned somewhere that the format must be: 

```
first_name,last_name,email
doe,john,john.doe@example.com
```

**Comment by ylecuyer** [comment]
I think there should be only one order per import instead of one per attendee

**Comment by ylecuyer** [comment]
It doesn't import attendee with accents
