### ISSUE TITLE
Combatting Contact form Spam

### ISSUE THREAD

**Issue by frigginglorious** [Attendize/Attendize#740]
I'm not an expert on how bots scrape websites, but I know they're finding the contact form on our site and sending a bunch of spam.

I see that the Contact form is just a hidden div. The "Contact" button's click event looks like it just gets rid of the dipaly:none; on the contact form.

I'm thinkin if the form wasn't in the DOM to begin with, bots aren't good at javascript and wouldn't be able to fill in/submit the form. Should I rig up that contact button to generate the form HTML?

I'm sure other folks have had the same issue. Any creative solutions out there?

<img width="802" alt="image" src="https://user-images.githubusercontent.com/3982200/71312050-3c59e600-23ec-11ea-9a4b-6cc7e301e40f.png">

**Comment by samdb** [comment]
The most basic implementation that I have seen elsewhere is to have a field, hidden with CSS, that when filled out causes the form to appear to be submitted but the message is never transmitted on the server-side. There are probably more advanced ways of doing this but that would be a good start.

**Comment by frigginglorious** [comment]
That's a good idea, I'll look into it. Thanks!

**Comment by emekaorjiani** [comment]
Use google captcha here, I think that should work.
