### ISSUE TITLE
QR Scanner

### ISSUE THREAD

**Issue by lawer** [Attendize/Attendize#746]
I'm testing the software and It seems wonderful, but QR Scanning doesn¡t work.

I tested on Firefox on Mac and Chrome and Firefox on Android.

I¡m getting the "Couldn't find enough finder patterns" error.

Any ideas?

Thanks.

**Comment by clawfire** [comment]
Check #675 ;)

**Comment by RayhanYulanda** [comment]
@lawer  i just made mobile scanner with flutter framework for attendize check in. check my repo and give me some love ❤️💙💚💜💛😄
https://github.com/RayhanYulanda/Attendize-Scanner-Mobile
