### ISSUE TITLE
Several issues.

### ISSUE THREAD

**Issue by mitchellcrazyeye** [Attendize/Attendize#750]
I've been having issues with the mail configuration. I'm not a hugely technical guy, I didn't download this from an official download but used Softaculous for an auto install. 

I have a couple issues: 

1. When tickets are purchased, the site returns a "We'll be back soon. We're currently making improvements to our website." rather than showing the tickets.
2. The mail doesn't get sent at all, as much as my mail configuration seems to be set correctly. (Not much in terms of documentation on how to set this up)
3. When attempting to scan the tickets, the site never seems to ask permission to use the camera. (This ended up not being SSL & Chrome related, so its a problem somewhere else)
4. PDFs don't seem to want to be generated, the only way I can even get the ticket is by clicking download and removing the "?download=1"

I'm really hoping this to be something really simple that I have set wrong somewhere.

**Comment by johannac** [comment]
@mitchellcrazyeye hm.. without knowing more about how the auto-install from Softaculous was configured, there's nothing obvious here that is a known issue. You can try going through the troublshooting guide here http://www.attendize.com/troubleshooting.html. If you find any other information via the debug logs, please re-open this ticket and let us know. Thanks!
