### ISSUE TITLE
How to use API in postman?

### ISSUE THREAD

**Issue by RayhanYulanda** [Attendize/Attendize#752]
i need to test attendize.com/api/attendees/ but i'm still confusing how to use it and test it in postman. any ideas?
where should i put email password and api_token? header? form-data? or x-www-form-urlencoded?

```
Server : centos 7
SQL : mysql 10
php : 7.3
attendize version : latest
```

**Comment by mrlexley** [comment]
Only API Token is needed like https://tickets.website.com/api/attendees?api_token=
