### ISSUE TITLE
Install - First Run

### ISSUE THREAD

**Issue by Pilly170** [Attendize/Attendize#754]
Hi running the install the url changes from /install to /signup?first_run=yup

Yet the page goes blank.
How can I troubleshoot this? The only log available is laravel.log which had the error when I intitially typed the password incorrectly.

Its not : https://github.com/Attendize/Attendize/issues/609 as I have a password on the db user

**Comment by Pilly170** [comment]
This was due to having spaces within the "mail_from_name" in the .env

**Comment by robetus** [comment]
Thanks for sharing this, worked for me.
