### ISSUE TITLE
Stuck on we'll be back soon

### ISSUE THREAD

**Issue by ChukapiTCG** [Attendize/Attendize#761]
Hi,
I know i'm "uping" #513 and #695 but both ticket didn't help me.
First of all i'm not a devlopper : i'm new on github and i know only the basis (advanced) of ftp, administrating a website, sql, php and html.

At the beginning i tried to install Attendize through softaculous : i got a lot of problem like mail that didn't send and pdf than can't generate.

Here is my first time installing something with a command line (SSH).

I make it and i passed the "install" things but i'm stuck at the "We'll be back soon" page.

Can you help me to go through ?

Thanks :)

**Comment by travtaz997** [comment]
Make sure you run `php artisan key:generate` after running `php composer install`

**Comment by ChukapiTCG** [comment]
Thanks you for your reply : yes i made the point 5 of the installation. Do i have to make it again ?

**Comment by ChukapiTCG** [comment]
I delete the installation : I will try to reinstall it

**Comment by ChukapiTCG** [comment]
I reinstalled the website and still don't work :/

**Comment by itmm85** [comment]
The same thing happened to me when I first ran the installation. It can be multiple things so go to your ".env" file set APP_DEBUG=false to "true" and run install again. This won't fix the problem but it should give you a message as to why it can't finish the installation. In my case, I had to make three adjustments to my server settings for everything to run correctly.

**Comment by ChukapiTCG** [comment]
I will install again from the beginning and add the "true" in APP_DEBUG

**Comment by ChukapiTCG** [comment]
The log file says "Access denied to user@localhost" : this is something i don't understand because attendize create all the table in the db :/

**Comment by ChukapiTCG** [comment]
After a lot of retry I resolve my situation : I create a new user in database with all permission and it works. I'm not sure but I think it's due of the fact that my password have some special characters like # and @.
By the way this issue close.

**Comment by CloudLinuxDeveloper** [comment]
![Screenshot from 2020-07-05 16-53-20](https://user-images.githubusercontent.com/61201761/86531076-0c81b400-bee0-11ea-8f3f-2d8a045e35fb.png)

Hello, I am using Ubuntu 18.04 LTS. I have set app_debug=true and did all after review this troubleshooting. I am also having We'll be back soon
We're currently making improvements to our website.

I am using PHP 7.3.19
NGINX 
MySQL

Please check this bug effect the Attendize for ubuntu or not

**Comment by mikerouse** [comment]
Had the same. My DB password had a '#' symbol, so changed it for something more simple.
