### ISSUE TITLE
headless API frontend and admin frontend

### ISSUE THREAD

**Issue by ebredy** [Attendize/Attendize#762]
Presently Attendize uses laravel's blade template and passes in the values along with some jquery modals to create the frontend for both the user-facing UI and organizer facing UI.  I would like the ability to use an API version where the response is JSON response instead of laravel's template response.  the Use case is to be able to implement my own frontend UI using reactjs, react native,  angular or vuejs.  An addition this would allow for the ability.

**Comment by etiennemarais** [comment]
@ebredy Thank you for your contribution. Unfortunately we don't have capacity at this point in time to completely write up a full API. You are most welcome to fork this project and attempt to add one 🙏
