### ISSUE TITLE
laravel vapor serverless ready

### ISSUE THREAD

**Issue by ebredy** [Attendize/Attendize#763]
I would like to use this platform with vapor: https://docs.vapor.build/1.0/introduction.html#introduction

However, presently attendize is not compatible or meet the minimum requirements for vapor:
The mimum requirements are the following:
Vapor requires that your application be compatible with PHP 7.3+ and Laravel 6.0+.

and the assets in attendize is too massive for AWS serverless as it has a minimum of 300 assets.  if you remove the publics of attendize to an s3 bucket then that seems to work but it requires a workaround to get it to work.  It would be great if there was a way to make it easy to use this setup.

**Comment by etiennemarais** [comment]
We have upgraded Attendize to use laravel 6.5. Please try again? 🙏
