### ISSUE TITLE
Dashboard sales volume and orders not updated when orders are cancelled and refunded

### ISSUE THREAD

**Issue by BigBlockStudios** [Attendize/Attendize#766]
Dashboard sales volume and orders not updated when orders are cancelled and refunded. If I refund all ticket sales the sales volume will still have a dollar value.

**Comment by etiennemarais** [comment]
@BigBlockStudios Please check out https://github.com/Attendize/Attendize/releases/tag/v2.0.0 It fixed the stats on the dashboard 🙏
