### ISSUE TITLE
Payment options

### ISSUE THREAD

**Issue by justynpride** [Attendize/Attendize#779]
Following on from the 2.0 release I have made a fresh installation. I appear to only have payment options for  STRIPE, DUMMY/TEST GATEWAY & STRIPE SCA. 

Looking at the demo system and also the 2.0 readme there should be PayPal Express and Coinbase as well. Is this just a version difference or have I missed something?

**Comment by etiennemarais** [comment]
hi @justynpride we removed support for PayPal Express and Coinbase but forgot to amend the docs. Thank you for pointing that out 💪 We will be updating the docs shortly

/cc @samdb

**Comment by justynpride** [comment]
@etiennemarais Thanks for the confirmation, that all makes sense. Do you know if anyone is looking at developing for PayPal? some client I have use PayPal rather than Stripe.

**Comment by etiennemarais** [comment]
Unfortunately not in the short or medium term as far as I know. @jeremyquinton or @samdb might have more context around why we dropped support for those.

**Comment by justynpride** [comment]
@etiennemarais Thanks. It would be helpful to know reasoning, and if it was just technical someone might be able to pick up and resolve.
