### ISSUE TITLE
Access Codes

### ISSUE THREAD

**Issue by justynpride** [Attendize/Attendize#780]
Can anyone explain to me how the access codes feature is supposed to work? I've created codes, but cannot see where anyone would enter them, even on the event page. I can confirm that the event page is published. I'm using the 2.0 version.

**Comment by etiennemarais** [comment]
@justynpride The access codes adds functionality to tickets to have promotional tickets which are hidden from public view unless you type in a special code. 

Only hidden tickets can have access codes attached to them and there will be an input that shows on the event public page when an event has hidden tickets with codes attached to them. Only when a human types in the correct code will they see an option to show the promotional ticket and continue through the payment process. 

You also can't delete an access code once it's been used.

Please see #558 and #572 for more context.

**Comment by justynpride** [comment]
That is really helpful. Thank you.
