### ISSUE TITLE
Error SQLSTATE[42S01]

### ISSUE THREAD

**Issue by hanami001** [Attendize/Attendize#781]
Dear All,

I have a problem after click "Install" as shown below.

SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'password_resets' already exists (SQL: create table `password_resets` (`email` varchar(255) not null, `token` varchar(255) not null, `created_at` timestamp default CURRENT_TIMESTAMP not null) default character set utf8mb4 collate 'utf8mb4_unicode_ci')

**Comment by johannac** [comment]
@hanami001 this error occurs when you have already ran the install process. You can delete the tables from the database and start the installation over again. If you're still experiencing problems, please re-open a new ticket with all required fields for replicating the error filled out.
