### ISSUE TITLE
Turning off social settings error

### ISSUE THREAD

**Issue by justynpride** [Attendize/Attendize#782]
Anyone else have the ("whoops.. looks ---")  error when trying to save the social settings for an event? I'n running 2.0.1 and was trying to turn off a couple of the social types.

The details in the logs are:

`[2020-04-13 14:28:44] production.ERROR: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'social_show_facebook' cannot be null (SQL: update `events` set `social_show_facebook` = ?, `events`.`updated_at` = 2020-04-13 14:28:44 where `id` = 1) {"userId":1,"exception":"[object] (Illuminate\\Database\\QueryException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'social_show_facebook' cannot be null (SQL: update `events` set `social_show_facebook` = ?, `events`.`updated_at` = 2020-04-13 14:28:44 where `id` = 1) at /home/afamily1/public_html/attendize_test/vendor/laravel/framework/src/Illuminate/Database/Connection.php:669)
`

**Comment by etiennemarais** [comment]
@justynpride Thank you for pointing it out. I will take a look for you. 🙏

**Comment by justynpride** [comment]
@etiennemarais Thanks. I'm liking this system, and looking into how best it might work for my scenario, and then what we can add to this project if we use it.

**Comment by aayycee** [comment]
@justynpride I had the same issue when trying to disable some of the social sharing buttons. A buddy suggested I comment out that section of the page in the blade template.

File name: EventPage.blade.php
` {{-- @include('Public.ViewEvent.Partials.EventShareSection') --}}`

**Comment by justynpride** [comment]
@aayycee Thanks for the helpful suggestion until there is a bug fix.

**Comment by aayycee** [comment]
@justynpride I forgot to tell you that this share also shows up on the EventPageViewOrder.blade.php

**Comment by johannac** [comment]
Fixed via #906
