### ISSUE TITLE
[FEATURE] Attendee Information Collection / Attendee Profile

### ISSUE THREAD

**Issue by travtaz997** [Attendize/Attendize#783]
This is a great system that I have tons of use for and am excited to use it!  One feature that I think would be extremely beneficial to a system like this would be to have more of an Attendee Profile where Event Organizers can create multiple required or optional text/dropdown fields when purchasing tickets.  Examples would be if each ticket holder gets a free tshirt, then you could great a dropdown field for TShirt size.  Or if you wanted to track food allergy information, you could have a field to enter any dietary restrictions / food allergies.

Ideally all of this information could be exported in a list for the Event Organizer.  But one step further would be to have it so each ticket holder has a scannable barcode/QR code, etc. that can be scanned by the program and pull up the persons "profile" with all the information they entered.

One real life example for this would be a Kids Camp project I'm currently working on for a customer.  Each kid will receive a bracelet, or nametag, with their name and a barcode.  All of our Camp Counselors will have a handheld tablet where at any moment they could scan a Kids barcode and pull up their Attendee Profile that would list any food allergies and emergency contacts.

**Comment by samdb** [comment]
@travtaz997 this can be achieved with the 'Surveys' option in Attendize, on the left nav bar with 'Event Tools'. You can define as many questions as you like and the fields are repeated for every ticket purchased. I use this myself for things like collecting dietary requirements.

It would be a good idea to make this data exportable though so I will tag this as a future enhancement.

**Comment by johannac** [comment]
@travtaz997 @samdb the survey data is exportable in the current version, if you go to surveys in the nav, there is a button at the top of the page to Export Answers. So I think all the basics are there and in good working order. But perhaps we could make the UI and navigation easier. The survey answers are only shown in the Surveys section, they aren't show when you look up an Order or an Attendee or check someone in on the Check-In page. So a more tighter integration would be a nice enhancement.
