### ISSUE TITLE
Your Ticket(s) link redirects to: We'll be back soon, We're currently making improvements to our website.

### ISSUE THREAD

**Issue by dasdboot** [Attendize/Attendize#785]
After the ticket is purchased on the confirmation page, when clicking on Your **Ticket(s)**  link it redirects to <domain name>/order/cPMez194/tickets?download=1
which lands on:
_We'll be back soon
We're currently making improvements to our website._
instead. 
Using the latest version 2.01
Is there a more stable version available which does not have this and the social network bug? Thanks!

**Comment by dasdboot** [comment]
also a confirmation email is not send, possibly due to the same issue

**Comment by dasdboot** [comment]
ok so after setting APP_DEBUG=true in .env
it appeared that 
NitMedia/wkhtml2pdf was troughing an error while attempting to load shared libraries: libfontconfig.so.1

sudo apt-get install libfontconfig fixed it in Debian

**Comment by johannac** [comment]
Great! Thanks for the update and glad you got it figured out!

**Comment by afahitech** [comment]
I have an issue installing Attendize. Please help me out as I am facing the issue "We'll be back soon
We're currently making improvements to our website."  Make all necessary changes APP_DEBUG=true
in .env but same issue faced.
![Screenshot from 2020-07-15 21-38-09](https://user-images.githubusercontent.com/57868100/87565659-bf71bf00-c6e3-11ea-871f-f4b5e49e8672.png)

**Comment by samdb** [comment]
@afahitech Please submit this as a new issue, following the issue template.
