### ISSUE TITLE
Help with Organiser Register screen

### ISSUE THREAD

**Issue by featurist-au** [Attendize/Attendize#790]
G'day!
Can anyone help me to understand the detail of what the fields in the Register screen are?
I will be using Attendize primarily for an Australian market, so there are a lot of fields that I need to get a clearer picture on in regards to signing up a new organiser.

Can someone help me to understand what are the fields listed below are for and if I could safely have them removed?;

1. ORGANISER MCC CODE. 
We don't use this in Australia. Could it be removed?

2. ORGANISER DATE OF BIRTH. 
Why is this required? Could it be removed?

3. ORGANISER ID NUMBER
What does this refer to? Could it be removed?

4. ORGANISER SSN LAST 4
We don't use Social Security Numbers in Australia. Could it be removed?

5. TAX ID
What does this refer to? We use ABN (Australian Business Number) or an ACN (Australian Company Number) in Australia. Is this the same thing?
Also, since there is another field called COMPANY TAX ID, I suspect this field may not be required? Could it be removed?

6. ORGANISER ID PROOF DOCUMENT
What is this for? What am I expected to have uploaded here & what is it for?
Could it be removed?

7. ROUTING NUMBER
I suspect this is the same as our BSB (Bank-State-Branch) number, which is a six-digit number that identifies banks and branches across Australia. Would this be correct?
I would not remove this one, only rename it in my instance.

I look forward to your help on these queries.

**Comment by samdb** [comment]
Hi Scott, where do you see these fields? They are not standard parts of Attendize.

**Comment by featurist-au** [comment]
Hi @samdb 
You have raised a very good point.
I have a developer making amendments to Attendize for me and I was led to believe the screen I was asking about was a default part of the platform.
I will go back to them now & ask some hard questions about why this has been done.

**Comment by samdb** [comment]
The fields have possibly been added as custom fields via the ‘questionnaire’ feature.
