### ISSUE TITLE
[BUG] headers already sent issue while downloading pdf

### ISSUE THREAD

**Issue by waqasraza123** [Attendize/Attendize#791]
Getting this error while downloading the tickets after the checkout 
`Cannot modify header information - headers already sent by (output started at /Users/user/Attendize/vendor/symfony/var-dumper/Dumper/AbstractDumper.php:182)
http://localhost:8000/order/v81qB15/tickets?download=1`

I am on mac, using php 7.4.

**Comment by benchew1234** [comment]
I facing this issue too , may I know how you solved it?

**Comment by benchew1234** [comment]
Hi I just solve this issue , under /config/Wkhtml2pdf.php make sure your debug is -> env('APP_DEBUG_PDF', false).
