### ISSUE TITLE
More payment gateways support (PayPal / Bitpay)

### ISSUE THREAD

**Issue by Attendize** [Attendize/Attendize#8]
Currently it is only possible to use Stripe.com to accept payments. However, [Omnipay](https://github.com/thephpleague/omnipay), the payments library being used, allows for easy(ish) supporting of further payment gateways.

Stripe doesn't require the user to leave the site which is a positive, however, it is not supported in many countries. 

Supporting Bitcoin would also be a bonus and there's a [Bitpay](https://github.com/thephpleague/omnipay-bitpay) driver available for Omnipay.

**Comment by georgeboot** [comment]
Is adding support for off-site gatways on the list?

**Comment by Attendize** [comment]
We're now using [Omnipay](https://github.com/thephpleague/omnipay-paypal) as the payment library so they will certainly will be. 

In theory the majority of following payment gateways will be supported. Or at least will not require a major amount of work to implement. 

1. 2Checkout
2. Agms
3. Alipay(Global)
4. Alipay
5. Authorize.Net
6. Barclays ePDQ
7. BKM Express
8. Buckaroo
9. CardGate
10. CardSave
11. Checkout.com
12. Coinbase
13. Creditcall
14. Cybersource
15. Cybersource SOAP
16. DataCash
17. Dummy
18. ecoPayz
19. eWAY
20. Fasapay
21. Fat Zebra
22. First Data
23. Flo2cash
24. Globalcloudpay
25. GoCardless
26. GVP (Garanti)
27. Helcim
28. IfthenPay
29. Iyzico
30. Komerci (Rede, former RedeCard)
31. Komoju
32. Manual
33. Migs
34. Mollie
35. MultiCards
36. MultiSafepay
37. NestPay (EST)
38. Netaxept (BBS)
39. Netbanx
40. Neteller
41. Network Merchants Inc. (NMI)
42. Pacnet
43. Pagar.me
44. PayFast
45. Payflow
46. PaymentExpress (DPS)
47. PaymentSense
48. PaymentWall
49. PayPal
50. PayPro
51. Paysafecard
52. PayTrace
53. PayU
54. Pin Payments
55. Portmanat
56. Posnet
57. Postfinance
58. Realex
59. RedSys
60. Sage Pay
61. SecPay
62. SecurePay
63. Secure Trading
64. Sisow
65. Skrill
66. Stripe
67. TargetPay
68. UnionPay
69. Veritrans
70. WebMoney
71. WeChat
72. WechatPay
73. WePay
74. Wirecard
75. WorldPay
76. WorldPay XML Direct
77. Yandex.Money

**Comment by Sebi55** [comment]
I am able to use paypal apparently. It takes me to the paypal site and I am able to pay. Why shouldn't I be able to use process payments with paypal?
Furthermore is there an option to let the user choose between strip, paypal and coinbase?

**Comment by daveearley** [comment]
Apologies, but I can't quite make out the issue you're having. Are you getting errors when trying to pay with PayPal?

Also, currently it is not possible to for the user to choose the payment method. However, I may add that as an option in a future release.

**Comment by Sebi55** [comment]
No everything works fine but you said in your initial text that the only way payments can be accepted is Stripe. Or do I understand it wrong?

It would make sense since not all user use stripe or paypal.

**Comment by daveearley** [comment]
I understand now. Support for additional payment gateways has been added since the first comment. 

Over the next month or so there should be a few more added also.

**Comment by carneto** [comment]
Can you add the Paysafecard driver for the Omnipay payment processing library?

**Comment by daveearley** [comment]
I'm not overly familiar with Paysafecard, however, if there is an Omnipay driver then it could be added. As it stands it's not on our list of planned gateways, but if anyone wants to add it and make a pull request we'd be happy to include it.

**Comment by kasbah** [comment]
Not sure if this should be a separate issue but it would be great to be able to provide multiple payment options at the same time for the same event.

**Comment by jimrome** [comment]
So I am confused. In /Attendize/vendor/omnipay there is a paypal directory. What is needed to activate this into Attendize?
