### ISSUE TITLE
I can't login right after installation

### ISSUE THREAD

**Issue by flipside37** [Attendize/Attendize#809]
Hi all, 

I have installed Attendize on a server (Ubuntu server 16.04 LTS, Apache, MySQL, PHP 7.4). Everything was green on the Attendize setup page and the database connection was OK. After installation was finished i was asked to create a user. I got a message that everything is OK and that i can login.
When i tried to login i got an error message saying "Robot verification failed, please try again". 

Could you please help me on that?

**Comment by johannac** [comment]
Did you clone the repo from github when installing? You'll need to use the master branch or a tag, the develop branch is unstable.

**Comment by flipside37** [comment]
Hello johannac, 
I followed the instructions from https://www.attendize.com/getting_started.html and i used the command: git clone https://github.com/Attendize/Attendize
Do you think that this caused the problem?
Does the error message mean something to you?

**Comment by johannac** [comment]
Sure that’s fine. You’ll just need to check out the master branch by running ‘git checkout master’ from the root of the project. And then try and log in again. Please let me know if this solves the problem.

**Comment by flipside37** [comment]
Bingo!!!
Now it works like a charm. Thank you so much...
I just had to run it using sudo.
On last question, off topic i'm afraid. Could you tell me if Attendize can support different languages?

**Comment by johannac** [comment]
Great! I will add that step to the documentation. 

Yes, there is support for several languages, and it's easy to add more if you need. See here https://github.com/Attendize/Attendize/tree/develop/resources/lang
