### ISSUE TITLE
[BUG] Error generating PDF - wkhtml2pdf

### ISSUE THREAD

**Issue by mazdakzar** [Attendize/Attendize#817]
Hello, 
I'm pretty newbie in dev, I managed after few days of hard work and a lot of bug to make this nice tool works, but I have a last issue which I cannot find solution. Maybe I did something wrong and I'm sorry for that.

The error appear when generating a PDF ticket with wkhtml2pdf 

TIcket is not generated and give error : 
System error <pre>sh: 1: /var/www/html/attendize/vendor/nitmedia/wkhtml2pdf/src/Nitmedia/Wkhtml2pdf/lib/wkhtmltopdf-amd64: Exec format error </pre> 

this error can be seen in 
https://flareapp.io/share/V7jByj7b#F55
![Capture](https://user-images.githubusercontent.com/26630482/86232931-fbaa0900-bb94-11ea-8c0e-197f5288d470.JPG)

**To Reproduce**
1. Buy ticket
2. click on download ticket
3. Error appear

**Environment the bug happens in (Desktop, Mobile, CLI) (please complete the following information):**
Tried on several Browser, on my Windows PC

**Version of Attendize you are using**
- 2.0.2

**Where you are running Attendize**
- Raspberry Pi 4b

**What version or Operating System are you using on the above server**
- Raspian OS Version 20/05/2020 (Based on Debian)

**What version of PHP you are using on the above server**
- e.g PHP 7.3
**What web server are you using Attendize with**
- Nginx

**Additional context**
https://flareapp.io/share/V7jByj7b#F55

Thanks in advance for your help.

**Comment by samdb** [comment]
WKHTML is a binary that will only run on the architecture it was compiled for. If you look at the binary name it is wkhtmltopdf-amd64 so this won't execute on the Raspberry Pi's ARM processor.

You could try swapping out the binary with one compiled for ARM. The full list of versions available is here:
https://wkhtmltopdf.org/downloads.html

**Comment by mazdakzar** [comment]
Thank you for this explication, it's more clear to me now !
Have a nice day
