### ISSUE TITLE
[BUG] version checking error

### ISSUE THREAD

**Issue by justynpride** [Attendize/Attendize#818]
On the About page there appears to be no version checking or an error. My system says 'Your version (2.1.0 ) of Attendize is out of date. The latest version (2.1.0) can be downloaded here.' I'd expect it to say something like 'Your version (2.1.0 ) of Attendize is up to date.' It's also worth noting the download link (https://www.attendize.com/documentation.php#download) doesn't work.

**Comment by publicarray** [comment]
Is there anything in the laravel log file?

**Comment by justynpride** [comment]
@publicarray the log file is clear of entries. I confirm  .env `APP_DEBUG=true`.

**Comment by publicarray** [comment]
No logs at all? Is the environment set to ‘production’? Can you try and change it to ‘local’ thanks

**Comment by justynpride** [comment]
@publicarray So I do have logs, it's just that they don't have any contents. They work because I know if I do something that creates an error (such as #782) the log is populated with the relevant info. I have tried with both APP_ENV=production and APP_ENV=local and have the same results.

With this quirk it's not that an error message is display, it feels more like the logic isn't working, or there. 
<img width="611" alt="image" src="https://user-images.githubusercontent.com/309050/86536994-c822f380-bea0-11ea-9cfe-c8ce0cdd2cd0.png">

**Comment by johannac** [comment]
Fixed in https://github.com/Attendize/Attendize/releases/tag/v2.8.0
