### ISSUE TITLE
Getting Error on php 7.1

### ISSUE THREAD

**Issue by GaneshKandu** [Attendize/Attendize#819]
Hi,

I am getting error on php 7.1.

[minimum requirements](https://www.attendize.com/getting_started.html#minimum-requirements)

```

We'll be back soon
We're currently making improvements to our website.
```

[minimum requirements](https://github.com/Attendize/Attendize#minimum-requirements)

**Comment by samdb** [comment]
We would need a lot more information to be able to help you diagnose this. Please resubmit your issue following the issue template, filling out as much of the information as you can.
