### ISSUE TITLE
[Sat Apr 23 19:14:55 2016] PHP Notice:  Use of undefined constant MCRYPT_RIJNDAEL_128 - assumed 'MCRYPT_RIJNDAEL_128' in /root/coding/Attendize/config/app.php on line 95

### ISSUE THREAD

**Issue by taibaiyifeng** [Attendize/Attendize#82]
[Sat Apr 23 19:14:59 2016] PHP Notice:  Use of undefined constant MCRYPT_RIJNDAEL_128 - assumed 'MCRYPT_RIJNDAEL_128' in /root/coding/Attendize/config/app.php on line 95
[Sat Apr 23 19:14:59 2016] 192.168.8.1:50211 [500]: /
[Sat Apr 23 19:17:14 2016] 192.168.8.1:50220 [500]: /
[Sat Apr 23 19:17:19 2016] 192.168.8.1:50221 [500]: /login
[Sat Apr 23 19:17:34 2016] 192.168.8.1:50222 [500]: /signup
[Sat Apr 23 19:17:47 2016] 192.168.8.1:50223 [500]: /
[Sat Apr 23 19:17:53 2016] 192.168.8.1:50224 [500]: /install
[Sat Apr 23 19:18:46 2016] 192.168.8.1:50225 [200]: /signup
[Sat Apr 23 19:18:46 2016] 192.168.8.1:50226 [200]: /vendor/jquery/jquery.js

I change the app.php file 'cipher' => 'AES-256-CBC'(this is laravel default value') so it can work.
use the value MCRYPT_RIJNDAEL_128 it can't work.

**Comment by daveearley** [comment]
It looks like you may be missing the PHP mycrypt module. Try installing the module and see if that helps.
