### ISSUE TITLE
[BUG] Docker build is failing when executing php artisan migrate

### ISSUE THREAD

**Issue by pernpas** [Attendize/Attendize#822]
**Describe the bug**
In order to start attendize on a local docker runtime I do the first step: `make setup`
During building the attendize_base image the build executes `php artisan migrate`. This results in an error: 
```
> @php artisan clear-compiled
Compiled services and packages files removed!
Application key set successfully.

   Illuminate\Database\QueryException  : SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: No address associated with hostname (SQL: select * from information_schema.tables where table_schema = attendize and table_name = migrations and table_type = 'BASE TABLE')

  at /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:669
    665|         // If an exception occurs when attempting to run a query, we'll format the error
    666|         // message to include the bindings with SQL, which will make this exception a
    667|         // lot more helpful to the developer instead of just the database's errors.
    668|         catch (Exception $e) {
  > 669|             throw new QueryException(
    670|                 $query, $this->prepareBindings($bindings), $e
    671|             );
    672|         }
    673|

  Exception trace:

  1   Doctrine\DBAL\Driver\PDOException::("SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: No address associated with hostname")
      /usr/share/nginx/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31

  2   PDOException::("PDO::__construct(): php_network_getaddresses: getaddrinfo failed: No address associated with hostname")
      /usr/share/nginx/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27

  Please use the argument -v to see more details.
The command '/bin/sh -c ./scripts/setup' returned a non-zero code: 1
```

**To Reproduce**
1.  `git checkout master`
2.  `make setup`
3. See error

**Expected behavior**
I want the docker image `attendize_base` to be created successfully.

**Environment the bug happens in (Desktop, Mobile, CLI) (please complete the following information):**
 - OS: Ubuntu

**Version of Attendize you are using**
- Master branch 

**Where you are running Attendize**
- Docker

**What version or Operating System are you using on the above server**
-  Ubuntu 20.04

**What version of PHP you are using on the above server**
-  PHP 7.3

**Comment by millsoft** [comment]
same problem here.

**Comment by roddenm** [comment]
And here

**Comment by tumaniholie** [comment]
> I have been able to resolve it by commenting out the php artisan migrate in the script set-up folder

Can you explain better? Please

**Comment by jefhar** [comment]
@tumaniholie The process tries to migrate using the `mysql` host which hasn't yet been built. Solution is to not run `./scripts/setup` in the `Dockerfile` during the build process. It will run during the setup process correctly.


```patch
Index: Dockerfile
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- Dockerfile	(revision 030b42d14924b871e6b62b29a48ce771ad5dbcbc)
+++ Dockerfile	(date 1598926923638)
@@ -8,7 +8,7 @@
 COPY . .
 
 # run composer, chmod files, setup laravel key
-RUN ./scripts/setup
+# RUN ./scripts/setup
 
 # The worker container runs the laravel queue in the background
 FROM base as worker
```

**Comment by kraigAllan** [comment]
Thanks @jefhar that worked for me!

**Comment by trysten** [comment]
It seems that 8b8c9162f0c226af6b45af66c32939dff64886d5 would break the initial setup process as there is no mysql server at this point in the build. I created a PR #843 to revert. 

I'm just getting into Attendize, so i'm unsure if this is the right solution. Perhaps the attendize_db needs to be started sooner.

**Comment by johannac** [comment]
Hi all - thanks for all the bug reports and apologies for the delay in fixing this. I've sorted out the set up flow so the database migrations don't fail on initial set up. Would greatly appreciate it if anyone is able to test this locally on a clean checkout and let me know if it's working now. 

Will be releasing this to v2.1.1 shortly.
