### ISSUE TITLE
[BUG] Deactivating social settings turned into SQL excetion

### ISSUE THREAD

**Issue by pernpas** [Attendize/Attendize#825]
**Describe the bug**
When I customize an event and deactivate the social links on the event I cannot save the changes. Saving ends up in `[2020-07-18 03:57:34] production.ERROR: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'social_show_facebook' cannot be null (SQL: update `events` set `social_show_facebook` = ?, `social_show_linkedin` = ?, `social_show_twitter` = ?, `social_show_email` = ?, `social_show_googleplus` = ?, `social_show_whatsapp` = ?, `events`.`updated_at` = 2020-07-18 03:57:34 where `id` = 1) {"userId":2,"exception":"[object] (Illuminate\\Database\\QueryException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'social_show_facebook' cannot be null (SQL: update `events` set `social_show_facebook` = ?, `social_show_linkedin` = ?, `social_show_twitter` = ?, `social_show_email` = ?, `social_show_googleplus` = ?, `social_show_whatsapp` = ?, `events`.`updated_at` = 2020-07-18 03:57:34 where `id` = 1) at /var/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php:669)`

**To Reproduce**
1. Go in admin section to an event 
2. Click on 'Event Menu -> Customize -> Social'
3. Uncheck all social buttons to share 
4. See error in logfile: `[2020-07-18 03:57:34] production.ERROR: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'social_show_facebook' cannot be null (SQL: update `events` set `social_show_facebook` = ?, `social_show_linkedin` = ?, `social_show_twitter` = ?, `social_show_email` = ?, `social_show_googleplus` = ?, `social_show_whatsapp` = ?, `events`.`updated_at` = 2020-07-18 03:57:34 where `id` = 1) {"userId":2,"exception":"[object] (Illuminate\\Database\\QueryException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'social_show_facebook' cannot be null (SQL: update `events` set `social_show_facebook` = ?, `social_show_linkedin` = ?, `social_show_twitter` = ?, `social_show_email` = ?, `social_show_googleplus` = ?, `social_show_whatsapp` = ?, `events`.`updated_at` = 2020-07-18 03:57:34 where `id` = 1) at /var/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php:669)`

**Expected behavior**
I want to persist the changed configuration regarding social integration. 

**Environment the bug happens in (Desktop, Mobile, CLI) (please complete the following information):**
 - OS: Ubuntu 20.04
 - MySQL 5.7.23
 - Version 2.1.0

**Version of Attendize you are using**
- Tag v2.1.0

**Where you are running Attendize**
- in Docker

**What version or Operating System are you using on the above server**
- Ubuntu 20.04

**What version of PHP you are using on the above server**
- PHP 7.3
**What web server are you using Attendize with**
- Nginx.

**Comment by lmarmier** [comment]
I have the same issue. Who can solve it

**Comment by johannac** [comment]
Fixed via #906
