### ISSUE TITLE
Mailers.

### ISSUE THREAD

**Issue by GFvax** [Attendize/Attendize#83]
I have a huge problem with mailing.
I cannot send tickets or resend, swiftmailer [] error cannot get the email address     
private function _assertValidAddress($address)
    {
        if (!preg_match('/^'.$this->getGrammar()->getDefinition('addr-spec').'$/D',
            $address)) {
            throw new Swift_RfcComplianceException(
                'Address in mailbox given ['.$address.
                '] does not comply with RFC 2822, 3.6.2.'
                );
        }
    }
The app don't take the [.$address.]   

I tried to comment it, then I get this error for swiftmail... 

[2016-04-23 11:17:40] production.INFO: 23 04 16 11:17 - Starting Job  App\Commands\SendAttendeeTicketCommand  
[2016-04-23 11:17:41] production.ERROR: exception 'Swift_TransportException' with message 'Connection could not be established with host  [php_network_getaddresses: getaddrinfo failed: Name or service not known #0]' in /home/ubuntu/workspace/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php:265

I'm using a shared server.

**Comment by daveearley** [comment]
It looks like your SMTP host can't be reached. Check if it's set correctly in the .env file. If that doesn't work contact your host and check if they are blocking the connection.

**Comment by GFvax** [comment]
First I want to clarify this so nobody think your code is wrong by my sight.
**I'm overwhelmed with my lack of knowledge.**
Now it works after proper config of .env ... the app sends the pdf, but an empty pdf.

[2016-04-23 12:59:30] production.ERROR: exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'ticket_revenue' in 'field list'' in /home/.../public_html/register/vendor/laravel/framework/src/Illuminate/Database/Connection.php:429

Next exception 'Illuminate\Database\QueryException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'ticket_revenue' in 'field list' (SQL: update `tickets` set `ticket_revenue` = 5, `updated_at` = 2016-04-23 12:59:30 where `id` = 1)' in /home/.../public_html/register/vendor/laravel/framework/src/Illuminate/Database/Connection.php:673


I didn't want to write over here to not bother the development, but I really need to fix this issue and I don't know if is me, or the code.

**Comment by daveearley** [comment]
The **Unknown column 'ticket_revenue'** error is caused by a bug that was fixed a few weeks ago. If you replace the contents of the file **app/Models/EventStats.php** with the file [found here](https://github.com/Attendize/Attendize/blob/master/app/Models/EventStats.phpEventStats.php) it should work.

In relation to the empty PDF problem, that sounds like it may be an issue with the **WkhtmlToPdf**, the library used to create the PDFs. If you Google "wkhtmltopdf empty pdf" you'll find answers from people who have had the same issue.
