### ISSUE TITLE
[BUG] Mail not sent with real queue

### ISSUE THREAD

**Issue by gciliberti** [Attendize/Attendize#844]
**Describe the bug**
When using a real queue driver (in my case database) the mail are not sent because the queue worker doesn't find the template associated to the mail.
In fact it will search the template at the root level of the view folder and not inside the translation folder.
**To Reproduce**
Set the driver to database inside the queue.php config.

**Expected behavior**
It should look inside the local translation folder to send the emails.

**Screenshots**
`Error message. View [Emails.OrderNotification] not found.`

**Version of Attendize you are using**
2.1.0

**Where you are running Attendize**
- In Docker

**What version or Operating System are you using on the above server**
- Debian 10

**What version of PHP you are using on the above server**
PHP 7.3 with Apache

**Additional context**
By moving files from en/Emails/* to Emails/ the queue will now work but this mean no translation feature.

**Comment by gciliberti** [comment]
It seems that using the 'Localizable' trait fix this issue ! It would have to be implemented everywhere 'Mail::send' is used or at a higher level if possible but I can't manage to find where to put it.

**Comment by johannac** [comment]
This is fixed in https://github.com/Attendize/Attendize/pull/883 and released in v2.2.0
