### ISSUE TITLE
[BUG] No install page

### ISSUE THREAD

**Issue by jimrome** [Attendize/Attendize#846]
**Describe the bug**
I carefully followed the installation guide at https://www.attendize.com/ on my OpenSUSE LEAP 15.2 machine. I got no error messages, and permissions are good. But the step https://mysite/Attendize/install fails with a 404.
There is no install* in my installation:
`jarfx:/srv/www/htdocs/Attendize # ls public
assets  css  favicon.ico  .htaccess  index.php  mp3  robots.txt  user_content  vendor
jarfx:/srv/www/htdocs/Attendize # ls public/user_content
event_bg_images  event_images  .gitignore  organiser_images  pdf_tickets
jarfx:/srv/www/htdocs/Attendize # ls
app                 composer.json       Dockerfile-apache  .gitattributes  Makefile      resources         .styleci.yml
artisan             composer.lock       .dockerignore      .github         nginx.conf    routes            tests
AUTHORS             config              .editorconfig      .gitignore      package.json  scripts           vendor
bootstrap           CONTRIBUTING.md     .env               Gruntfile.js    phpspec.yml   self-signed.conf  VERSION
bower.json          database            .env.example       .htaccess       phpunit.xml   server.php        yarn.lock
.bowerrc            docker-compose.yml  .env.swp           LICENSE         public        ssl-params.conf
CODE_OF_CONDUCT.md  Dockerfile          .git               MAINTAINERS     README.md     storage`
Attendize can access the database, and populated it (via a popup) from somewhere(??). But it dies when I try to make an account:
`Illuminate\Database\QueryException
SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`attendize`.`accounts`, CONSTRAINT `accounts_timezone_id_foreign` FOREIGN KEY (`timezone_id`) REFERENCES `timezones` (`id`)) (SQL: insert into `accounts` (`email`, `first_name`, `last_name`, `currency_id`, `timezone_id`, `updated_at`, `created_at`) values `
At https://mysite/Attendize/public/signup 

I do have a license
**To Reproduce**
See above
`
/srv/www/htdocs/Attendize/
Illuminate\Database\QueryException
SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`attendize`.`accounts`, CONSTRAINT `accounts_timezone_id_foreign` FOREIGN KEY (`timezone_id`) REFERENCES `timezones` (`id`)) (SQL: insert into `accounts` (`email`, `first_name`, `last_name`, `currency_id`, `timezone_id`, `updated_at`, `created_at`) values (jamesrome@gmail.com, James, Rome, 2, 30, 2020-10-18 17:59:52, 2020-10-18 17:59:52))
https://jarfx.dyndns.org/Attendize/public/signup

        71
        vendor/laravel/framework/src/Illuminate/Database/Connection.php
        Illuminate\Database\Connection
        :669

    55
    app/Http/Controllers/UserSignupController.php
    App\Http\Controllers\UserSignupController
    :71

1 unknown frame

    47
    app/Http/Middleware/RedirectIfAuthenticated.php
    App\Http\Middleware\RedirectIfAuthenticated
    :24

    45
    app/Http/Middleware/CheckInstalled.php
    App\Http\Middleware\CheckInstalled
    :37

    37
    app/Http/Middleware/SetViewVariables.php
    App\Http\Middleware\SetViewVariables
    :44

    8
    app/Http/Middleware/GeneralChecks.php
    App\Http\Middleware\GeneralChecks
    :26

        1
        public/index.php
        :55

Illuminate\Database\Connection::runQueryCallback :669
vendor/laravel/framework/src/Illuminate/Database/Connection.php:669

     * @throws \Illuminate\Database\QueryException

     */

    protected function runQueryCallback($query, $bindings, Closure $callback)

    {

        // To execute the statement, we'll simply call the callback, which will actually

        // run the SQL against the PDO connection. Then we can calculate the time it

        // took to execute and log the query SQL, bindings and time in our memory.

        try {

            $result = $callback($query, $bindings);

        }

 

        // If an exception occurs when attempting to run a query, we'll format the error

        // message to include the bindings with SQL, which will make this exception a

        // lot more helpful to the developer instead of just the database's errors.

        catch (Exception $e) {

            throw new QueryException(

                $query, $this->prepareBindings($bindings), $e

            );

        }

 

        return $result;

    }

 

    /**

     * Log a query in the connection's query log.

     *

     * @param  string  $query

     * @param  array  $bindings

     * @param  float|null  $time

     * @return void

     */

            

`

**Expected behavior**
The install page sho
![Attendize](https://user-images.githubusercontent.com/1304327/96376403-be21b980-114c-11eb-8647-72621f1ea57b.png)
uld work
**Screenshots**

**Environment the bug happens in (Desktop, Mobile, CLI) (please complete the following information):**
 - OS: [e.g. Mac, iOS, Windows]
Browsing from across the room on my MacOS Mojave using Firefox

**Version of Attendize you are using**
- Master branch or release tag  2.1.0

**Where you are running Attendize**
In a normal linux machine in htdocs directory

**What version or Operating System are you using on the above server**
OpenSUSE LEAP 15.2

**What version of PHP you are using on the above server**
PHP 7.4.6
**What web server are you using Attendize with**
Apache.

**Additional context**

**Comment by jimrome** [comment]
You seem to have no support, even after I bought a license.

**Comment by johannac** [comment]
Hi again @jimrome For the install page, Attendize uses rewrites for all the URLs. So in your case with Apache, it will use mod_rewrite, and there is an .htaccess file here in the repo that has the related rewrite rules. Once you set that up, you should be able to load the install page in your browser. My guess is that this will resolve the second error with the SQL exception, which is likely caused from the database not being set up yet, which happens when you get to the install page. 

I see that the rewrite information is missing from our documentation. It's a requirement for Laravel. I will add some additional notes about that to our docs to make that more clear.

**Comment by jimrome** [comment]
I have the .htaccess file in the main Attendize directory:
RewriteEngine On
RewriteRule ^(.*)$ public/$1 [L]

Attendize is a subdirectory in htdocs. If I  go to mysite/Attendize, I get a 404. I must go to mysite/Attendize/public to get the install page. But then after entering an account, I get the SQL error.
So I still cannot make an account!

**Comment by johannac** [comment]
Hi @jimrome Attendize is meant to be installed in the root directory of your web server, as stated on the getting started page. If you'd like to run it in a subdirectory instead, you're welcome to, but I don't personally have any other information or documentation to provide. I think you'll need to change the mod_rewrite settings to take the sub directory into account, and there seems to be lot's of info online about how to run a Laravel app in a subdirectory. 

With regards to the SQL error, I believe the installation of the database may have gotten messed up with you having tried to run the installation more than once. I would suggest dropping the database and starting the installation again, once you have the rewrites working.

**Comment by jimrome** [comment]
There are no instructions about installing this on OpenSUSE or RedHat. I flushed the database and still get the same SQL error. The .htaccess rewrite is correct. Am still stuck.

**Comment by johannac** [comment]
Hi @jimrome Basically what the error is saying is that it's missing the timezone entry that you're using. If you can log into your database server and try running `select * from timezones where id=30;` does it return any data? If not, then the timezones table wasn't seeded correctly and needs to be seeded again. You can reseed by running `php artisan migrate:fresh --seed` from the root of the Attendize directory.

**Comment by jimrome** [comment]
Attendize is still not working for me!

**Comment by jimrome** [comment]
I reseeded the tables, and still get no results from select * from timezones where id=30 ;

**Comment by jimrome** [comment]
The timezone table was populated, and things seem to work now.

**Comment by jimrome** [comment]
![attendizeorganiser](https://user-images.githubusercontent.com/1304327/122653636-e0246f00-d113-11eb-895b-16abe01f3fd5.png)
I spoke too soon. The first step will not work. How do I tell what the server error is?
