### ISSUE TITLE
[BUG] Composer failed In PackageManifest.php line 131:   Undefined index: name

### ISSUE THREAD

**Issue by jimrome** [Attendize/Attendize#847]
**Describe the bug**
Followed directions at https://www.attendize.com/getting_started.html on my site.
Composer threw errors:
`Generating optimized autoload files
Class Tests\Features\UtilsTest located in ./tests/Feature/Utils/UtilsTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Tests\Features\OrganisationWithoutTaxTest located in ./tests/Feature/OrderCancellation/OrganisationWithoutTaxTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Tests\Features\OrganisationWithTaxTest located in ./tests/Feature/OrderCancellation/OrganisationWithTaxTest.php does not comply with psr-4 autoloading standard. Skipping.
Class HTMLPurifier_Language_en_x_test located in ./vendor/ezyang/htmlpurifier/library/HTMLPurifier/Language/classes/en-x-test.php does not comply with psr-0 autoloading standard. Skipping.
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
In PackageManifest.php line 131:
  Undefined index: name
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1`

**To Reproduce**
1. follow install instructions
2. composer install dies with above error

**Screenshots**

**Environment the bug happens in (Desktop, Mobile, CLI) (please complete the following information):**
 - OS: [Linux
 - Browser N/A

**Version of Attendize you are using**
- Master branch or release tag
Master 1.1
**Where you are running Attendize**
- in Docker, a Virtual Machine, Shared Webhost, VPS etc

**What version or Operating System are you using on the above server**
cloudlinux:7.8:GA:server

**What version of PHP you are using on the above server**
- 7.4
**What web server are you using Attendize with**
Apache.

**Additional context**

**Comment by Bilgee** [comment]
same here

**Comment by johannac** [comment]
Hi @jimrome @Bilgee what version of composer are you using when this error occurs?

**Comment by xobtoor** [comment]
We have the same problem.

For me it's composer v2.0.7 (latest).

We can downgrade to 1.x and it's working again and we also get these warnings:

`does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0`

**Comment by jimrome** [comment]
It was Composer 2

**Comment by jimrome** [comment]
So I used Composer 1 with no issues. But how do I actually run the program?

**Comment by jimrome** [comment]
_Navigate to http://your-ticket-site.com/install_ 
There is no "install" in the Attendize directory. 
`www/htdocs/Attendize # ls
app                 composer.json       Dockerfile-apache  .github          nginx.conf          routes            vendor
artisan             composer.lock       .dockerignore      .gitignore       package.json        scripts           VERSION
AUTHORS             composer.phar       .editorconfig      Gruntfile.js     phpspec.yml         self-signed.conf  yarn.lock
bootstrap           config              .env               .htaccess        .phpstorm.meta.php  server.php
bower.json          CONTRIBUTING.md     .env~              _ide_helper.php  phpunit.xml         ssl-params.conf
.bowerrc            database            .env.example       LICENSE          public              storage
c1                  docker-compose.yml  .git               MAINTAINERS      README.md           .styleci.yml
CODE_OF_CONDUCT.md  Dockerfile          .gitattributes     Makefile         resources           tests`

**Comment by jimrome** [comment]
Well, the url is mysite/Attendize/public, But I cannot make an account. I get:
`Illuminate\Database\QueryException
SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`attendize`.`accounts`, CONSTRAINT `accounts_timezone_id_foreign` FOREIGN KEY (`timezone_id`) REFERENCES `timezones` (`id`)) (SQL: insert into `accounts` (`email`, `first_name`, `last_name`, `currency_id`, `timezone_id`, `updated_at`, `created_at`) values (jamesrome@gmail.com, James, Rome, 2, 30, 2020-11-30 18:31:21, 2020-11-30 18:31:21))
https://jarfx.dyndns.org/Attendize/public/signup `

**Comment by johannac** [comment]
Hi @jimrome Thanks for your bug report. I've added it to our backlog to upgrade the composer compatibility to also work with v2. See #856. I'm going to close this for now as the work will be completed via #856. Regarding your other question about the install page, I'll answer on your other ticket #846 just to keep the topics separated.

**Comment by simkea** [comment]
Unfortunately, the problem still exists.
How can I start a current executable version?

my current composer version 2.0.9

**Comment by quentincaffeino** [comment]
Currently project supports only composer v1.
You need to rollback using something like `composer --self-upgrade 1`, can't check right now

**Comment by justynpride** [comment]
Try composer self-update --1

**Comment by simkea** [comment]
Update: I have updated composer to version 2.1.5.
then deleted the composer.lock and now the installation worked successfully.

**Comment by ridwanpratama** [comment]
I still got the error, using composer version 2.1.5

**Comment by ridwanpratama** [comment]
Downgraded to composer 1.x, work well...
