### ISSUE TITLE
Attendize version 2.1.1 composer install issue

### ISSUE THREAD

**Issue by prbt2016** [Attendize/Attendize#853]
Hello,

I was in the process of manual installation of Attendize on Centos 6.9 with : 
Apache - 2.2
MYSQL -5.7
PHP - 7.3

I followed the following guide to install Attendize : 
https://www.attendize.com/getting_started.html#manual-installation-steps

I downloaded Attendize 2.1.1 package from here : 
https://github.com/Attendize/Attendize/releases/tag/v2.1.1

When i run `composer install` i get the following error : 

```
Generating optimized autoload files
Class Tests\Features\UtilsTest located in ./tests/Feature/Utils/UtilsTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Tests\Features\OrganisationWithTaxTest located in ./tests/Feature/OrderCancellation/OrganisationWithTaxTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Tests\Features\OrganisationWithoutTaxTest located in ./tests/Feature/OrderCancellation/OrganisationWithoutTaxTest.php does not comply with psr-4 autoloading standard. Skipping.
Class HTMLPurifier_Language_en_x_test located in ./vendor/ezyang/htmlpurifier/library/HTMLPurifier/Language/classes/en-x-test.php does not comply with psr-0 autoloading standard. Skipping.
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
In PackageManifest.php line 131:
  Undefined index: name
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
```

Could you please fix this issue?

**Comment by johannac** [comment]
Hi @prbt2016 Thanks for your bug report. Attendize currently only works with Composer v1. I've added it to our backlog to upgrade the compatibility to also work with v2. See #856. In the meantime, if you use composer v1 (v1.10.15 is what's used on our docker container for dev) you'll be able to complete the install. I'm going to close this for now as the work will be completed via #856.
