### ISSUE TITLE
[BUG] Unable to add user 

### ISSUE THREAD

**Issue by mercurystorm** [Attendize/Attendize#854]
**Describe the bug**
On a fresh installation (2.10 and 2.11) I am unable to add a new user to manage my organization

**To Reproduce**
1. Go to 'Account Settings'
2. Click on 'Users.'
3. Type in email address
4. Click 'Add User'
4. See error "Whoops!, it looks like the server returned an error."

**Expected behavior**
A user receives an email and configures account

**Screenshots**

Error in Logs:
[2020-11-30 17:47:01] production.ERROR: Argument 1 passed to App\Http\Controllers\ManageAccountController::App\Http\Controllers\{closure}() must be an instance of Illuminate\Contracts\Mail\Mailable, instance of Illuminate\Mail\Message given, called in /var/www/attendize/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php on line 244 {"userId":1,"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Argument 1 passed to App\\Http\\Controllers\\ManageAccountController::App\\Http\\Controllers\\{closure}() must be an instance of Illuminate\\Contracts\\Mail\\Mailable, instance of Illuminate\\Mail\\Message given, called in /var/www/attendize/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php on line 244 at /var/www/attendize/app/Http/Controllers/ManageAccountController.php:203)
[stacktrace]

**Version of Attendize you are using**
- 2.10 and 2.11

**Where you are running Attendize**
- VPS

**What version or Operating System are you using on the above server**
- Ubuntu 20.04

**What version of PHP you are using on the above server**
- 7.4
**What web server are you using Attendize with**
- Apache

**Additional context**

**Comment by justynpride** [comment]
I think you will find this is fixed in https://github.com/Attendize/Attendize/pull/803 but it has yet to be merged in to a release.

**Comment by mercurystorm** [comment]
this does indeed fix the issue 👍

**Comment by johannac** [comment]
@mercurystorm Thank you for the bug report! I've fixed this issue in v2.1.2. Please let me know if you have any further issues.

**Comment by luan-kodeplus** [comment]
@johannac After I have received account information from email address that I have typed at step 3 (Type in email address), I couldn't login with that account:
![2](https://user-images.githubusercontent.com/61045289/102592272-d3fc2c80-4145-11eb-9b97-06028b85a9c8.png)

**Comment by EstebanJoseSantos** [comment]
> **Describe the bug**
> On a fresh installation (2.10 and 2.11) I am unable to add a new user to manage my organization
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Go to 'Account Settings'
> 2. Click on 'Users.'
> 3. Type in email address
> 4. Click 'Add User'
> 5. See error "Whoops!, it looks like the server returned an error."
> 
> **Expected behavior**
> A user receives an email and configures account
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> 
> Error in Logs:
> [2020-11-30 17:47:01] production.ERROR: Argument 1 passed to App\Http\Controllers\ManageAccountController::App\Http\Controllers{closure}() must be an instance of Illuminate\Contracts\Mail\Mailable, instance of Illuminate\Mail\Message given, called in /var/www/attendize/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php on line 244 {"userId":1,"exception":"[object] (Symfony\Component\Debug\Exception\FatalThrowableError(code: 0): Argument 1 passed to App\Http\Controllers\ManageAccountController::App\Http\Controllers\{closure}() must be an instance of Illuminate\Contracts\Mail\Mailable, instance of Illuminate\Mail\Message given, called in /var/www/attendize/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php on line 244 at /var/www/attendize/app/Http/Controllers/ManageAccountController.php:203)
> [stacktrace]
> 
> **Version of Attendize you are using**
> 
> * 2.10 and 2.11
> 
> **Where you are running Attendize**
> 
> * VPS
> 
> **What version or Operating System are you using on the above server**
> 
> * Ubuntu 20.04
> 
> **What version of PHP you are using on the above server**
> 
> * 7.4
>   **What web server are you using Attendize with**
> * Apache
> 
> **Additional context**
> Add any other context about the problem here.

There was a bug.
If you don't want to update the whole Attendize with the new branch and just want to fix this error

This is what worked for me:
Go to app/Http/Controllers/ManageAccountController.php

Substitute this line:
use Illuminate\Contracts\Mail\Mailable;  (old)
with this line:
**use Illuminate\Mail\Message;** (new)

and change this:
 Mail::send('Emails.inviteUser', $data, static function (Mailable $message) use ($data) {  (old)

with this:
**Mail::send('Emails.inviteUser', $data, static function (Message $message) use ($data) {**  (new)

Save and you should be fine!
