### ISSUE TITLE
Organiser dashboard

### ISSUE THREAD

**Issue by blumedia85** [Attendize/Attendize#86]
After installation I was able to signup however after creating an organiser I was given this error on the organiser dashboard:

ErrorException in OrganiserDashboardController.php line 38: Undefined variable: calendar_events
1. in OrganiserDashboardController.php line 38

Here's the code form line 83:
'calendar_events' => json_encode($calendar_events),

**Comment by daveearley** [comment]
Nice catch, the latest push should fix this. Cheers!

**Comment by blumedia85** [comment]
awesome the dashboard now shows
