### ISSUE TITLE
Oganiser dashboard Links

### ISSUE THREAD

**Issue by blumedia85** [Attendize/Attendize#87]
When I login I'm taken to the organiser dashboard the  "My Profile" and "Account Setting" links do not fire. However if I navigate away to Events or Customise, I can fire the links from there. If I navigate back to "Dashboard" the links don't fire.

**Comment by daveearley** [comment]
I can't seem to replicate this on my end. Are there any errors in the browser console?

**Comment by ylecuyer** [comment]
See notes on this commit : https://github.com/Attendize/Attendize/commit/79f8de9653d973d6c9dfe262f14814007307f715

**Comment by blumedia85** [comment]
This commit was made 2 days before my installation so I should have the fix... there's still an issue

**Comment by ylecuyer** [comment]
To be sure fires up the developer console and watch for javascript errors on this page
