### ISSUE TITLE
[BUG] Demo pages not working

### ISSUE THREAD

**Issue by rowild** [Attendize/Attendize#891]
Just to let you know: The 2 links to the 2 demos (frontend, backend) on the start page (https://www.attendize.com/) lead to 404.

**Comment by jaisharmaimcl** [comment]
![image](https://user-images.githubusercontent.com/17176741/125228744-f7a9de80-e2f2-11eb-9364-6c519d6c48e0.png)
I am getting same error

**Comment by johannac** [comment]
The demo site has been retired. I've removed the links from the web site.
