### ISSUE TITLE
Email copy to Organizer send to the email address of the person who trigger the order

### ISSUE THREAD

**Issue by alexissinglaire** [Attendize/Attendize#895]
When trigger the order successfully, the email received by the person who order (not ticket holder) are 2 emails. 
1 of the email is email for organizer (organiser copy). 

 
**Expected behavior**
Email for organizer copy should be sent to organizer only 

**Screenshots**
![image](https://user-images.githubusercontent.com/17283778/114999925-e0667b00-9ed4-11eb-91df-b1babec86ab3.png)

**Environment the bug happens in (Desktop, Mobile, CLI) (please complete the following information):**
 - OS: Windows
 - Browser  chrome
  
**Version of Attendize you are using**
- Master branch  2.2.0 (latest)

**Where you are running Attendize**
- in google cloud VM

**What version or Operating System are you using on the above server**
-Debian 10

**What version of PHP you are using on the above server**
- PHP 7.3
**What web server are you using Attendize with**
- Apache.

**Comment by johannac** [comment]
Thank you for reporting this @alexissinglaire ! It's been fixed in [v2.2.1](https://github.com/Attendize/Attendize/releases/tag/v2.2.1).
