### ISSUE TITLE
How to activate 

### ISSUE THREAD

**Issue by jasonjenssen** [Attendize/Attendize#897]
Hey, when I buy a license for my self hosted environment, I would like to know how to activate it. Will I get a Key or something else?

**Comment by justynpride** [comment]
@timowevel03 I agree, I would also like to know how Attendize can be white labelled once a full licence has been purchased.

**Comment by johannac** [comment]
We don't have an option for this right now. We sell the licenses through BigCartel and they don't have a system that let's you manage digital downloads and license keys. We will migrate to a new system at some point that supports this, but for now there is no activation required when buying a license.
