### ISSUE TITLE
Version number isn't updated in 'VERSION' file, for 2.2.1 release zip package

### ISSUE THREAD

**Issue by prbt2016** [Attendize/Attendize#899]
Hello @johannac ,

I was in the process of manual installation of Attendize version 2.2.1 downloaded from here : 

https://github.com/Attendize/Attendize/archive/refs/tags/v2.2.1.zip

However the version number isn't updated in the 'VERSION' file. It's still 2.2.0. 

Could you please update this?.

Regards.

**Comment by prbt2016** [comment]
Any update regarding the same?. Awaiting your reply on this?

**Comment by prbt2016** [comment]
Awaiting your reply on this. Please check.

**Comment by prbt2016** [comment]
Any updates on the same ?

**Comment by johannac** [comment]
Hi @prbt2016 Is this blocking something for you? I wasn't planning on going back and changing what's in the tag. A new version has just been released v2.2.2 and the version file is fixed in there.
