### ISSUE TITLE
Support coupons / discount codes at checkout

### ISSUE THREAD

**Issue by Attendize** [Attendize/Attendize#9]

**Comment by bretto36** [comment]
Fields to add for Coupon Table

- code - varchar
- description - varchar
- minimum_purchase - float default 0
- discount - float - default 0
- discount_type - either an int and we handle statuses in code or varchar (eg percentage, dollar value)
- maximum_discount - default 0 (0 means no maximum)
- start_datetime - DATETIME
- end_datetime - DATETIME
- number_of_uses 
- uses_per_user

Coupon Redemption Table

- coupon_id
- order_id
not sure if we'd need any other fields for this as the discount amount is stored against orders table, and the date too

**Comment by VigWatch** [comment]
Coupons should be able to...
1: Open up a particular ticket for purchase (Say, allow someone to buy the 'I'm With DAVE' ticket)
2: Apply a discount (Percentage or Cash) to a specific ticket
3: Apply a Discount (Percentage or Cash) to a whole order
4: Be ticket-specific (I.E. /NOT/ apply to a particular ticket)

**Comment by bretto36** [comment]
also would coupons be restricted to events? I think that's easiest. But there could be a need to set up coupons across all events

**Comment by Kmaz66** [comment]
Hi Guys @Attendize , 

I'm looking to this feature starting with the functionality 2-3-4 of @VigWatch . 

I gonna use the data structure of @bretto36  since I don't see anything missing but I was having two questions before coding. 

- [User Frontend] Should the discount input be on the event page , order page or both ? 
- [Admin] Should we manage coupon on the ticket section or create a different section ? 
- [Backend] Is there anything specific I should know about regarding the event stats when a discount is applied ? 

Let me know what you think works best, any feedback greatly appreciated.

**Comment by bretto36** [comment]
@Kmaz66 
Personally i think discounts just on the order page. As they are directly related to orders and keeping it in the one place allows it to be more uniform

Admin i think have it as it's own section and coupons should be able to be dependent on the event, not a particular ticket.

**Comment by Kmaz66** [comment]
@bretto36 
Thanks for the feedback. 

On a side note I was wondering what would be the  sections on the admin interface where the coupon should be integrated / visible when used by a customer (besides the order overview and report)  .

Any thoughts @daveearley / @ylecuyer   before I start on it ?

**Comment by daveearley** [comment]
I'd opt for having discount codes section on the backend or else things could get cluttered. 

There's another fork I came across [here](https://github.com/aiaechel/Attendize/commits/master) which seems to have started implementing discount codes, I havne't looked at it in detail but you could fork from that as a head start.

**Comment by Kmaz66** [comment]
@daveearley  Great I will have a look. Thanks for the feedback and direction.  

And congrats on the solution, there are some really smart pattern.

**Comment by emergingdzns** [comment]
I see that this thread was closed. Does this mean this feature was completed? If so, where is it? I can't find it in the application. Have a discount code option would be a very nice tool.

**Comment by scottybo** [comment]
Any reason why this was closed?

**Comment by danchello** [comment]
For the ones who is still looking for this functionality you can use Access codes.

**Comment by scottybo** [comment]
@danchello can you give some more information please? :)
