### ISSUE TITLE
[BUG] No place to submit payment details

### ISSUE THREAD

**Issue by PLOKMJNB** [Attendize/Attendize#901]
**Describe the bug**
The payment process/ payment method fields are never shown during checkout

**Expected behavior**
Some sort of modal form with fields to fill with payment details to show

**Screenshots**
![](https://i.iodine.gg/ai56h.png)

**Environment the bug happens in (Desktop, Mobile, CLI) (please complete the following information):**
 - OS: Windows, Android
 - Browser: Chrome, Microsoft Edge, Samsung internet

**Version of Attendize you are using**
- 2.2.0

**Where you are running Attendize**
- Shared Webhost, via softaculous installer

**What version of PHP you are using on the above server**
- PHP 7.2.34

**Log**
[laravel-2021-04-22.log](https://github.com/Attendize/Attendize/files/6358001/laravel-2021-04-22.log)

**Comment by justynpride** [comment]
I can verify happens, if I use the latest version.

**Comment by PLOKMJNB** [comment]
> I can verify happens, if I use the latest version.

In which version does it work? I might manually downgrade for the time being

**Comment by justynpride** [comment]
The previous version was ok. I’ve not got a fresh install of latest version to test,

**Comment by justynpride** [comment]
I've just done a fresh install of the latest version and can confirm that the payment details do not appear.
