### ISSUE TITLE
GenerateTicketJob is undefined (wrong use)

### ISSUE THREAD

**Issue by quentincaffeino** [Attendize/Attendize#902]
https://github.com/Attendize/Attendize/blob/323b60a5304eb6aa0f50d326f4f5be503e3caa29/app/Http/Controllers/EventAttendeesController.php#L6

https://github.com/Attendize/Attendize/blob/323b60a5304eb6aa0f50d326f4f5be503e3caa29/app/Http/Controllers/EventAttendeesController.php#L474

**Comment by johannac** [comment]
This has been fixed in PR #918
