### ISSUE TITLE
[BUG] composer install fails with In PackageManifest.php line 131:    Undefined index: name

### ISSUE THREAD

**Issue by jimrome** [Attendize/Attendize#929]
**Describe the bug**
Following instructions at https://www.attendize.com/getting_started.html
**To Reproduce**
1. https://www.attendize.com/getting_started.html
2. follow instructions up to composer install
3. After many installs, I get
4. ` Installing theseer/tokenizer (1.1.3): Extracting archive
  - Installing sebastian/code-unit-reverse-lookup (1.0.1): Extracting archive
  - Installing phpunit/php-code-coverage (7.0.10): Extracting archive
  - Installing phar-io/version (2.0.1): Extracting archive
  - Installing phar-io/manifest (1.0.3): Extracting archive
  - Installing myclabs/deep-copy (1.9.5): Extracting archive
  - Installing phpunit/phpunit (8.5.2): Extracting archive
  - Installing predis/predis (v1.1.1): Extracting archive
  - Installing stripe/stripe-php (v7.22.0): Extracting archive
  - Installing superbalist/php-money (2.0.0): Extracting archive
  - Installing symfony/dom-crawler (v3.4.37): Extracting archive
  - Installing tolerance/tolerance (0.4.2): Extracting archive
  - Installing vinelab/http (v1.5.4): Extracting archive
Package jakub-onderka/php-console-color is abandoned, you should avoid using it. Use php-parallel-lint/php-console-color instead.
Package jakub-onderka/php-console-highlighter is abandoned, you should avoid using it. Use php-parallel-lint/php-console-highlighter instead.
Package league/commonmark-ext-table is abandoned, you should avoid using it. Use league/commonmark instead.
Generating optimized autoload files
Class Tests\Features\UtilsTest located in ./tests/Feature/Utils/UtilsTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Tests\Features\OrganisationWithoutTaxTest located in ./tests/Feature/OrderCancellation/OrganisationWithoutTaxTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Tests\Features\OrganisationWithTaxTest located in ./tests/Feature/OrderCancellation/OrganisationWithTaxTest.php does not comply with psr-4 autoloading standard. Skipping.
Class HTMLPurifier_Language_en_x_test located in ./vendor/ezyang/htmlpurifier/library/HTMLPurifier/Language/classes/en-x-test.php does not comply with psr-0 autoloading standard. Skipping.
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

**In PackageManifest.php line 131:

  Undefined index: name**

Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1`
**Expected behavior**

**Screenshots**

**Environment the bug happens in (hosting server a2hosting.com
 - x86_64 x86_64 x86_64 GNU/Linux
 - Browser Firefox - Version [e.g. 22]

**Version of Attendize you are using**
- Master branch or release tag
today's git pull
**Where you are running Attendize**
Shared Webhost,

**What version or Operating System are you using on the above server**
unsure

**What version of PHP you are using on the above server**
PHP 7.4.20 (cli)
**What web server are you using Attendize with**
Apache.

**Additional context**

**Comment by jimrome** [comment]
This was due to using Composer 2. You need to change the documentation to stop people pulling their hair out. And also, the "php migrate artisan" instruction after one logs in needs to be 
php artisan migrate:fresh --seed

**Comment by raphavini** [comment]
@jimrome 
I'm having the same problem.
Which version composer did you use?

**Comment by jimrome** [comment]
I had to use a prebuilt version that was for OpenSUSE. But we ended up 
using ThunderTix. You get what you pay for. And I did pay for Attendize 
and got no support.

James A. Rome

https://blogs.jamesrome.net

**Comment by raphavini** [comment]
Okay, thanks for the help, I'll keep trying here

**Comment by raphavini** [comment]
I resolved, when I using the command: "composer install"

I got the error: "In PackageManifest.php line 131: Undefined index: name"

So I used the command: "composer update"

After that I followed the manual installation, with the command "php artisan key:generate"

:)
