### ISSUE TITLE
[BUG] Describe your bug

### ISSUE THREAD

**Issue by jimrome** [Attendize/Attendize#930]
**Describe the bug**
Fill in organiser form. Get error 
`Facade\Ignition\Exceptions\ViewException
Trying to get property 'id' of non-object (View: /home/orcmaorg/public_html/Attendize/resources/views/Shared/Layouts/Master.blade.php)
https://orcma.org/Attendize/public/organiser/2/events?first_run=1 
![Attendize View](https://user-images.githubusercontent.com/1304327/122984568-29223080-d36b-11eb-8739-f57618e806e9.png)
`

**To Reproduce**
![AttendizeCreateOrganizer](https://user-images.githubusercontent.com/1304327/122984752-5c64bf80-d36b-11eb-8c70-0eaab18f35bd.png)

2. 
2. Click on 'create organiser
4. See above

**Expected behavior**

**Screenshots**

**Environment the bug happens in (Mac Mojave) (please complete the following information):**
 - OS: [gnu/linux]
 - Browser [Firefox]
 - Version [90.0b10]

**Version of Attendize you are using**
- Master branch from june22, 2021
**Where you are running Attendize**
- Shared Webhost

**What version or Operating System are you using on the above server**
- gnu/linux

**What version PHP 7.4.20 (cli)e.g PHP 7.1
**What web server are you using Attendize with**
- Apache.

**Additional context**

Attendize is the most frustrating package I have ever tried to use.
I need some support please!!

**Comment by jimrome** [comment]
As per the laravel instructions, I moved Attendize outside of public_html and linked Attendize/public to public_html/Attendize. I started afresh, made a new account, created an Organizer, and get exactly the same error:
`Facade\Ignition\Exceptions\ViewException
Undefined variable: organisers (View: /home/orcmaorg/Attendize/resources/views/Shared/Layouts/Master.blade.php)
https://orcma.org/Attendize/organiser/1/events?first_run=1
Hide solutions
Possible typo $organisers

Did you mean $organiser?
`
HELP please

**Comment by jimrome** [comment]
Grrr. https://github.com/Attendize/Attendize/issues/871 fixed this. This is a show stopper! Why isn't it fixed in the distro???

**Comment by jimrome** [comment]
So I am now one step further along. I have wasted a week on this now. 
I am on the Create Event page, and am unable to fill in the dates. The boxes highlight but do not accept anything
What format is required? I tried numbers and letters, nothing is accepted.
![AttendizeCreateEvent](https://user-images.githubusercontent.com/1304327/123314132-34569700-d4f8-11eb-9253-6639fb68852f.png)

**Comment by jimrome** [comment]
These fields are READ ONLY!!!
![AttendizeReadOnly](https://user-images.githubusercontent.com/1304327/123450614-eea6d680-d5aa-11eb-869f-1abb6164e162.png)

**Comment by johannac** [comment]
Hi @jimrome I understand you're frustrated trying to get your install up and running, but please keep your bug reports professional in tone. This isn't a support forum, but we can try to help when possible. All the maintainers of this project have full time jobs that do not include working on this free and open source software. We have community guidelines posted here https://github.com/Attendize/Attendize/blob/develop/CODE_OF_CONDUCT.md for your reference.

With regards to #871 I merged this only 2 days ago, and it will be tagged into a release shortly. 

With regards to your latest screen shot about the start/end date: these fields use javascript to show a date/time modal. Please ensure js is enabled in your browser and the files are being loaded on the page from your web server properly. 

I'm going to go ahead and close this ticket as there's no software bug here, and we aren't able to provide general tech support for web servers and javascript.
