### ISSUE TITLE
[BUG] Demo sites not working

### ISSUE THREAD

**Issue by iPublicis** [Attendize/Attendize#932]
**Describe the bug**
When going to the demo website it just shows a page to sell services from 123Reg.

**To Reproduce**
1. Go to http://attendize.website/e/799/attendize-test-event-w-special-guest-attendize
2. or Go to http://attendize.website/signup
4. It shows a page to sell services with the message "Want your own website? Get online with Website Builder "

**Expected behavior**
I expected to see the application demo

**Additional context**

**Comment by johannac** [comment]
The demo site has been retired. I've removed the links from the web site.
