### ISSUE TITLE
[BUG] Attendize is undefined

### ISSUE THREAD

**Issue by jimrome** [Attendize/Attendize#933]
**Describe the bug**
Trying to find out why event date fields do not work

**To Reproduce**
1. Create an event. Try to fill in the date
2. nothing happens
See attached screen shot of the problem
![AttendizeNot Defined](https://user-images.githubusercontent.com/1304327/123643878-daedb100-d7f2-11eb-91b6-45fb88f53e70.png)

Where is it supposed to be defined?

**Expected behavior**

**Screenshots**

**Environment the bug happens in (Desktop, Mobile, CLI) (please complete the following information):**
 - OS: [e.g. Mac, iOS, Windows]

**Version of Attendize you are using**
- Master branch or release tag

**Where you are running Attendize**
- in Docker, a Virtual Machine, Shared Webhost, VPS etc

**What version or Operating System are you using on the above server**
- e.g. Ubuntu 14.04

**What version of PHP you are using on the above server**
- e.g PHP 7.1
**What web server are you using Attendize with**
- Nginx or Apache.

**Additional context**

**Comment by ranfysvalle02** [comment]
@jimrome - I stumbled upon this error as well when I was making modifications to the views; I was able to fix it by just removing my changes and doing them all over again, this time more carefully. I'm not exactly sure what caused it - but if you provide a little more information - I'd love to help.

**What were you doing to the source code when this happened?**

**Where are you running this?**

**PHP Version? Operating System?**

**Comment by jimrome** [comment]
Thanks, I need help.

I did not change any views.

This happens when I try to make a new event. It is impossible to enter 
the dates in the date fields, and there are no date-picker pop-ups. 
Looking in debug mode, I find the Attendize is undefined error. There 
was a similar error for Organiser, but I edited the code to fix that as 
per another post.

It is running on my web hoster A2hosting running gnu linux. PHP is 7.4.

Where is Attendize defined?

James A. Rome

***@***.***
https://blogs.jamesrome.net

**Comment by jimrome** [comment]
I installed Attendize using the Softaculous installer, and it worked. So 
something must be wrong with the instructions that I followed to the letter.

The Attendize download page should suggest using this if people have it 
on their host.

James A. Rome

***@***.***
https://blogs.jamesrome.net
