### ISSUE TITLE
[BUG] Can't cancel a paid order

### ISSUE THREAD

**Issue by clawfire** [Attendize/Attendize#940]
**Describe the bug**
When trying to cancel an order (because a client asks for a refund) I cannot process it and got the error message: `You cannot cancel this PaymentIntent because it has a status of succeeded. Only a PaymentIntent with one of the following statuses may be canceled: requires_payment_method, requires_capture, requires_confirmation, requires_action.`

**To Reproduce**
1. Go to orders
2. Select Cancel for an order paid
3. Select the tickets to refund
4. Click cancel. Nothing happens
5. Check the 200 responses of the AJAX Call

**Expected behavior**
Initiate a refund through the payment gateway and cancel the order + attendees

**Version of Attendize you are using**
- tag 2.2.2
- Stripe SCA

**Where you are running Attendize**
- in Gandi Simple Hosting

**What version of PHP you are using on the above server**
- e.g PHP 7.4

**What web server are you using Attendize with**
- Apache.

**Comment by GeekLabsUK** [comment]
got the same issue

**Comment by clawfire** [comment]
This issue is SO annoying.

**Comment by GeekLabsUK** [comment]
also got this issue so cant cancel a ticket. i can refund manually but wont allow me to cancel a ticket so the ticket could still get used.

**Comment by storca** [comment]
Hey
If you're still here I fixed this bug in #1016  , you may use storca/Attendize and develop branch while my changes are approved!
