### ISSUE TITLE
[documentation] How to change currency

### ISSUE THREAD

**Issue by jimrome** [Attendize/Attendize#942]
**Describe the bug**
I need to change currency from Euros to dollars. 

**To Reproduce**
1. I went to Attendize/config/attendize.php and guessed that 
2. 'default_currency'              => 1, #Dollar
2. I then made a ticket, and it is still listen in Euros.
Is there some other way to specify the currency? Is '1' the code for Dollars?

**Comment by johannac** [comment]
Hi @jimrome There are multiple places to change the currency, to allow you to run many different kinds of events with different requirements if needed. 

The config file specifies the base default currency for a new system. You can also set the default currency in the Organizer's profile (go to Account Settings in the top right menu). Lastly, you can set the currency at the Event level, when creating a new event or if you already have an event, you can change the currency by clicking Edit on the event.

**Comment by jimrome** [comment]
Thank you!

James A. Rome

***@***.***
https://blogs.jamesrome.net
