### ISSUE TITLE
Getting 404 on install and home page 

### ISSUE THREAD

**Issue by jaisharmaimcl** [Attendize/Attendize#943]
Hi, I have installed Attendize on my local windows comupter in XAMPP. But when i am opening the url localhost/attendize it is showing 404. can you please help me out on it.

![image](https://user-images.githubusercontent.com/17176741/125231672-cfbd7980-e2f8-11eb-8c8f-170205e5348f.png)

**Comment by EloneSampaio** [comment]
access with url:  http://localhost/attendize/public/install
