### ISSUE TITLE
version is not updated to 2.2.3 in 2.2.3 version.

### ISSUE THREAD

**Issue by GaneshKandu** [Attendize/Attendize#945]
Hi,

version is not updated to 2.2.3 in [https://github.com/Attendize/Attendize/archive/refs/tags/v2.2.3.zip](https://github.com/Attendize/Attendize/archive/refs/tags/v2.2.3.zip).

[https://github.com/Attendize/Attendize/blob/develop/VERSION](
https://github.com/Attendize/Attendize/blob/develop/VERSION)

**Comment by johannac** [comment]
Oof! Thank you! I always seem to forget to do this. I will update it.
