### ISSUE TITLE
[BUG] Error generating ticket on payment submission

### ISSUE THREAD

**Issue by justynpride** [Attendize/Attendize#956]
**Describe the bug**
When using a fresh installation I am encountering the following error once payment is submitted. The order processes ok, but I get an Whoops error and it doesn't take me to the order completed screen. The log file shows: 

[2021-08-07 08:52:39] production.DEBUG: Queueing Order Notification Job  
[2021-08-07 08:52:41] production.DEBUG: Queueing Order Tickets Job  
[2021-08-07 08:52:41] production.ERROR: Error generating ticket. This can be due to permissions on vendor/nitmedia/wkhtml2pdf/src/Nitmedia/Wkhtml2pdf/lib. This folder requires write and execute permissions for the web user

**To Reproduce**
1. Submit a payment

**Expected behavior**
Completed payment processing with no error message

**Version of Attendize you are using**
- Master branch 2.3.1

**Where you are running Attendize**
- VPS

**What version or Operating System are you using on the above server**
- Debian 10.10 (x86_64)

**What version of PHP you are using on the above server**
- e.g PHP 7.4
- 
**What web server are you using Attendize with**
- Apache.

**Additional context**
Is the error on my server or is there something extra needed in setup instructions?

**Comment by Alezcano16** [comment]
Hi, @justynpride  Please, can you tell me how to solve this bug, exactly the same thing happens to me

**Comment by DirectITServicesUK** [comment]
Not very helpful.
