### ISSUE TITLE
[BUG] Session persists between all browsers and session on a device

### ISSUE THREAD

**Issue by quentincaffeino** [Attendize/Attendize#958]
**Describe the bug**
Is this happening to only me? When I login onto website I can then access the admin panel in all browsers and incognito on a same device. It seems very strange and I couldn't find anything about remotely related.

**To Reproduce**
1. Open Attendize
2. Login
3. Open any other browser or incognito mode on a same device
4. You are logged in

**Expected behavior**
You are not logged in.

**Environment the bug happens in (Desktop, Mobile, CLI) (please complete the following information):**
 - OS: Linux
 - Browser: Chrome, Brave, Firefox
 - Version: Latest

**Version of Attendize you are using**
- v2.3.1

**Where you are running Attendize**
- in Docker

**What version or Operating System are you using on the above server**
- fedora 5.13.6-200.fc34.x86_64

**What version of PHP you are using on the above server**
- PHP 7.4

**What web server are you using Attendize with**
- Nginx and Swoole.

**Additional context**
- If this happens only to me I think old laravel version and swoole are to blame, but can't be sure.

**Comment by justynpride** [comment]
@quentincaffeino I can't replicate it. Don't know if that helps!

**Comment by quentincaffeino** [comment]
Thanks, that helps. Then it almost definitely swoole.
