### ISSUE TITLE
ide-helper:models generator error

### ISSUE THREAD

**Issue by kiuka** [Attendize/Attendize#96]
Hello,

When I generate models with ide-helper (artisan ide-helper:models) it throws exception:
 [Symfony\Component\Debug\Exception\FatalErrorException]
  Cannot use Illuminate\Routing\Controller as Controller because the name is already in use

The error is In App\Http\Controllers\UserLogoutController, it should look like the following:

....
use Illuminate\Routing\Controller as BaseController;

class UserLogoutController extends BaseController
{
....

**Comment by daveearley** [comment]
This should be fixed now.
