### ISSUE TITLE
Can't disable new user registration & more

### ISSUE THREAD

**Issue by signorettae** [Attendize/Attendize#969]
Hello, I have to ask some questions about something I would like to do. 
In order:
 
- disable new user registration;
- disable ticket generation in order to send a custom message such as "we are cheking your data, if everything is ok you'll receive the ticket soon" and then a different tiket (in PDF);
- move the questions in the first half of the order page and disable the company checkbox.

Thank you in advance

**Comment by johannac** [comment]
@signorettae What is your question about these items? Are you asking how to do these things?

**Comment by storca** [comment]
Hi

I'm having a similar problem : I'd like to disable public user registration on attendize's login page, but I can't find it

I'm using Attendize 2.1.0 (with user roles and permissions)

Thanks for any help :)

**Comment by storca** [comment]
I've got a solution to my problem : to disable public registration, you have to set ``ATTENDIZE_DEV``` and ```ATTENDIZE_CLOUD``` to false in your .env file
