### ISSUE TITLE
[BUG] Docker Apache-Build does not work

### ISSUE THREAD

**Issue by simkea** [Attendize/Attendize#979]
**Describe the bug**
The docker setup for the Apache build somehow does not work.

Can you check this again?

**To Reproduce**
Run image build with:
>docker build --tag attendize_base --target base --file Dockerfile-apache .
>docker build --tag attendize_worker --target worker --cache-from attendize_base:latest --file Dockerfile-apache .
>docker build --tag attendize_web --target web --cache-from attendize_worker:latest --file Dockerfile-apache .

Then run setup:
>cp .env.example .env
>docker-compose up -d
>docker-compose exec web sh -c 'wait-for-it db:3306 -t 180 && php artisan key:generate && php artisan migrate'
>docker-compose up -d
>docker-compose exec web sh -c 'wait-for-it web:443 -t 120'

After the setup was performed without error message, I open the URL.
**Unfortunately, it seems that the apache web server is not working.**

**Environment the bug happens in (Desktop, Mobile, CLI) (please complete the following information):**
 - Windows
 - chrome

**Version of Attendize you are using**
- develop

**Where you are running Attendize**
- local, Docker

**What version or Operating System are you using on the above server**
- Windows 10, WSL2

**What web server are you using Attendize with**
- Apache.

**Comment by quentincaffeino** [comment]
Do you have any logs of it? Sadly I'm not sure I will be able to help, since I'm not using windows nor docker setup provided in this repo. But most of the time logs have the answers.

To see logs you would need to start without detach flag (-d) or run `docker-compose logs --follow` after you setup the project.

**Comment by simkea** [comment]
Okay sorry, my fault:
There is no SSL certificate with the Apache build yet. Therefore the URL must be:

>http://localhost:8080/
