### ISSUE TITLE
We'll be back soon

### ISSUE THREAD

**Issue by maxkpower** [Attendize/Attendize#980]
After installing Attendize successfully everything seemed to work well until I tried to create a ticket.
![image](https://user-images.githubusercontent.com/25062001/134682330-d2037b19-32b6-454d-9745-3a64200e40b4.png)

If I clear Cookies and Sign Up with a new Account the Dashboard seems to be working fine again. Only when I want to create tickets it breaks and the user is "blocked".

Version 2.3.1

**Comment by quentincaffeino** [comment]
What was the problem?

**Comment by princerai162** [comment]
how you fix that issue?

**Comment by maxkpower** [comment]
My Mailserver wasn't set up correctly.
