### ISSUE TITLE
[BUG] Can not do the payment using credit card with Stripe gateway

### ISSUE THREAD

**Issue by ericknyoto** [Attendize/Attendize#984]
I already change the token to Live key,
but when I tried to make the payment there were error that shows:
No such token: 'tok_1JffqAArjPIbseAdmT6UfEtL'

I can make sure that the live key token was correct.

What am I missing here?

**Comment by quentincaffeino** [comment]
Try changing ATTENDIZE_DEV (or something like that) to true, basically try enabling dev mode, this way it will output more logs, maybe it will help

**Comment by ericknyoto** [comment]
> Try changing ATTENDIZE_DEV (or something like that) to true, basically try enabling dev mode, this way it will output more logs, maybe it will help

Thanks, I already make ATTENDIZE_DEV set to true, but the error, still the same.
Is there any settings or configuration that I need to set to be on production?

I check the request was like this

```
id: "tok_1Jfh2QArjPIbseAdepYIHDPC"
livemode: false
object: "token"
type: "card"
used: false
```

**Comment by quentincaffeino** [comment]
It doesn't mean that changing this value would make it work. This only makes attendize more verbose putting more information into logs. So you might want to look at those (/storage/logs)

I don't use stripe with attendize so I'm not sure if it even works. But looking at the code I see that there is no way for switching from demo to live key. So I guess you would need modify stripe payment gateway sources.

**Comment by paws13** [comment]
@clawfire Could you elaborate on your config for stripe payments?

**Comment by clawfire** [comment]
I just selected Stripe SCA into the Account Setting → Payment and put my 2 Stripe's key 😃

**Comment by paws13** [comment]
I did that too, and the credit card fields stop showing when I go to checkout...
