### ISSUE TITLE
Covid QR code

### ISSUE THREAD

**Issue by maccored** [Attendize/Attendize#997]
Can the ability to optionally request a QR code to be uploaded if required? (could be photo ID to prove ticket authenticity or Covid19 QR code)

**Comment by clawfire** [comment]
At that time no.
You could imagine doing so by a file type of question in a survey but file upload isn't supported yet.

Take notes that storing a photo ID or COVID19 certificate would may come with a lot of security and privacy issues you'll need to handle yourself.
