### ISSUE TITLE
[BUG] Error sending email- when generating/attaching ticket only

### ISSUE THREAD

**Issue by MacBadger** [Attendize/Attendize#998]
**Error sending email- when generating ticket only**
When mailing anything containing a ticket it doesn't complete and returns error after longer period (approximately 70seconds) when either:-
1. when using 'action > resend ticket' in attendees page
2. when using 'invite attendee' in attendees page
3. also note no email sent on new ticket purchase with error thrown up- but it does register in attendees (dummy payment gateway) "whoops! it looks like the server returned an error..."

It works fine sending emails otherwise- such as through messaging. It's just when sending with a ticket.

**To Reproduce**
1. Go to 'attendees'
2. Click on 'action'
3. Scroll down and click 'resend ticket'
4.Click on 'send ticket'
5. See error

**Expected behavior**
Send, or resend email when done with ticket

**Screenshots**

**Environment the bug happens in (Desktop, Mobile, CLI) (please complete the following information):**
 - OS: Fedora 34
 - Browser Vivaldi (Chrome)

**Version of Attendize you are using**
- Master branch 2.4.0

**Where you are running Attendize**
- VPS

**What version or Operating System are you using on the above server**
- e.g. debian 10

**What version of PHP you are using on the above server**
- e.g PHP 7.4
**What web server are you using Attendize with**
- Apache.

**Comment by quentincaffeino** [comment]
Set these variables in your `.env`

```
APP_ENV=dev
APP_DEBUG=true
ATTENDIZE_DEV=true
```

Try sending a ticket, it should output more logs in `session/logs/laravel*`, please post those here.

**Comment by MacBadger** [comment]
I actuall just realised that libxrender was missing! Sorted now.
