### ISSUE TITLE
[BUG] Unknown column in 'field list'

### ISSUE THREAD

**Issue by MacBadger** [Attendize/Attendize#999]
**Describe the bug**
When attempting to change which social media links show anywhere (check/uncheck), it fails. Log reads:

`$ Unknown column 'social_show_googleplus' in 'field list' at /home/tickets/Attendize/vendor/doctrine/dbal/lib/Doctrine/DBAL/Drive$
[stacktrace]
`
A remnant to the old google plus days?

**To Reproduce**
Un-check any of the social media options under customize - social and click save

**Expected behavior**
save the unchecking

**Screenshots**

**Environment the bug happens in (Desktop, Mobile, CLI) (please complete the following information):**
 - OS: Fedora 34
 - Vivaldi (chrome)

**Version of Attendize you are using**
- Master branch 2.4.0

**Where you are running Attendize**
- VPS

**What version or Operating System are you using on the above server**
- Debian 10

**What version of PHP you are using on the above server**
- e.g PHP 7.4
**What web server are you using Attendize with**
- Apache.

**Comment by quentincaffeino** [comment]
g+ was removed but not completely, some parts were forgotten. Fix is done but not merged yet. Could you merge this pr https://github.com/Attendize/Attendize/pull/978 on your instance?

**Comment by MacBadger** [comment]
Thank you! I did search but didn't come across #978 it saved me time- i was about to start looking for the lines myself when i thought i'd check back. thanks very much.
